import Lanius.Extraction.VerifiedFrontend.Surface.CanonicalTokens.Claims.Assembly
import Lanius.Extraction.VerifiedFrontend.Surface.CanonicalTokens.Origins.Trace
import Lanius.Extraction.VerifiedFrontend.Surface.CanonicalTokens.Decode.Assembly
namespace Lanius.Extraction
set_option maxRecDepth 500000
def verifiedFrontendCanonicalTokensReconstructionKernel : ProvenanceSurfaceReconstruction := {
  reconstructed := verifiedFrontendCanonicalTokensReconstructedKernel
  claims := verifiedFrontendCanonicalTokensClaimsKernel
  origins := verifiedFrontendCanonicalTokensOrigins
}
theorem verifiedFrontendCanonicalTokens_reconstruction_found_kernel :
    reconstructArtifactSurfaceWithProvenanceView verifiedFrontendCanonicalTokensArtifact verifiedFrontendCanonicalTokensView
      verifiedFrontendCanonicalTokensOrigins = some verifiedFrontendCanonicalTokensReconstructionKernel :=
  reconstructArtifactSurfaceWithProvenanceView_of_components verifiedFrontendCanonicalTokensView
    verifiedFrontendCanonicalTokensOrigins verifiedFrontendCanonicalTokensReconstructedKernel verifiedFrontendCanonicalTokensClaimsKernel
    verifiedFrontendCanonicalTokens_reconstructed_found_kernel verifiedFrontendCanonicalTokens_claims_found_kernel
def verifiedFrontendCanonicalTokensSurfaceKernel : CheckedSurfaceArtifact verifiedFrontendCanonicalTokensArtifact :=
  CheckedSurfaceArtifact.ofOriginsWithParse verifiedFrontendCanonicalTokensView verifiedFrontendCanonicalTokensOrigins
    verifiedFrontendCanonicalTokensParseValidTraceKernel verifiedFrontendCanonicalTokensReconstructionKernel
    verifiedFrontendCanonicalTokens_reconstruction_found_kernel verifiedFrontendCanonicalTokensDecodedSurfaceKernel
    verifiedFrontendCanonicalTokens_decoded_surface_found_kernel verifiedFrontendCanonicalTokens_claims_equal_kernel
    verifiedFrontendCanonicalTokens_origins_checked_kernel
theorem verifiedFrontendCanonicalTokens_surface_checked_kernel : SurfaceArtifactValid verifiedFrontendCanonicalTokensArtifact :=
  CheckedSurfaceArtifact.valid verifiedFrontendCanonicalTokensSurfaceKernel
end Lanius.Extraction
