//! GPU-resident type checking and semantic metadata retention.
//!
//! The type checker records compute passes over token and parser HIR buffers
//! rather than walking an AST on the host. It builds module, name,
//! type-instance, call, method, visibility, predicate, and backend metadata
//! relations on the GPU, then exposes retained buffers to backend phases only
//! through explicit wrapper structs. The maintainer guide for pass-family
//! ownership and resident cache invariants lives in
//! `docs/compiler/type-checker.md`.

use std::{
    collections::HashMap,
    hash::{Hash, Hasher},
    sync::Mutex,
};

mod bind_groups;
mod bind_models;
mod bind_support;
mod module_path;
mod params;
mod pass_loaders;
mod record;
mod resident;
mod util;

use anyhow::Result;
use bind_models::*;
use bind_support::*;
use module_path::*;
use params::*;
use record::*;
use util::*;
use wgpu::util::DeviceExt;

use crate::gpu::{
    buffers::{LaniusBuffer, storage_ro_from_bytes, storage_ro_from_u32s, uniform_from_val},
    device,
    passes_core::{DispatchDim, InputElements, PassData, bind_group, plan_workgroups},
};

/// Semantic rejection classes reported by GPU type-check status words.
///
/// The numeric mapping is owned by GPU status buffers and shader constants.
/// Host diagnostics should preserve the source token or HIR row that made the
/// rejection user-visible.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuTypeCheckCode {
    UnknownType,
    UnresolvedIdent,
    AssignMismatch,
    ReturnMismatch,
    ConditionType,
    BadHir,
    LoopControl,
    InvalidMemberAccess,
    InvalidArrayReturn,
    CallMismatch,
    NameLimit,
    ImportCycle,
    TraitBoundUnsatisfied,
    TraitBoundAmbiguous,
    UnresolvedImport,
    UnsupportedImport,
    ImportPathTooDeep,
    DuplicateModule,
    ModulePathTooDeep,
    InvalidModulePath,
    Unknown(u32),
}

impl GpuTypeCheckCode {
    fn from_u32(value: u32) -> Self {
        match value {
            1 => Self::UnknownType,
            2 => Self::UnresolvedIdent,
            3 => Self::AssignMismatch,
            4 => Self::ReturnMismatch,
            5 => Self::ConditionType,
            6 => Self::BadHir,
            7 => Self::LoopControl,
            8 => Self::InvalidMemberAccess,
            9 => Self::InvalidArrayReturn,
            10 => Self::CallMismatch,
            11 => Self::NameLimit,
            12 => Self::ImportCycle,
            13 => Self::TraitBoundUnsatisfied,
            14 => Self::TraitBoundAmbiguous,
            15 => Self::UnresolvedImport,
            16 => Self::UnsupportedImport,
            17 => Self::ImportPathTooDeep,
            18 => Self::DuplicateModule,
            19 => Self::ModulePathTooDeep,
            20 => Self::InvalidModulePath,
            other => Self::Unknown(other),
        }
    }

    fn description(self) -> String {
        match self {
            Self::UnknownType => "unknown type".to_string(),
            Self::UnresolvedIdent => "unresolved identifier".to_string(),
            Self::AssignMismatch => "type mismatch".to_string(),
            Self::ReturnMismatch => "return type mismatch".to_string(),
            Self::ConditionType => "condition has the wrong type".to_string(),
            Self::BadHir => "invalid syntax or lowered syntax tree".to_string(),
            Self::LoopControl => "invalid loop control".to_string(),
            Self::InvalidMemberAccess => "invalid member access".to_string(),
            Self::InvalidArrayReturn => "invalid array return".to_string(),
            Self::CallMismatch => "call does not match a resolved function or method".to_string(),
            Self::NameLimit => "name is outside the current compiler limit".to_string(),
            Self::ImportCycle => "import cycle".to_string(),
            Self::TraitBoundUnsatisfied => "unsatisfied trait bound".to_string(),
            Self::TraitBoundAmbiguous => "ambiguous trait bound".to_string(),
            Self::UnresolvedImport => "unresolved import".to_string(),
            Self::UnsupportedImport => "unsupported import form".to_string(),
            Self::ImportPathTooDeep => "import path too deep".to_string(),
            Self::DuplicateModule => "duplicate module declaration".to_string(),
            Self::ModulePathTooDeep => "module path too deep".to_string(),
            Self::InvalidModulePath => "invalid module path".to_string(),
            Self::Unknown(code) => format!("unknown type-check error (code {code})"),
        }
    }
}

/// Error returned after a recorded type-check pass sequence is finished.
#[derive(Debug)]
pub enum GpuTypeCheckError {
    /// The GPU status buffer rejected the program and supplied a token/code
    /// tuple for host-side diagnostic mapping.
    Rejected {
        token: u32,
        code: GpuTypeCheckCode,
        detail: u32,
    },
    /// GPU setup, submission, or readback failed before semantic status could
    /// be decoded.
    Gpu(anyhow::Error),
}

/// Parser HIR buffers consumed by type-check recording.
///
/// These are borrowed for the duration of a recorded check. Any value required
/// after parser resident buffers are released must be cloned into an owned
/// retained wrapper before this struct is constructed.
#[derive(Clone, Copy)]
pub struct GpuTypeCheckHirItemBuffers<'a> {
    pub node_kind: &'a wgpu::Buffer,
    pub parent: &'a wgpu::Buffer,
    pub first_child: &'a wgpu::Buffer,
    pub next_sibling: &'a wgpu::Buffer,
    pub subtree_end: &'a wgpu::Buffer,
    pub kind: &'a wgpu::Buffer,
    pub name_token: &'a wgpu::Buffer,
    pub type_form: &'a wgpu::Buffer,
    pub type_value_node: &'a wgpu::Buffer,
    pub type_len_token: &'a wgpu::Buffer,
    pub type_len_value: &'a wgpu::Buffer,
    pub type_file_id: &'a wgpu::Buffer,
    pub type_path_leaf_node: &'a wgpu::Buffer,
    pub bound_path_owner_by_leaf: &'a wgpu::Buffer,
    pub type_arg_start: &'a wgpu::Buffer,
    pub type_arg_count: &'a wgpu::Buffer,
    pub type_arg_next: &'a wgpu::Buffer,
    pub type_arg_owner: &'a wgpu::Buffer,
    pub type_arg_rank: &'a wgpu::Buffer,
    pub type_alias_target_node: &'a wgpu::Buffer,
    pub fn_return_type_node: &'a wgpu::Buffer,
    pub param_record: &'a wgpu::Buffer,
    pub param_type_node: &'a wgpu::Buffer,
    pub method_owner_node: &'a wgpu::Buffer,
    pub method_impl_node: &'a wgpu::Buffer,
    pub method_name_token: &'a wgpu::Buffer,
    pub method_first_param_token: &'a wgpu::Buffer,
    pub method_receiver_mode: &'a wgpu::Buffer,
    pub method_visibility: &'a wgpu::Buffer,
    pub method_signature_flags: &'a wgpu::Buffer,
    pub method_impl_receiver_type_node: &'a wgpu::Buffer,
    pub expr_record: &'a wgpu::Buffer,
    pub expr_result_node: &'a wgpu::Buffer,
    pub expr_result_root_node: &'a wgpu::Buffer,
    pub expr_int_value: &'a wgpu::Buffer,
    pub member_receiver_node: &'a wgpu::Buffer,
    pub member_receiver_token: &'a wgpu::Buffer,
    pub member_name_token: &'a wgpu::Buffer,
    pub stmt_record: &'a wgpu::Buffer,
    pub stmt_scope_end: &'a wgpu::Buffer,
    pub nearest_stmt_node: &'a wgpu::Buffer,
    pub nearest_block_node: &'a wgpu::Buffer,
    pub nearest_enclosing_control_node: &'a wgpu::Buffer,
    pub nearest_loop_node: &'a wgpu::Buffer,
    pub nearest_fn_node: &'a wgpu::Buffer,
    pub array_lit_first_element: &'a wgpu::Buffer,
    pub array_lit_element_count: &'a wgpu::Buffer,
    pub array_lit_context_stmt_node: &'a wgpu::Buffer,
    pub array_element_parent_lit: &'a wgpu::Buffer,
    pub array_element_next: &'a wgpu::Buffer,
    pub namespace: &'a wgpu::Buffer,
    pub visibility: &'a wgpu::Buffer,
    pub path_start: &'a wgpu::Buffer,
    pub path_end: &'a wgpu::Buffer,
    pub file_id: &'a wgpu::Buffer,
    pub import_target_kind: &'a wgpu::Buffer,
    pub call_callee_node: &'a wgpu::Buffer,
    pub call_context_stmt_node: &'a wgpu::Buffer,
    pub call_arg_start: &'a wgpu::Buffer,
    pub call_arg_end: &'a wgpu::Buffer,
    pub call_arg_count: &'a wgpu::Buffer,
    pub call_arg_parent_call: &'a wgpu::Buffer,
    pub call_arg_ordinal: &'a wgpu::Buffer,
    pub variant_parent_enum: &'a wgpu::Buffer,
    pub variant_payload_start: &'a wgpu::Buffer,
    pub variant_payload_count: &'a wgpu::Buffer,
    pub variant_payload_node: &'a wgpu::Buffer,
    pub match_scrutinee_node: &'a wgpu::Buffer,
    pub match_arm_start: &'a wgpu::Buffer,
    pub match_arm_count: &'a wgpu::Buffer,
    pub match_arm_next: &'a wgpu::Buffer,
    pub match_arm_pattern_node: &'a wgpu::Buffer,
    pub match_arm_payload_start: &'a wgpu::Buffer,
    pub match_arm_payload_count: &'a wgpu::Buffer,
    pub match_arm_result_node: &'a wgpu::Buffer,
    pub match_payload_owner_arm: &'a wgpu::Buffer,
    pub match_payload_match_node: &'a wgpu::Buffer,
    pub match_payload_ordinal: &'a wgpu::Buffer,
    pub struct_field_parent_struct: &'a wgpu::Buffer,
    pub struct_field_ordinal: &'a wgpu::Buffer,
    pub struct_field_type_node: &'a wgpu::Buffer,
    pub struct_decl_field_start: &'a wgpu::Buffer,
    pub struct_decl_field_count: &'a wgpu::Buffer,
    pub struct_lit_head_node: &'a wgpu::Buffer,
    pub struct_lit_context_stmt_node: &'a wgpu::Buffer,
    pub struct_lit_field_start: &'a wgpu::Buffer,
    pub struct_lit_field_count: &'a wgpu::Buffer,
    pub struct_lit_field_parent_lit: &'a wgpu::Buffer,
    pub struct_lit_field_value_node: &'a wgpu::Buffer,
    pub semantic_dense_node: &'a wgpu::Buffer,
    pub semantic_count: &'a wgpu::Buffer,
}

/// Scratch and metadata buffers supplied by the caller after earlier phase data
/// has been proven dead or intentionally retained.
///
/// Buffer identity is part of the resident type-check cache contract whenever a
/// pass binds one of these buffers. Add new bind-group-affecting buffers to the
/// resident fingerprint instead of relying on the raw `wgpu::Buffer` handle.
#[derive(Clone, Copy)]
pub struct GpuTypeCheckExternalScratchBuffers<'a> {
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub type_expr_ref_tag: &'a wgpu::Buffer,
    pub type_expr_ref_payload: &'a wgpu::Buffer,
    pub type_generic_param_slot_by_token: &'a wgpu::Buffer,
    pub type_const_param_slot_by_token: &'a wgpu::Buffer,
    pub record_family_flag: Option<&'a wgpu::Buffer>,
    pub module_record_prefix: &'a wgpu::Buffer,
    pub record_scan_local_prefix: &'a wgpu::Buffer,
    pub module_path_key_radix_block_histogram: &'a wgpu::Buffer,
    pub module_path_key_radix_block_bucket_prefix: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub decl_module_file_id: &'a wgpu::Buffer,
    pub decl_module_id: &'a wgpu::Buffer,
    pub decl_name_id: &'a wgpu::Buffer,
    pub decl_namespace: &'a wgpu::Buffer,
    pub decl_visibility: &'a wgpu::Buffer,
    pub decl_token_start: &'a wgpu::Buffer,
    pub decl_token_end: &'a wgpu::Buffer,
    pub decl_key_to_decl_id: &'a wgpu::Buffer,
    pub decl_key_order_tmp: &'a wgpu::Buffer,
    pub decl_status: &'a wgpu::Buffer,
    pub call_param_count: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub call_arg_record: &'a wgpu::Buffer,
    pub function_lookup_key: &'a wgpu::Buffer,
    pub function_lookup_fn: &'a wgpu::Buffer,
    pub type_decl_generic_param_count: &'a wgpu::Buffer,
    pub type_decl_generic_param_count_by_node: &'a wgpu::Buffer,
    pub type_instance_head_token: &'a wgpu::Buffer,
    pub type_instance_arg_start: &'a wgpu::Buffer,
    pub type_instance_arg_count: &'a wgpu::Buffer,
    pub type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub type_instance_elem_ref_tag: &'a wgpu::Buffer,
    pub type_instance_elem_ref_payload: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub type_instance_state: &'a wgpu::Buffer,
    pub decl_type_key_to_decl_id: &'a wgpu::Buffer,
    pub decl_value_key_to_decl_id: &'a wgpu::Buffer,
    pub method_decl_module_id: &'a wgpu::Buffer,
    pub method_decl_impl_node: &'a wgpu::Buffer,
    pub method_decl_name_token: &'a wgpu::Buffer,
    pub method_decl_name_id: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub method_decl_receiver_mode: &'a wgpu::Buffer,
    pub method_decl_visibility: &'a wgpu::Buffer,
    pub method_key_to_fn_token: &'a wgpu::Buffer,
    pub method_key_status: &'a wgpu::Buffer,
    pub method_key_radix_block_histogram: &'a wgpu::Buffer,
    pub method_key_radix_block_bucket_prefix: &'a wgpu::Buffer,
    pub method_call_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_call_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_call_name_id: &'a wgpu::Buffer,
    pub method_call_site_module_id: &'a wgpu::Buffer,
    pub import_visible_type_count: &'a wgpu::Buffer,
    pub import_visible_value_count: &'a wgpu::Buffer,
    pub import_visible_type_prefix: &'a wgpu::Buffer,
    pub import_visible_value_prefix: &'a wgpu::Buffer,
    pub resolved_type_decl: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_type_status: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub member_result_ref_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_tag: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_payload: &'a wgpu::Buffer,
    pub struct_init_field_context_instance: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub path_start: &'a wgpu::Buffer,
    pub path_len: &'a wgpu::Buffer,
    pub path_segment_count: &'a wgpu::Buffer,
    pub path_segment_base: &'a wgpu::Buffer,
    pub path_segment_name_id: &'a wgpu::Buffer,
    pub path_segment_token: &'a wgpu::Buffer,
    pub path_owner_hir: &'a wgpu::Buffer,
    pub path_owner_token: &'a wgpu::Buffer,
    pub path_owner_module_id: &'a wgpu::Buffer,
    pub path_kind: &'a wgpu::Buffer,
}

impl std::fmt::Display for GpuTypeCheckError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GpuTypeCheckError::Rejected { code, .. } => {
                write!(f, "type check error: {}", code.description())
            }
            GpuTypeCheckError::Gpu(_) => {
                f.write_str("type-check execution failed before semantic status could be decoded")
            }
        }
    }
}

impl std::error::Error for GpuTypeCheckError {}

#[cfg(test)]
mod tests {
    use super::{GpuTypeCheckCode, GpuTypeCheckError};

    #[test]
    fn type_check_error_display_is_user_facing() {
        let error = GpuTypeCheckError::Rejected {
            token: 12,
            code: GpuTypeCheckCode::UnknownType,
            detail: 7,
        };

        let message = error.to_string();
        assert_eq!(message, "type check error: unknown type");
        assert!(!message.contains("GPU"));
        assert!(!message.contains("near token"));
        assert!(!message.contains("status token"));
    }

    #[test]
    fn type_check_gpu_error_display_omits_backend_detail() {
        let error = GpuTypeCheckError::Gpu(anyhow::anyhow!(
            "typecheck.modules.projected_refs status readback failed"
        ));

        let message = error.to_string();
        assert_eq!(
            message,
            "type-check execution failed before semantic status could be decoded"
        );
        assert!(!message.contains("projected_refs"));
        assert!(!message.contains("readback"));
        assert!(!message.contains("GPU"));
    }
}

impl From<anyhow::Error> for GpuTypeCheckError {
    fn from(err: anyhow::Error) -> Self {
        Self::Gpu(err)
    }
}

/// GPU type-check driver and resident state cache.
///
/// A `GpuTypeChecker` owns pass pipelines, the main status buffer, and reusable
/// resident bind groups/scratch storage. Callers record type-check work into an
/// existing command encoder and finish it after submission/readback.
pub struct GpuTypeChecker {
    passes: TypeCheckPasses,
    params_buf: LaniusBuffer<TypeCheckParams>,
    status_buf: LaniusBuffer<u32>,
    status_readback: wgpu::Buffer,
    resident_state: Mutex<Option<ResidentTypeCheckState>>,
}

/// Marker returned when type-check work has been recorded into a command
/// encoder and must still be submitted/read back by the caller.
pub struct RecordedTypeCheck;

#[derive(Clone, Copy)]
struct ResidentTypeCheckCacheKey {
    source_file_capacity: u32,
    token_capacity: u32,
    hir_node_capacity: u32,
    parser_hir_node_capacity: u32,
    input_fingerprint: u64,
    uses_hir_control: bool,
    uses_hir_items: bool,
}

struct TypeCheckPasses {
    hir_active_dispatch_args: PassData,
    names_mark_lexemes: PassData,
    counted_scan_local: PassData,
    counted_scan_blocks: PassData,
    counted_scan_apply: PassData,
    count_dispatch_args: PassData,
    count_pair_max_dispatch_args: PassData,
    names_scatter_lexemes: PassData,
    names_radix_dispatch_args: PassData,
    names_radix_byte_dispatch_args: PassData,
    names_radix_histogram: PassData,
    names_radix_bucket_prefix_active: PassData,
    names_radix_bucket_bases_active: PassData,
    names_radix_bucket_prefix: PassData,
    names_radix_bucket_bases: PassData,
    names_radix_scatter: PassData,
    names_radix_dedup: PassData,
    names_radix_assign_ids: PassData,
    language_names_clear: PassData,
    language_type_codes_clear: PassData,
    language_decls_materialize: PassData,
    modules_mark_records: PassData,
    modules_extract_record_flag: PassData,
    modules_scatter_paths: PassData,
    modules_count_path_segments: PassData,
    modules_scatter_path_segments: PassData,
    modules_scatter_module_records: PassData,
    modules_scatter_import_records: PassData,
    modules_scatter_decl_core_records: PassData,
    modules_clear_decl_lookup: PassData,
    modules_scatter_decl_span_records: PassData,
    modules_build_module_keys: PassData,
    modules_sort_module_keys_histogram: PassData,
    modules_sort_module_keys_scatter: PassData,
    modules_validate_modules: PassData,
    modules_resolve_imports: PassData,
    modules_seed_import_edge_key_order: PassData,
    modules_sort_import_edges: PassData,
    modules_sort_import_edges_scatter: PassData,
    modules_validate_import_cycles: PassData,
    modules_clear_file_module_map: PassData,
    modules_build_file_module_map: PassData,
    modules_attach_record_modules: PassData,
    modules_seed_decl_key_order: PassData,
    modules_sort_decl_keys: PassData,
    modules_sort_decl_keys_scatter: PassData,
    modules_validate_decls: PassData,
    modules_mark_decl_namespace_keys: PassData,
    modules_scatter_decl_namespace_keys: PassData,
    modules_mark_public_decl_keys: PassData,
    modules_count_import_visibility: PassData,
    modules_scatter_import_visibility: PassData,
    modules_sort_import_visible_keys: PassData,
    modules_sort_import_visible_keys_scatter: PassData,
    modules_build_import_visible_key_tables: PassData,
    modules_validate_import_visible_keys: PassData,
    modules_resolve_local_paths: PassData,
    modules_resolve_imported_paths: PassData,
    modules_resolve_qualified_paths: PassData,
    modules_clear_type_path_types: PassData,
    modules_project_type_paths: PassData,
    modules_validate_type_paths: PassData,
    modules_project_type_aliases: PassData,
    modules_project_type_instances: PassData,
    modules_mark_value_call_paths: PassData,
    modules_project_value_paths: PassData,
    modules_consume_value_calls: PassData,
    modules_mirror_value_call_leaf: PassData,
    modules_consume_value_consts: PassData,
    modules_consume_value_enum_units: PassData,
    modules_consume_value_enum_calls: PassData,
    modules_validate_value_enum_call_payloads: PassData,
    modules_finalize_value_enum_calls: PassData,
    modules_bind_match_patterns: PassData,
    modules_type_match_payloads: PassData,
    modules_type_match_exprs: PassData,
    type_instances_clear: PassData,
    type_instances_mark_generic_param_records: PassData,
    type_instances_propagate_generic_decl_owner: PassData,
    type_instances_decl_generic_params: PassData,
    type_instances_sort_generic_param_keys: PassData,
    type_instances_sort_generic_param_keys_scatter: PassData,
    type_instances_sort_generic_param_slots: PassData,
    type_instances_sort_generic_param_slots_scatter: PassData,
    type_instances_generic_param_use_slots: PassData,
    type_instances_seed_struct_field_keys: PassData,
    type_instances_sort_struct_field_keys: PassData,
    type_instances_sort_struct_field_keys_scatter: PassData,
    type_instances_collect: PassData,
    type_instances_collect_named: PassData,
    type_instances_collect_aggregate_refs: PassData,
    type_instances_collect_aggregate_details: PassData,
    type_instances_collect_named_arg_refs: PassData,
    type_instances_hash_arg_rows: PassData,
    type_instances_decl_refs: PassData,
    type_instances_member_receivers: PassData,
    type_instances_member_results: PassData,
    type_instances_member_substitute: PassData,
    type_instances_struct_init_clear: PassData,
    type_instances_struct_init_contexts: PassData,
    type_instances_struct_init_fields: PassData,
    type_instances_struct_init_substitute: PassData,
    type_instances_array_return_refs: PassData,
    type_instances_array_literal_return_refs: PassData,
    type_instances_array_index_results: PassData,
    type_instances_validate_aggregate_access: PassData,
    predicates_clear_syntax_tokens: PassData,
    predicates_clear_bound_arg_facts: PassData,
    predicates_collect_bound_arg_facts: PassData,
    predicates_collect_method_contracts: PassData,
    predicates_collect: PassData,
    predicates_seed_key_order: PassData,
    predicates_sort_keys: PassData,
    predicates_sort_keys_scatter: PassData,
    predicates_build_method_owner_ranges: PassData,
    predicates_emit_method_validation_rows: PassData,
    predicates_reduce_method_validation_errors: PassData,
    predicates_apply_method_validation_errors: PassData,
    predicates_obligations: PassData,
    returns_clear: PassData,
    returns_mark: PassData,
    returns_mark_if: PassData,
    returns_validate: PassData,
    conditions_hir: PassData,
    conditions_aggregate_args: PassData,
    control: PassData,
    control_hir: PassData,
    scope: PassData,
    scope_hir: PassData,
    calls_clear: PassData,
    calls_return_refs: PassData,
    calls_entrypoints: PassData,
    calls_functions: PassData,
    calls_param_types: PassData,
    calls_intrinsics: PassData,
    calls_clear_hir_call_args: PassData,
    calls_pack_hir_call_args: PassData,
    calls_mark_compact_hir_call_args: PassData,
    calls_scatter_compact_hir_call_args: PassData,
    calls_scatter_compact_hir_params: PassData,
    calls_resolve: PassData,
    calls_match_arg_params_init: PassData,
    calls_match_arg_params_copy: PassData,
    calls_match_arg_params_step: PassData,
    calls_collect_row_args: PassData,
    calls_emit_generic_claims: PassData,
    calls_sort_generic_claims: PassData,
    calls_sort_generic_claims_scatter: PassData,
    calls_validate_generic_claims: PassData,
    calls_mark_required_generics: PassData,
    calls_validate_required_generics: PassData,
    calls_validate_const_claims: PassData,
    calls_apply_row_args: PassData,
    calls_infer_array_generics: PassData,
    calls_validate_array_results: PassData,
    calls_mark_array_args: PassData,
    calls_erase_generic_params: PassData,
    methods_clear: PassData,
    methods_collect: PassData,
    methods_attach_metadata: PassData,
    methods_bind_self_receivers: PassData,
    methods_seed_key_order: PassData,
    methods_sort_keys: PassData,
    methods_sort_keys_scatter: PassData,
    methods_validate_keys: PassData,
    methods_mark_call_keys: PassData,
    methods_mark_call_return_keys: PassData,
    methods_resolve_table: PassData,
    methods_resolve: PassData,
    visible_clear_resident: PassData,
    visible_mark_hir_decl_names: PassData,
    visible_scatter_hir_decl_records: PassData,
    visible_seed_hir_decl_order: PassData,
    visible_sort_hir_decl_keys: PassData,
    visible_sort_hir_decl_keys_scatter: PassData,
    visible_build_hir_decl_scope_leaves: PassData,
    visible_build_hir_decl_scope_tree: PassData,
    visible_hir_names: PassData,
    fn_context_clear: PassData,
    fn_context_mark: PassData,
    fn_context_local: PassData,
    fn_context_scan: PassData,
    fn_context_apply: PassData,
    loop_depth_clear: PassData,
    loop_depth_mark: PassData,
    loop_depth_local: PassData,
    loop_depth_scan: PassData,
    loop_depth_apply: PassData,
}

// Resident type-checking keeps buffers and bind groups in this owner so GPU
// resources stay alive across the retained pipeline even when a field is only
// consumed indirectly by a reflected bind group.
#[allow(dead_code)]
struct ResidentTypeCheckState {
    cache_key: ResidentTypeCheckCacheKey,
    name_capacity: u32,
    name_n_blocks: u32,
    loop_n_blocks: u32,
    fn_n_blocks: u32,
    name_lexeme_flag: LaniusBuffer<u32>,
    name_lexeme_kind: LaniusBuffer<u32>,
    name_lexeme_prefix: LaniusBuffer<u32>,
    name_scan_local_prefix: LaniusBuffer<u32>,
    name_scan_block_sum: LaniusBuffer<u32>,
    name_scan_prefix_a: LaniusBuffer<u32>,
    name_scan_prefix_b: LaniusBuffer<u32>,
    name_scan_total: LaniusBuffer<u32>,
    name_spans: LaniusBuffer<u32>,
    name_order_in: LaniusBuffer<u32>,
    name_order_tmp: LaniusBuffer<u32>,
    name_id_by_token: LaniusBuffer<u32>,
    language_name_id: LaniusBuffer<u32>,
    language_decl_symbol_slot: LaniusBuffer<u32>,
    language_decl_kind: LaniusBuffer<u32>,
    language_decl_tag: LaniusBuffer<u32>,
    language_decl_name_id: LaniusBuffer<u32>,
    language_type_code_by_name_id: LaniusBuffer<u32>,
    language_entrypoint_tag_by_name_id: LaniusBuffer<u32>,
    language_intrinsic_tag_by_name_id: LaniusBuffer<u32>,
    radix_block_histogram: LaniusBuffer<u32>,
    radix_block_bucket_prefix: LaniusBuffer<u32>,
    radix_bucket_total: LaniusBuffer<u32>,
    radix_bucket_base: LaniusBuffer<u32>,
    run_head_mask: LaniusBuffer<u32>,
    adjacent_equal_mask: LaniusBuffer<u32>,
    run_head_prefix: LaniusBuffer<u32>,
    sorted_name_id: LaniusBuffer<u32>,
    name_id_by_input: LaniusBuffer<u32>,
    unique_name_count: LaniusBuffer<u32>,
    module_path: Option<ModulePathState>,
    method_module_id_by_file_id_implicit_root: LaniusBuffer<u32>,
    module_type_path_type: LaniusBuffer<u32>,
    module_type_path_status: LaniusBuffer<u32>,
    module_value_path_expr_head: LaniusBuffer<u32>,
    module_value_path_call_head: LaniusBuffer<u32>,
    module_value_path_call_open: LaniusBuffer<u32>,
    module_value_path_call_path_id: LaniusBuffer<u32>,
    module_value_path_call_leaf: LaniusBuffer<u32>,
    module_value_path_associated_method_token: LaniusBuffer<u32>,
    module_value_path_associated_receiver_token: LaniusBuffer<u32>,
    module_value_path_const_head: LaniusBuffer<u32>,
    module_value_path_const_end: LaniusBuffer<u32>,
    module_value_path_status: LaniusBuffer<u32>,
    visible_decl: LaniusBuffer<u32>,
    visible_type: LaniusBuffer<u32>,
    hir_value_decl_name_present: LaniusBuffer<u32>,
    hir_visible_decl_flag: LaniusBuffer<u32>,
    hir_visible_decl_prefix: LaniusBuffer<u32>,
    hir_visible_decl_scan_local_prefix: LaniusBuffer<u32>,
    hir_visible_decl_scan_block_sum: LaniusBuffer<u32>,
    hir_visible_decl_scan_prefix_a: LaniusBuffer<u32>,
    hir_visible_decl_scan_prefix_b: LaniusBuffer<u32>,
    hir_visible_decl_count_out: LaniusBuffer<u32>,
    hir_visible_decl_owner_fn: LaniusBuffer<u32>,
    hir_visible_decl_name_id: LaniusBuffer<u32>,
    hir_visible_decl_token: LaniusBuffer<u32>,
    hir_visible_decl_scope_end: LaniusBuffer<u32>,
    hir_visible_decl_node: LaniusBuffer<u32>,
    hir_visible_decl_key_order: LaniusBuffer<u32>,
    hir_visible_decl_key_order_tmp: LaniusBuffer<u32>,
    hir_visible_decl_key_radix_dispatch_args: LaniusBuffer<u32>,
    hir_visible_decl_key_radix_block_histogram: LaniusBuffer<u32>,
    hir_visible_decl_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    hir_visible_decl_key_radix_bucket_total: LaniusBuffer<u32>,
    hir_visible_decl_key_radix_bucket_base: LaniusBuffer<u32>,
    hir_visible_decl_scope_tree: LaniusBuffer<u32>,
    generic_param_count_out: LaniusBuffer<u32>,
    generic_param_owner_node: LaniusBuffer<u32>,
    generic_param_name_id: LaniusBuffer<u32>,
    generic_param_token: LaniusBuffer<u32>,
    generic_param_node: LaniusBuffer<u32>,
    generic_param_kind: LaniusBuffer<u32>,
    generic_param_key_order: LaniusBuffer<u32>,
    generic_param_key_order_tmp: LaniusBuffer<u32>,
    generic_param_slot_order: LaniusBuffer<u32>,
    generic_param_slot_order_tmp: LaniusBuffer<u32>,
    generic_decl_owner_by_node_a: LaniusBuffer<u32>,
    generic_decl_owner_by_node_b: LaniusBuffer<u32>,
    generic_decl_parent_jump_a: LaniusBuffer<u32>,
    generic_decl_parent_jump_b: LaniusBuffer<u32>,
    token_active_dispatch_args: LaniusBuffer<u32>,
    hir_active_dispatch_args: LaniusBuffer<u32>,
    token_hir_active_dispatch_args: LaniusBuffer<u32>,
    hir_active_count: LaniusBuffer<u32>,
    hir_active_dispatch: wgpu::BindGroup,
    loop_delta: LaniusBuffer<i32>,
    loop_depth_inblock: LaniusBuffer<i32>,
    loop_block_sum: LaniusBuffer<i32>,
    loop_prefix_a: LaniusBuffer<i32>,
    loop_prefix_b: LaniusBuffer<i32>,
    loop_block_prefix: LaniusBuffer<i32>,
    loop_depth: LaniusBuffer<i32>,
    enclosing_fn: LaniusBuffer<u32>,
    enclosing_fn_end: LaniusBuffer<u32>,
    fn_event_value: LaniusBuffer<u32>,
    fn_event_end: LaniusBuffer<u32>,
    fn_event_index: LaniusBuffer<u32>,
    fn_event_inblock: LaniusBuffer<u32>,
    fn_block_sum: LaniusBuffer<u32>,
    fn_prefix_a: LaniusBuffer<u32>,
    fn_prefix_b: LaniusBuffer<u32>,
    fn_block_prefix: LaniusBuffer<u32>,
    call_fn_index: LaniusBuffer<u32>,
    call_intrinsic_tag: LaniusBuffer<u32>,
    fn_entrypoint_tag: LaniusBuffer<u32>,
    call_return_type: LaniusBuffer<u32>,
    call_return_type_token: LaniusBuffer<u32>,
    return_fn_flags: LaniusBuffer<u32>,
    return_block_flags: LaniusBuffer<u32>,
    call_param_count: LaniusBuffer<u32>,
    call_param_type: LaniusBuffer<u32>,
    call_param_ref_tag: LaniusBuffer<u32>,
    call_param_ref_payload: LaniusBuffer<u32>,
    call_generic_slot_type: LaniusBuffer<u32>,
    call_generic_slot_ordinal: LaniusBuffer<u32>,
    call_const_slot_len: LaniusBuffer<u32>,
    call_param_row_count_out: LaniusBuffer<u32>,
    call_param_row_flag: LaniusBuffer<u32>,
    call_param_row_node_type: LaniusBuffer<u32>,
    call_param_row_node_ref_tag: LaniusBuffer<u32>,
    call_param_row_node_ref_payload: LaniusBuffer<u32>,
    call_param_row_node: LaniusBuffer<u32>,
    call_param_row_fn_token: LaniusBuffer<u32>,
    call_param_row_ordinal: LaniusBuffer<u32>,
    call_param_row_type: LaniusBuffer<u32>,
    call_param_row_ref_tag: LaniusBuffer<u32>,
    call_param_row_ref_payload: LaniusBuffer<u32>,
    call_param_row_start: LaniusBuffer<u32>,
    call_param_row_count: LaniusBuffer<u32>,
    call_param_row_scan_local_prefix: LaniusBuffer<u32>,
    call_param_row_scan_block_sum: LaniusBuffer<u32>,
    call_param_row_scan_prefix_a: LaniusBuffer<u32>,
    call_param_row_scan_prefix_b: LaniusBuffer<u32>,
    call_arg_record: LaniusBuffer<u32>,
    call_arg_row_count_out: LaniusBuffer<u32>,
    call_arg_row_scan_input: LaniusBuffer<u32>,
    call_arg_row_prefix: LaniusBuffer<u32>,
    call_arg_row_node: LaniusBuffer<u32>,
    call_arg_row_call_node: LaniusBuffer<u32>,
    call_arg_row_ordinal: LaniusBuffer<u32>,
    call_arg_row_start: LaniusBuffer<u32>,
    call_arg_row_count: LaniusBuffer<u32>,
    call_arg_param_row: LaniusBuffer<u32>,
    call_arg_param_row_tmp: LaniusBuffer<u32>,
    call_arg_match_jump_a: LaniusBuffer<u32>,
    call_arg_match_jump_b: LaniusBuffer<u32>,
    call_param_match_jump_a: LaniusBuffer<u32>,
    call_param_match_jump_b: LaniusBuffer<u32>,
    call_generic_claim_count_out: LaniusBuffer<u32>,
    call_generic_claim_scan_input: LaniusBuffer<u32>,
    call_generic_claim_prefix: LaniusBuffer<u32>,
    call_generic_claim_callee: LaniusBuffer<u32>,
    call_generic_claim_slot: LaniusBuffer<u32>,
    call_generic_claim_type: LaniusBuffer<u32>,
    call_generic_claim_arg_row: LaniusBuffer<u32>,
    call_generic_claim_order: LaniusBuffer<u32>,
    call_generic_claim_order_tmp: LaniusBuffer<u32>,
    call_generic_claim_radix_dispatch_args: LaniusBuffer<u32>,
    call_generic_claim_radix_block_histogram: LaniusBuffer<u32>,
    call_generic_claim_radix_block_bucket_prefix: LaniusBuffer<u32>,
    call_generic_claim_radix_bucket_total: LaniusBuffer<u32>,
    call_generic_claim_radix_bucket_base: LaniusBuffer<u32>,
    call_const_claim_callee: LaniusBuffer<u32>,
    call_const_claim_slot: LaniusBuffer<u32>,
    call_const_claim_len: LaniusBuffer<u32>,
    call_const_claim_order: LaniusBuffer<u32>,
    call_const_claim_order_tmp: LaniusBuffer<u32>,
    call_const_claim_radix_dispatch_args: LaniusBuffer<u32>,
    call_const_claim_radix_block_histogram: LaniusBuffer<u32>,
    call_const_claim_radix_block_bucket_prefix: LaniusBuffer<u32>,
    call_const_claim_radix_bucket_total: LaniusBuffer<u32>,
    call_const_claim_radix_bucket_base: LaniusBuffer<u32>,
    call_required_generic_count_out: LaniusBuffer<u32>,
    call_required_generic_scan_input: LaniusBuffer<u32>,
    call_required_generic_prefix: LaniusBuffer<u32>,
    call_required_generic_scan_local_prefix: LaniusBuffer<u32>,
    call_required_generic_scan_block_sum: LaniusBuffer<u32>,
    call_required_generic_scan_prefix_a: LaniusBuffer<u32>,
    call_required_generic_scan_prefix_b: LaniusBuffer<u32>,
    call_required_generic_dispatch_args: LaniusBuffer<u32>,
    call_has_array_arg: LaniusBuffer<u32>,
    call_array_return_arg_instance: LaniusBuffer<u32>,
    call_arg_row_scan_local_prefix: LaniusBuffer<u32>,
    call_arg_row_scan_block_sum: LaniusBuffer<u32>,
    call_arg_row_scan_prefix_a: LaniusBuffer<u32>,
    call_arg_row_scan_prefix_b: LaniusBuffer<u32>,
    call_generic_claim_scan_local_prefix: LaniusBuffer<u32>,
    call_generic_claim_scan_block_sum: LaniusBuffer<u32>,
    call_generic_claim_scan_prefix_a: LaniusBuffer<u32>,
    call_generic_claim_scan_prefix_b: LaniusBuffer<u32>,
    function_lookup_key: LaniusBuffer<u32>,
    function_lookup_fn: LaniusBuffer<u32>,
    method_decl_receiver_ref_tag: LaniusBuffer<u32>,
    method_decl_receiver_ref_payload: LaniusBuffer<u32>,
    method_decl_module_id: LaniusBuffer<u32>,
    method_decl_impl_node: LaniusBuffer<u32>,
    method_decl_name_token: LaniusBuffer<u32>,
    method_decl_name_id: LaniusBuffer<u32>,
    method_decl_param_offset: LaniusBuffer<u32>,
    method_decl_receiver_mode: LaniusBuffer<u32>,
    method_decl_visibility: LaniusBuffer<u32>,
    method_module_count_out_implicit_root: LaniusBuffer<u32>,
    method_key_to_fn_token: LaniusBuffer<u32>,
    method_key_order_tmp: LaniusBuffer<u32>,
    method_key_status: LaniusBuffer<u32>,
    method_key_duplicate_of: LaniusBuffer<u32>,
    method_key_radix_block_histogram: LaniusBuffer<u32>,
    method_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    method_key_radix_bucket_total: LaniusBuffer<u32>,
    method_key_radix_bucket_base: LaniusBuffer<u32>,
    struct_field_key_order: LaniusBuffer<u32>,
    struct_field_key_order_tmp: LaniusBuffer<u32>,
    struct_field_key_radix_dispatch_args: LaniusBuffer<u32>,
    struct_field_key_radix_block_histogram: LaniusBuffer<u32>,
    struct_field_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    struct_field_key_radix_bucket_total: LaniusBuffer<u32>,
    struct_field_key_radix_bucket_base: LaniusBuffer<u32>,
    method_call_receiver_ref_tag: LaniusBuffer<u32>,
    method_call_receiver_ref_payload: LaniusBuffer<u32>,
    method_call_name_id: LaniusBuffer<u32>,
    method_call_site_module_id: LaniusBuffer<u32>,
    type_expr_ref_tag: LaniusBuffer<u32>,
    type_expr_ref_payload: LaniusBuffer<u32>,
    type_instance_kind: LaniusBuffer<u32>,
    type_instance_head_token: LaniusBuffer<u32>,
    type_decl_generic_param_count: LaniusBuffer<u32>,
    type_decl_generic_param_count_by_node: LaniusBuffer<u32>,
    type_decl_const_param_count_by_node: LaniusBuffer<u32>,
    type_decl_hir_node_by_token: LaniusBuffer<u32>,
    type_generic_param_slot_by_token: LaniusBuffer<u32>,
    type_const_param_slot_by_token: LaniusBuffer<u32>,
    type_instance_decl_token: LaniusBuffer<u32>,
    type_instance_arg_start: LaniusBuffer<u32>,
    type_instance_arg_count: LaniusBuffer<u32>,
    type_instance_arg_ref_tag: LaniusBuffer<u32>,
    type_instance_arg_ref_payload: LaniusBuffer<u32>,
    type_instance_arg_hash: LaniusBuffer<u32>,
    type_instance_arg_row_start: LaniusBuffer<u32>,
    type_instance_arg_row_count_out: LaniusBuffer<u32>,
    type_instance_arg_row_ref_tag: LaniusBuffer<u32>,
    type_instance_arg_row_ref_payload: LaniusBuffer<u32>,
    type_instance_arg_row_scan_local_prefix: LaniusBuffer<u32>,
    type_instance_arg_row_scan_block_sum: LaniusBuffer<u32>,
    type_instance_arg_row_scan_prefix_a: LaniusBuffer<u32>,
    type_instance_arg_row_scan_prefix_b: LaniusBuffer<u32>,
    aggregate_compare_scan_input: LaniusBuffer<u32>,
    aggregate_compare_prefix: LaniusBuffer<u32>,
    aggregate_compare_count_out: LaniusBuffer<u32>,
    aggregate_compare_expected_instance: LaniusBuffer<u32>,
    aggregate_compare_actual_instance: LaniusBuffer<u32>,
    aggregate_compare_error_token: LaniusBuffer<u32>,
    aggregate_compare_error_detail: LaniusBuffer<u32>,
    aggregate_compare_scan_local_prefix: LaniusBuffer<u32>,
    aggregate_compare_scan_block_sum: LaniusBuffer<u32>,
    aggregate_compare_scan_prefix_a: LaniusBuffer<u32>,
    aggregate_compare_scan_prefix_b: LaniusBuffer<u32>,
    aggregate_compare_dispatch_args: LaniusBuffer<u32>,
    aggregate_compare_dispatch_params: LaniusBuffer<CountDispatchParams>,
    type_instance_elem_ref_tag: LaniusBuffer<u32>,
    type_instance_elem_ref_payload: LaniusBuffer<u32>,
    type_instance_len_kind: LaniusBuffer<u32>,
    type_instance_len_payload: LaniusBuffer<u32>,
    type_instance_state: LaniusBuffer<u32>,
    predicate_owner_node: LaniusBuffer<u32>,
    predicate_subject_token: LaniusBuffer<u32>,
    predicate_bound_token: LaniusBuffer<u32>,
    predicate_bound_decl_id: LaniusBuffer<u32>,
    predicate_bound_arg_count: LaniusBuffer<u32>,
    predicate_bound_first_arg_token: LaniusBuffer<u32>,
    predicate_bound_second_arg_token: LaniusBuffer<u32>,
    predicate_status: LaniusBuffer<u32>,
    predicate_syntax_token: LaniusBuffer<u32>,
    predicate_method_contract_owner_node: LaniusBuffer<u32>,
    predicate_method_contract_name_token: LaniusBuffer<u32>,
    predicate_method_contract_name_id: LaniusBuffer<u32>,
    predicate_method_contract_param_count: LaniusBuffer<u32>,
    predicate_method_contract_first_param_node: LaniusBuffer<u32>,
    predicate_method_contract_return_type_node: LaniusBuffer<u32>,
    predicate_method_contract_visibility: LaniusBuffer<u32>,
    predicate_method_contract_status: LaniusBuffer<u32>,
    predicate_method_contract_param_next_node: LaniusBuffer<u32>,
    predicate_method_contract_param_type_node: LaniusBuffer<u32>,
    predicate_method_contract_key_order: LaniusBuffer<u32>,
    predicate_method_contract_key_order_tmp: LaniusBuffer<u32>,
    predicate_method_param_key_order: LaniusBuffer<u32>,
    predicate_method_param_key_order_tmp: LaniusBuffer<u32>,
    predicate_method_contract_owner_range_first: LaniusBuffer<u32>,
    predicate_method_contract_owner_range_count: LaniusBuffer<u32>,
    predicate_method_validation_owner_node: LaniusBuffer<u32>,
    predicate_method_validation_peer_node: LaniusBuffer<u32>,
    predicate_method_validation_status: LaniusBuffer<u32>,
    predicate_method_validation_detail_token: LaniusBuffer<u32>,
    predicate_method_validation_first_error_row: LaniusBuffer<u32>,
    predicate_owner_key_order: LaniusBuffer<u32>,
    predicate_owner_key_order_tmp: LaniusBuffer<u32>,
    predicate_impl_key_order: LaniusBuffer<u32>,
    predicate_impl_key_order_tmp: LaniusBuffer<u32>,
    predicate_key_radix_block_histogram: LaniusBuffer<u32>,
    predicate_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    predicate_key_radix_bucket_total: LaniusBuffer<u32>,
    predicate_key_radix_bucket_base: LaniusBuffer<u32>,
    predicate_obligation_count_by_call: LaniusBuffer<u32>,
    predicate_obligation_prefix_by_call: LaniusBuffer<u32>,
    predicate_obligation_scan_local_prefix: LaniusBuffer<u32>,
    predicate_obligation_scan_block_sum: LaniusBuffer<u32>,
    predicate_obligation_scan_prefix_a: LaniusBuffer<u32>,
    predicate_obligation_scan_prefix_b: LaniusBuffer<u32>,
    predicate_obligation_pair_total: LaniusBuffer<u32>,
    predicate_obligation_pair_dispatch_args: LaniusBuffer<u32>,
    fn_return_ref_tag: LaniusBuffer<u32>,
    fn_return_ref_payload: LaniusBuffer<u32>,
    decl_type_ref_tag: LaniusBuffer<u32>,
    decl_type_ref_payload: LaniusBuffer<u32>,
    member_result_context_instance: LaniusBuffer<u32>,
    member_result_ref_tag: LaniusBuffer<u32>,
    member_result_ref_payload: LaniusBuffer<u32>,
    member_result_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_expected_ref_tag: LaniusBuffer<u32>,
    struct_init_field_expected_ref_payload: LaniusBuffer<u32>,
    struct_init_field_context_instance: LaniusBuffer<u32>,
    struct_init_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_ordinal_by_node: LaniusBuffer<u32>,
    struct_lit_context_decl_token: LaniusBuffer<u32>,
    struct_lit_context_instance: LaniusBuffer<u32>,
    name_scan_steps: Vec<NameScanStep>,
    name_bind_groups: NameBindGroups,
    language_name_bind_groups: LanguageNameBindGroups,
    loop_params: LaniusBuffer<LoopDepthParams>,
    loop_scan_steps: Vec<LoopDepthScanStep>,
    fn_params: LaniusBuffer<FnContextParams>,
    fn_scan_steps: Vec<FnContextScanStep>,
    loop_bind_groups: LoopDepthBindGroups,
    fn_context_bind_groups: FnContextBindGroups,
    visible_bind_groups: VisibleBindGroups,
    calls: CallBindGroups,
    methods: MethodBindGroups,
    predicates: Option<PredicateBindGroups>,
    type_instances: TypeInstanceBindGroups,
    returns_clear: wgpu::BindGroup,
    returns_mark: wgpu::BindGroup,
    returns_mark_if: wgpu::BindGroup,
    returns_validate: wgpu::BindGroup,
    conditions_hir: wgpu::BindGroup,
    aggregate_compare_scan: U32ScanBindGroups,
    aggregate_compare_scan_n_blocks: u32,
    aggregate_compare_dispatch: wgpu::BindGroup,
    conditions_aggregate_args: wgpu::BindGroup,
    control: wgpu::BindGroup,
    scope: wgpu::BindGroup,
    scope_hir: wgpu::BindGroup,
}

impl ResidentTypeCheckState {
    fn can_reuse_for(&self, key: ResidentTypeCheckCacheKey) -> bool {
        self.cache_key.source_file_capacity == key.source_file_capacity
            && self.cache_key.token_capacity >= key.token_capacity
            && self.cache_key.hir_node_capacity >= key.hir_node_capacity
            && self.cache_key.parser_hir_node_capacity >= key.parser_hir_node_capacity
            && self.cache_key.input_fingerprint == key.input_fingerprint
            && self.cache_key.uses_hir_control == key.uses_hir_control
            && self.cache_key.uses_hir_items == key.uses_hir_items
    }
}

/// Borrowed semantic metadata produced by type checking for backend consumers.
///
/// Backends should use this view rather than reaching into resident type-check
/// state directly. The fields are borrowed from retained buffers whose lifetime
/// is owned by `OwnedGpuCodegenBuffers`.
pub struct GpuCodegenBuffers<'a> {
    pub name_id_by_token: &'a wgpu::Buffer,
    pub enclosing_fn: &'a wgpu::Buffer,
    pub visible_decl: &'a wgpu::Buffer,
    pub visible_type: &'a wgpu::Buffer,
    pub path_count_out: &'a wgpu::Buffer,
    pub path_owner_token: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub decl_count_out: &'a wgpu::Buffer,
    pub decl_kind: &'a wgpu::Buffer,
    pub decl_name_token: &'a wgpu::Buffer,
    pub decl_id_by_name_token: &'a wgpu::Buffer,
    pub decl_hir_node: &'a wgpu::Buffer,
    pub decl_parent_type_decl: &'a wgpu::Buffer,
    pub decl_type_ref_tag: &'a wgpu::Buffer,
    pub decl_type_ref_payload: &'a wgpu::Buffer,
    pub type_expr_ref_tag: &'a wgpu::Buffer,
    pub type_expr_ref_payload: &'a wgpu::Buffer,
    pub module_value_path_call_head: &'a wgpu::Buffer,
    pub module_value_path_call_open: &'a wgpu::Buffer,
    pub module_value_path_const_head: &'a wgpu::Buffer,
    pub module_value_path_const_end: &'a wgpu::Buffer,
    pub call_fn_index: &'a wgpu::Buffer,
    pub call_intrinsic_tag: &'a wgpu::Buffer,
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub call_return_type: &'a wgpu::Buffer,
    pub call_return_type_token: &'a wgpu::Buffer,
    pub call_param_count: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub method_decl_module_id: &'a wgpu::Buffer,
    pub method_decl_name_token: &'a wgpu::Buffer,
    pub method_decl_name_id: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub method_decl_receiver_mode: &'a wgpu::Buffer,
    pub method_decl_visibility: &'a wgpu::Buffer,
    pub method_key_to_fn_token: &'a wgpu::Buffer,
    pub method_key_status: &'a wgpu::Buffer,
    pub method_call_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_call_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_call_name_id: &'a wgpu::Buffer,
    pub method_call_site_module_id: &'a wgpu::Buffer,
    pub type_instance_kind: &'a wgpu::Buffer,
    pub type_instance_decl_token: &'a wgpu::Buffer,
    pub type_instance_arg_start: &'a wgpu::Buffer,
    pub type_instance_arg_count: &'a wgpu::Buffer,
    pub type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub type_instance_arg_hash: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub fn_return_ref_tag: &'a wgpu::Buffer,
    pub fn_return_ref_payload: &'a wgpu::Buffer,
    pub member_result_ref_tag: &'a wgpu::Buffer,
    pub member_result_ref_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_tag: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_payload: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal_by_node: &'a wgpu::Buffer,
}

/// Owned copy of generic backend semantic metadata produced by type checking.
///
/// This wrapper is the lifetime boundary between the type-check resident cache
/// and later backend recording.
pub struct OwnedGpuCodegenBuffers {
    name_id_by_token: LaniusBuffer<u32>,
    enclosing_fn: LaniusBuffer<u32>,
    visible_decl: LaniusBuffer<u32>,
    visible_type: LaniusBuffer<u32>,
    path_count_out: LaniusBuffer<u32>,
    path_owner_token: LaniusBuffer<u32>,
    path_id_by_owner_hir: LaniusBuffer<u32>,
    resolved_value_decl: LaniusBuffer<u32>,
    resolved_value_status: LaniusBuffer<u32>,
    decl_count_out: LaniusBuffer<u32>,
    decl_kind: LaniusBuffer<u32>,
    decl_name_token: LaniusBuffer<u32>,
    decl_id_by_name_token: LaniusBuffer<u32>,
    decl_hir_node: LaniusBuffer<u32>,
    decl_parent_type_decl: LaniusBuffer<u32>,
    decl_type_ref_tag: LaniusBuffer<u32>,
    decl_type_ref_payload: LaniusBuffer<u32>,
    type_expr_ref_tag: LaniusBuffer<u32>,
    type_expr_ref_payload: LaniusBuffer<u32>,
    module_value_path_call_head: LaniusBuffer<u32>,
    module_value_path_call_open: LaniusBuffer<u32>,
    module_value_path_const_head: LaniusBuffer<u32>,
    module_value_path_const_end: LaniusBuffer<u32>,
    call_fn_index: LaniusBuffer<u32>,
    call_intrinsic_tag: LaniusBuffer<u32>,
    fn_entrypoint_tag: LaniusBuffer<u32>,
    call_return_type: LaniusBuffer<u32>,
    call_return_type_token: LaniusBuffer<u32>,
    call_param_count: LaniusBuffer<u32>,
    call_param_type: LaniusBuffer<u32>,
    method_decl_module_id: LaniusBuffer<u32>,
    method_decl_name_token: LaniusBuffer<u32>,
    method_decl_name_id: LaniusBuffer<u32>,
    method_decl_receiver_ref_tag: LaniusBuffer<u32>,
    method_decl_receiver_ref_payload: LaniusBuffer<u32>,
    method_decl_param_offset: LaniusBuffer<u32>,
    method_decl_receiver_mode: LaniusBuffer<u32>,
    method_decl_visibility: LaniusBuffer<u32>,
    method_key_to_fn_token: LaniusBuffer<u32>,
    method_key_status: LaniusBuffer<u32>,
    method_call_receiver_ref_tag: LaniusBuffer<u32>,
    method_call_receiver_ref_payload: LaniusBuffer<u32>,
    method_call_name_id: LaniusBuffer<u32>,
    method_call_site_module_id: LaniusBuffer<u32>,
    type_instance_kind: LaniusBuffer<u32>,
    type_instance_decl_token: LaniusBuffer<u32>,
    type_instance_arg_start: LaniusBuffer<u32>,
    type_instance_arg_count: LaniusBuffer<u32>,
    type_instance_arg_ref_tag: LaniusBuffer<u32>,
    type_instance_arg_ref_payload: LaniusBuffer<u32>,
    type_instance_arg_hash: LaniusBuffer<u32>,
    type_instance_len_kind: LaniusBuffer<u32>,
    type_instance_len_payload: LaniusBuffer<u32>,
    fn_return_ref_tag: LaniusBuffer<u32>,
    fn_return_ref_payload: LaniusBuffer<u32>,
    member_result_ref_tag: LaniusBuffer<u32>,
    member_result_ref_payload: LaniusBuffer<u32>,
    member_result_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_expected_ref_tag: LaniusBuffer<u32>,
    struct_init_field_expected_ref_payload: LaniusBuffer<u32>,
    struct_init_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_ordinal_by_node: LaniusBuffer<u32>,
}

/// Borrowed x86-specific semantic metadata produced by type checking.
///
/// This is a narrowed view of the type-check outputs needed by the current x86
/// backend.
#[derive(Clone, Copy)]
pub struct GpuX86CodegenBuffers<'a> {
    pub enclosing_fn: &'a wgpu::Buffer,
    pub visible_decl: &'a wgpu::Buffer,
    pub visible_type: &'a wgpu::Buffer,
    pub path_count_out: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub decl_count_out: &'a wgpu::Buffer,
    pub decl_kind: &'a wgpu::Buffer,
    pub decl_name_token: &'a wgpu::Buffer,
    pub decl_id_by_name_token: &'a wgpu::Buffer,
    pub decl_hir_node: &'a wgpu::Buffer,
    pub decl_parent_type_decl: &'a wgpu::Buffer,
    pub decl_type_ref_tag: &'a wgpu::Buffer,
    pub decl_type_ref_payload: &'a wgpu::Buffer,
    pub call_fn_index: &'a wgpu::Buffer,
    pub call_intrinsic_tag: &'a wgpu::Buffer,
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub call_return_type: &'a wgpu::Buffer,
    pub call_return_type_token: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub call_arg_row_node: &'a wgpu::Buffer,
    pub call_arg_row_start: &'a wgpu::Buffer,
    pub call_arg_row_count: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub type_instance_kind: &'a wgpu::Buffer,
    pub type_instance_decl_token: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal_by_node: &'a wgpu::Buffer,
}

/// Owned copy of x86 backend semantic metadata produced by type checking.
pub struct OwnedGpuX86CodegenBuffers {
    enclosing_fn: LaniusBuffer<u32>,
    visible_decl: LaniusBuffer<u32>,
    visible_type: LaniusBuffer<u32>,
    path_count_out: LaniusBuffer<u32>,
    path_id_by_owner_hir: LaniusBuffer<u32>,
    resolved_value_decl: LaniusBuffer<u32>,
    resolved_value_status: LaniusBuffer<u32>,
    decl_count_out: LaniusBuffer<u32>,
    decl_kind: LaniusBuffer<u32>,
    decl_name_token: LaniusBuffer<u32>,
    decl_id_by_name_token: LaniusBuffer<u32>,
    decl_hir_node: LaniusBuffer<u32>,
    decl_parent_type_decl: LaniusBuffer<u32>,
    decl_type_ref_tag: LaniusBuffer<u32>,
    decl_type_ref_payload: LaniusBuffer<u32>,
    call_fn_index: LaniusBuffer<u32>,
    call_intrinsic_tag: LaniusBuffer<u32>,
    fn_entrypoint_tag: LaniusBuffer<u32>,
    call_return_type: LaniusBuffer<u32>,
    call_return_type_token: LaniusBuffer<u32>,
    call_param_type: LaniusBuffer<u32>,
    call_arg_row_node: LaniusBuffer<u32>,
    call_arg_row_start: LaniusBuffer<u32>,
    call_arg_row_count: LaniusBuffer<u32>,
    method_decl_receiver_ref_tag: LaniusBuffer<u32>,
    method_decl_receiver_ref_payload: LaniusBuffer<u32>,
    method_decl_param_offset: LaniusBuffer<u32>,
    type_instance_kind: LaniusBuffer<u32>,
    type_instance_decl_token: LaniusBuffer<u32>,
    type_instance_len_kind: LaniusBuffer<u32>,
    type_instance_len_payload: LaniusBuffer<u32>,
    member_result_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_ordinal: LaniusBuffer<u32>,
    struct_init_field_ordinal_by_node: LaniusBuffer<u32>,
}

impl OwnedGpuX86CodegenBuffers {
    /// Borrows the owned x86 metadata as the backend-facing view.
    pub fn as_ref(&self) -> GpuX86CodegenBuffers<'_> {
        GpuX86CodegenBuffers {
            enclosing_fn: &self.enclosing_fn,
            visible_decl: &self.visible_decl,
            visible_type: &self.visible_type,
            path_count_out: &self.path_count_out,
            path_id_by_owner_hir: &self.path_id_by_owner_hir,
            resolved_value_decl: &self.resolved_value_decl,
            resolved_value_status: &self.resolved_value_status,
            decl_count_out: &self.decl_count_out,
            decl_kind: &self.decl_kind,
            decl_name_token: &self.decl_name_token,
            decl_id_by_name_token: &self.decl_id_by_name_token,
            decl_hir_node: &self.decl_hir_node,
            decl_parent_type_decl: &self.decl_parent_type_decl,
            decl_type_ref_tag: &self.decl_type_ref_tag,
            decl_type_ref_payload: &self.decl_type_ref_payload,
            call_fn_index: &self.call_fn_index,
            call_intrinsic_tag: &self.call_intrinsic_tag,
            fn_entrypoint_tag: &self.fn_entrypoint_tag,
            call_return_type: &self.call_return_type,
            call_return_type_token: &self.call_return_type_token,
            call_param_type: &self.call_param_type,
            call_arg_row_node: &self.call_arg_row_node,
            call_arg_row_start: &self.call_arg_row_start,
            call_arg_row_count: &self.call_arg_row_count,
            method_decl_receiver_ref_tag: &self.method_decl_receiver_ref_tag,
            method_decl_receiver_ref_payload: &self.method_decl_receiver_ref_payload,
            method_decl_param_offset: &self.method_decl_param_offset,
            type_instance_kind: &self.type_instance_kind,
            type_instance_decl_token: &self.type_instance_decl_token,
            type_instance_len_kind: &self.type_instance_len_kind,
            type_instance_len_payload: &self.type_instance_len_payload,
            member_result_field_ordinal: &self.member_result_field_ordinal,
            struct_init_field_ordinal: &self.struct_init_field_ordinal,
            struct_init_field_ordinal_by_node: &self.struct_init_field_ordinal_by_node,
        }
    }
}

impl OwnedGpuCodegenBuffers {
    /// Borrows the owned metadata as the full backend-facing view.
    pub fn as_ref(&self) -> GpuCodegenBuffers<'_> {
        GpuCodegenBuffers {
            name_id_by_token: &self.name_id_by_token,
            enclosing_fn: &self.enclosing_fn,
            visible_decl: &self.visible_decl,
            visible_type: &self.visible_type,
            path_count_out: &self.path_count_out,
            path_owner_token: &self.path_owner_token,
            path_id_by_owner_hir: &self.path_id_by_owner_hir,
            resolved_value_decl: &self.resolved_value_decl,
            resolved_value_status: &self.resolved_value_status,
            decl_count_out: &self.decl_count_out,
            decl_kind: &self.decl_kind,
            decl_name_token: &self.decl_name_token,
            decl_id_by_name_token: &self.decl_id_by_name_token,
            decl_hir_node: &self.decl_hir_node,
            decl_parent_type_decl: &self.decl_parent_type_decl,
            decl_type_ref_tag: &self.decl_type_ref_tag,
            decl_type_ref_payload: &self.decl_type_ref_payload,
            type_expr_ref_tag: &self.type_expr_ref_tag,
            type_expr_ref_payload: &self.type_expr_ref_payload,
            module_value_path_call_head: &self.module_value_path_call_head,
            module_value_path_call_open: &self.module_value_path_call_open,
            module_value_path_const_head: &self.module_value_path_const_head,
            module_value_path_const_end: &self.module_value_path_const_end,
            call_fn_index: &self.call_fn_index,
            call_intrinsic_tag: &self.call_intrinsic_tag,
            fn_entrypoint_tag: &self.fn_entrypoint_tag,
            call_return_type: &self.call_return_type,
            call_return_type_token: &self.call_return_type_token,
            call_param_count: &self.call_param_count,
            call_param_type: &self.call_param_type,
            method_decl_module_id: &self.method_decl_module_id,
            method_decl_name_token: &self.method_decl_name_token,
            method_decl_name_id: &self.method_decl_name_id,
            method_decl_receiver_ref_tag: &self.method_decl_receiver_ref_tag,
            method_decl_receiver_ref_payload: &self.method_decl_receiver_ref_payload,
            method_decl_param_offset: &self.method_decl_param_offset,
            method_decl_receiver_mode: &self.method_decl_receiver_mode,
            method_decl_visibility: &self.method_decl_visibility,
            method_key_to_fn_token: &self.method_key_to_fn_token,
            method_key_status: &self.method_key_status,
            method_call_receiver_ref_tag: &self.method_call_receiver_ref_tag,
            method_call_receiver_ref_payload: &self.method_call_receiver_ref_payload,
            method_call_name_id: &self.method_call_name_id,
            method_call_site_module_id: &self.method_call_site_module_id,
            type_instance_kind: &self.type_instance_kind,
            type_instance_decl_token: &self.type_instance_decl_token,
            type_instance_arg_start: &self.type_instance_arg_start,
            type_instance_arg_count: &self.type_instance_arg_count,
            type_instance_arg_ref_tag: &self.type_instance_arg_ref_tag,
            type_instance_arg_ref_payload: &self.type_instance_arg_ref_payload,
            type_instance_arg_hash: &self.type_instance_arg_hash,
            type_instance_len_kind: &self.type_instance_len_kind,
            type_instance_len_payload: &self.type_instance_len_payload,
            fn_return_ref_tag: &self.fn_return_ref_tag,
            fn_return_ref_payload: &self.fn_return_ref_payload,
            member_result_ref_tag: &self.member_result_ref_tag,
            member_result_ref_payload: &self.member_result_ref_payload,
            member_result_field_ordinal: &self.member_result_field_ordinal,
            struct_init_field_expected_ref_tag: &self.struct_init_field_expected_ref_tag,
            struct_init_field_expected_ref_payload: &self.struct_init_field_expected_ref_payload,
            struct_init_field_ordinal: &self.struct_init_field_ordinal,
            struct_init_field_ordinal_by_node: &self.struct_init_field_ordinal_by_node,
        }
    }
}
