import Lanius.Extraction.VerifiedFrontend.Surface.Symbol.View
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0

kernel_surface_reconstruction verifiedFrontendSymbol_reconstructed_present_kernel,
  verifiedFrontendSymbolReconstructedKernel, verifiedFrontendSymbol_reconstructed_found_kernel,
  verifiedFrontendSymbol_validated_nodes_kernel for
  verifiedFrontendSymbolArtifact, verifiedFrontendSymbolView, verifiedFrontendSymbolParseView

end Lanius.Extraction
