use std::{
    collections::HashMap,
    hash::{Hash, Hasher},
    sync::Mutex,
};

mod bind_groups;
mod bind_models;
mod bind_support;
mod module_path;
mod params;
mod pass_loaders;
mod record;
mod resident;
mod standalone;
mod util;

use anyhow::Result;
use bind_models::*;
use bind_support::*;
use module_path::*;
use params::*;
use pass_loaders::*;
use record::*;
pub use standalone::{
    check_token_buffer_on_gpu,
    check_token_buffer_with_hir_on_gpu,
    check_tokens_on_gpu,
};
use util::*;
use wgpu::util::DeviceExt;

use crate::{
    gpu::{
        buffers::{LaniusBuffer, storage_ro_from_bytes, storage_ro_from_u32s, uniform_from_val},
        device,
        passes_core::{DispatchDim, InputElements, PassData, bind_group, plan_workgroups},
    },
    lexer::types::Token,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuTypeCheckCode {
    UnknownType,
    UnresolvedIdent,
    AssignMismatch,
    ReturnMismatch,
    ConditionType,
    BadHir,
    LoopControl,
    InvalidMemberAccess,
    InvalidArrayReturn,
    CallMismatch,
    NameLimit,
    Unknown(u32),
}

impl GpuTypeCheckCode {
    fn from_u32(value: u32) -> Self {
        match value {
            1 => Self::UnknownType,
            2 => Self::UnresolvedIdent,
            3 => Self::AssignMismatch,
            4 => Self::ReturnMismatch,
            5 => Self::ConditionType,
            6 => Self::BadHir,
            7 => Self::LoopControl,
            8 => Self::InvalidMemberAccess,
            9 => Self::InvalidArrayReturn,
            10 => Self::CallMismatch,
            11 => Self::NameLimit,
            other => Self::Unknown(other),
        }
    }
}

#[derive(Debug)]
pub enum GpuTypeCheckError {
    Rejected {
        token: u32,
        code: GpuTypeCheckCode,
        detail: u32,
    },
    Gpu(anyhow::Error),
}

#[derive(Clone, Copy)]
pub struct GpuTypeCheckHirItemBuffers<'a> {
    pub node_kind: &'a wgpu::Buffer,
    pub parent: &'a wgpu::Buffer,
    pub first_child: &'a wgpu::Buffer,
    pub next_sibling: &'a wgpu::Buffer,
    pub subtree_end: &'a wgpu::Buffer,
    pub kind: &'a wgpu::Buffer,
    pub name_token: &'a wgpu::Buffer,
    pub type_form: &'a wgpu::Buffer,
    pub type_value_node: &'a wgpu::Buffer,
    pub type_len_token: &'a wgpu::Buffer,
    pub type_len_value: &'a wgpu::Buffer,
    pub type_path_leaf_node: &'a wgpu::Buffer,
    pub type_arg_start: &'a wgpu::Buffer,
    pub type_arg_count: &'a wgpu::Buffer,
    pub type_arg_next: &'a wgpu::Buffer,
    pub type_alias_target_node: &'a wgpu::Buffer,
    pub fn_return_type_node: &'a wgpu::Buffer,
    pub param_record: &'a wgpu::Buffer,
    pub expr_record: &'a wgpu::Buffer,
    pub expr_int_value: &'a wgpu::Buffer,
    pub member_receiver_node: &'a wgpu::Buffer,
    pub member_receiver_token: &'a wgpu::Buffer,
    pub member_name_token: &'a wgpu::Buffer,
    pub stmt_record: &'a wgpu::Buffer,
    pub array_lit_first_element: &'a wgpu::Buffer,
    pub array_lit_element_count: &'a wgpu::Buffer,
    pub array_element_next: &'a wgpu::Buffer,
    pub namespace: &'a wgpu::Buffer,
    pub visibility: &'a wgpu::Buffer,
    pub path_start: &'a wgpu::Buffer,
    pub path_end: &'a wgpu::Buffer,
    pub file_id: &'a wgpu::Buffer,
    pub import_target_kind: &'a wgpu::Buffer,
    pub call_callee_node: &'a wgpu::Buffer,
    pub call_arg_start: &'a wgpu::Buffer,
    pub call_arg_end: &'a wgpu::Buffer,
    pub call_arg_count: &'a wgpu::Buffer,
    pub call_arg_parent_call: &'a wgpu::Buffer,
    pub call_arg_ordinal: &'a wgpu::Buffer,
    pub variant_parent_enum: &'a wgpu::Buffer,
    pub variant_payload_start: &'a wgpu::Buffer,
    pub variant_payload_count: &'a wgpu::Buffer,
    pub match_scrutinee_node: &'a wgpu::Buffer,
    pub match_arm_start: &'a wgpu::Buffer,
    pub match_arm_count: &'a wgpu::Buffer,
    pub match_arm_next: &'a wgpu::Buffer,
    pub match_arm_pattern_node: &'a wgpu::Buffer,
    pub match_arm_payload_start: &'a wgpu::Buffer,
    pub match_arm_payload_count: &'a wgpu::Buffer,
    pub match_arm_result_node: &'a wgpu::Buffer,
    pub match_payload_owner_arm: &'a wgpu::Buffer,
    pub match_payload_match_node: &'a wgpu::Buffer,
    pub match_payload_ordinal: &'a wgpu::Buffer,
    pub struct_field_parent_struct: &'a wgpu::Buffer,
    pub struct_field_ordinal: &'a wgpu::Buffer,
    pub struct_field_type_node: &'a wgpu::Buffer,
    pub struct_decl_field_start: &'a wgpu::Buffer,
    pub struct_decl_field_count: &'a wgpu::Buffer,
    pub struct_lit_head_node: &'a wgpu::Buffer,
    pub struct_lit_field_start: &'a wgpu::Buffer,
    pub struct_lit_field_count: &'a wgpu::Buffer,
    pub struct_lit_field_parent_lit: &'a wgpu::Buffer,
    pub struct_lit_field_value_node: &'a wgpu::Buffer,
    pub semantic_dense_node: &'a wgpu::Buffer,
    pub semantic_count: &'a wgpu::Buffer,
}

#[derive(Clone, Copy)]
pub struct GpuTypeCheckExternalScratchBuffers<'a> {
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub type_expr_ref_tag: &'a wgpu::Buffer,
    pub type_expr_ref_payload: &'a wgpu::Buffer,
    pub type_generic_param_slot_by_token: &'a wgpu::Buffer,
    pub type_const_param_slot_by_token: &'a wgpu::Buffer,
    pub record_family_flag: &'a wgpu::Buffer,
    pub module_record_prefix: &'a wgpu::Buffer,
    pub record_scan_local_prefix: &'a wgpu::Buffer,
    pub module_path_key_radix_block_histogram: &'a wgpu::Buffer,
    pub module_path_key_radix_block_bucket_prefix: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub decl_module_file_id: &'a wgpu::Buffer,
    pub decl_module_id: &'a wgpu::Buffer,
    pub decl_name_id: &'a wgpu::Buffer,
    pub decl_namespace: &'a wgpu::Buffer,
    pub decl_visibility: &'a wgpu::Buffer,
    pub decl_token_start: &'a wgpu::Buffer,
    pub decl_token_end: &'a wgpu::Buffer,
    pub decl_key_to_decl_id: &'a wgpu::Buffer,
    pub decl_key_order_tmp: &'a wgpu::Buffer,
    pub decl_status: &'a wgpu::Buffer,
    pub call_param_count: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub call_arg_record: &'a wgpu::Buffer,
    pub function_lookup_key: &'a wgpu::Buffer,
    pub function_lookup_fn: &'a wgpu::Buffer,
    pub type_decl_generic_param_count: &'a wgpu::Buffer,
    pub type_decl_generic_param_count_by_node: &'a wgpu::Buffer,
    pub type_instance_head_token: &'a wgpu::Buffer,
    pub type_instance_arg_start: &'a wgpu::Buffer,
    pub type_instance_arg_count: &'a wgpu::Buffer,
    pub type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub type_instance_elem_ref_tag: &'a wgpu::Buffer,
    pub type_instance_elem_ref_payload: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub type_instance_state: &'a wgpu::Buffer,
    pub decl_type_key_to_decl_id: &'a wgpu::Buffer,
    pub decl_value_key_to_decl_id: &'a wgpu::Buffer,
    pub method_decl_module_id: &'a wgpu::Buffer,
    pub method_decl_impl_node: &'a wgpu::Buffer,
    pub method_decl_name_token: &'a wgpu::Buffer,
    pub method_decl_name_id: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub method_decl_receiver_mode: &'a wgpu::Buffer,
    pub method_decl_visibility: &'a wgpu::Buffer,
    pub method_key_to_fn_token: &'a wgpu::Buffer,
    pub method_key_status: &'a wgpu::Buffer,
    pub method_key_radix_block_histogram: &'a wgpu::Buffer,
    pub method_key_radix_block_bucket_prefix: &'a wgpu::Buffer,
    pub method_call_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_call_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_call_name_id: &'a wgpu::Buffer,
    pub method_call_site_module_id: &'a wgpu::Buffer,
    pub import_visible_type_count: &'a wgpu::Buffer,
    pub import_visible_value_count: &'a wgpu::Buffer,
    pub import_visible_type_prefix: &'a wgpu::Buffer,
    pub import_visible_value_prefix: &'a wgpu::Buffer,
    pub resolved_type_decl: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_type_status: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub member_result_ref_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_tag: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_payload: &'a wgpu::Buffer,
    pub struct_init_field_context_instance: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub path_start: &'a wgpu::Buffer,
    pub path_len: &'a wgpu::Buffer,
    pub path_segment_count: &'a wgpu::Buffer,
    pub path_segment_base: &'a wgpu::Buffer,
    pub path_segment_name_id: &'a wgpu::Buffer,
    pub path_segment_token: &'a wgpu::Buffer,
    pub path_owner_hir: &'a wgpu::Buffer,
    pub path_owner_token: &'a wgpu::Buffer,
    pub path_owner_module_id: &'a wgpu::Buffer,
    pub path_kind: &'a wgpu::Buffer,
}

impl std::fmt::Display for GpuTypeCheckError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GpuTypeCheckError::Rejected {
                token,
                code,
                detail,
            } => {
                write!(
                    f,
                    "GPU type check rejected token {token}: {code:?} ({detail})"
                )
            }
            GpuTypeCheckError::Gpu(err) => write!(f, "GPU type check failed: {err}"),
        }
    }
}

impl std::error::Error for GpuTypeCheckError {}

impl From<anyhow::Error> for GpuTypeCheckError {
    fn from(err: anyhow::Error) -> Self {
        Self::Gpu(err)
    }
}

pub struct GpuTypeChecker {
    passes: TypeCheckPasses,
    params_buf: LaniusBuffer<TypeCheckParams>,
    status_buf: wgpu::Buffer,
    status_readback: wgpu::Buffer,
    bind_groups: Mutex<Option<ResidentTypeCheckBindGroups>>,
}

pub struct RecordedTypeCheck;

struct TypeCheckPasses {
    hir_active_dispatch_args: PassData,
    names_mark_lexemes: PassData,
    counted_scan_local: PassData,
    counted_scan_blocks: PassData,
    counted_scan_apply: PassData,
    count_dispatch_args: PassData,
    count_pair_max_dispatch_args: PassData,
    names_scatter_lexemes: PassData,
    names_radix_dispatch_args: PassData,
    names_radix_byte_dispatch_args: PassData,
    names_radix_histogram: PassData,
    names_radix_bucket_prefix_active: PassData,
    names_radix_bucket_bases_active: PassData,
    names_radix_bucket_prefix: PassData,
    names_radix_bucket_bases: PassData,
    names_radix_scatter: PassData,
    names_radix_dedup: PassData,
    names_radix_assign_ids: PassData,
    language_names_clear: PassData,
    language_names_mark: PassData,
    language_type_codes_clear: PassData,
    language_decls_materialize: PassData,
    modules_mark_records: PassData,
    modules_extract_record_flag: PassData,
    modules_scatter_paths: PassData,
    modules_count_path_segments: PassData,
    modules_scatter_path_segments: PassData,
    modules_scatter_module_records: PassData,
    modules_scatter_import_records: PassData,
    modules_scatter_decl_core_records: PassData,
    modules_clear_decl_lookup: PassData,
    modules_scatter_decl_span_records: PassData,
    modules_build_module_keys: PassData,
    modules_sort_module_keys_histogram: PassData,
    modules_sort_module_keys_scatter: PassData,
    modules_validate_modules: PassData,
    modules_resolve_imports: PassData,
    modules_clear_file_module_map: PassData,
    modules_build_file_module_map: PassData,
    modules_attach_record_modules: PassData,
    modules_seed_decl_key_order: PassData,
    modules_sort_decl_keys: PassData,
    modules_sort_decl_keys_scatter: PassData,
    modules_validate_decls: PassData,
    modules_mark_decl_namespace_keys: PassData,
    modules_scatter_decl_namespace_keys: PassData,
    modules_mark_public_decl_keys: PassData,
    modules_count_import_visibility: PassData,
    modules_scatter_import_visibility: PassData,
    modules_sort_import_visible_keys: PassData,
    modules_sort_import_visible_keys_scatter: PassData,
    modules_build_import_visible_key_tables: PassData,
    modules_validate_import_visible_keys: PassData,
    modules_resolve_local_paths: PassData,
    modules_resolve_imported_paths: PassData,
    modules_resolve_qualified_paths: PassData,
    modules_clear_type_path_types: PassData,
    modules_project_type_paths: PassData,
    modules_validate_type_paths: PassData,
    modules_project_type_aliases: PassData,
    modules_project_type_instances: PassData,
    modules_mark_value_call_paths: PassData,
    modules_project_value_paths: PassData,
    modules_consume_value_calls: PassData,
    modules_mirror_value_call_leaf: PassData,
    modules_consume_value_consts: PassData,
    modules_consume_value_enum_units: PassData,
    modules_consume_value_enum_calls: PassData,
    modules_bind_match_patterns: PassData,
    modules_type_match_payloads: PassData,
    modules_type_match_exprs: PassData,
    type_instances_clear: PassData,
    type_instances_decl_generic_params: PassData,
    type_instances_generic_param_use_slots: PassData,
    type_instances_collect: PassData,
    type_instances_collect_named: PassData,
    type_instances_collect_aggregate_refs: PassData,
    type_instances_collect_aggregate_details: PassData,
    type_instances_collect_named_arg_refs: PassData,
    type_instances_decl_refs: PassData,
    type_instances_member_receivers: PassData,
    type_instances_member_results: PassData,
    type_instances_member_substitute: PassData,
    type_instances_struct_init_clear: PassData,
    type_instances_struct_init_fields: PassData,
    type_instances_struct_init_substitute: PassData,
    type_instances_array_return_refs: PassData,
    type_instances_array_literal_return_refs: PassData,
    type_instances_array_index_results: PassData,
    type_instances_validate_aggregate_access: PassData,
    predicates_collect: PassData,
    predicates_obligations: PassData,
    conditions_hir: PassData,
    tokens: PassData,
    control: PassData,
    control_hir: PassData,
    scope: PassData,
    scope_hir: PassData,
    calls_clear: PassData,
    calls_return_refs: PassData,
    calls_entrypoints: PassData,
    calls_functions: PassData,
    calls_param_types: PassData,
    calls_intrinsics: PassData,
    calls_clear_hir_call_args: PassData,
    calls_pack_hir_call_args: PassData,
    calls_resolve: PassData,
    calls_infer_array_generics: PassData,
    calls_validate_array_results: PassData,
    calls_erase_generic_params: PassData,
    methods_clear: PassData,
    methods_collect: PassData,
    methods_attach_metadata: PassData,
    methods_bind_self_receivers: PassData,
    methods_seed_key_order: PassData,
    methods_sort_keys: PassData,
    methods_sort_keys_scatter: PassData,
    methods_validate_keys: PassData,
    methods_mark_call_keys: PassData,
    methods_mark_call_return_keys: PassData,
    methods_resolve_table: PassData,
    methods_resolve: PassData,
    visible_clear_resident: PassData,
    visible_scope_blocks: PassData,
    visible_scatter: PassData,
    visible_decode: PassData,
    visible_mark_hir_decl_names: PassData,
    visible_scatter_hir_decl_records: PassData,
    visible_seed_hir_decl_order: PassData,
    visible_sort_hir_decl_keys: PassData,
    visible_sort_hir_decl_keys_scatter: PassData,
    visible_build_hir_decl_scope_leaves: PassData,
    visible_build_hir_decl_scope_tree: PassData,
    visible_hir_names: PassData,
    fn_context_clear: PassData,
    fn_context_mark: PassData,
    fn_context_local: PassData,
    fn_context_scan: PassData,
    fn_context_apply: PassData,
    loop_depth_clear: PassData,
    loop_depth_mark: PassData,
    loop_depth_local: PassData,
    loop_depth_scan: PassData,
    loop_depth_apply: PassData,
}

// Resident type-checking keeps buffers and bind groups in this owner so GPU
// resources stay alive across the retained pipeline even when a field is only
// consumed indirectly by a reflected bind group.
#[allow(dead_code)]
struct ResidentTypeCheckBindGroups {
    source_len: u32,
    source_file_capacity: u32,
    token_capacity: u32,
    hir_node_capacity: u32,
    input_fingerprint: u64,
    uses_hir_control: bool,
    uses_hir_items: bool,
    name_capacity: u32,
    name_n_blocks: u32,
    loop_n_blocks: u32,
    fn_n_blocks: u32,
    name_lexeme_flag: wgpu::Buffer,
    name_lexeme_kind: wgpu::Buffer,
    name_lexeme_prefix: wgpu::Buffer,
    name_scan_local_prefix: wgpu::Buffer,
    name_scan_block_sum: wgpu::Buffer,
    name_scan_prefix_a: wgpu::Buffer,
    name_scan_prefix_b: wgpu::Buffer,
    name_scan_total: wgpu::Buffer,
    name_spans: wgpu::Buffer,
    name_order_in: wgpu::Buffer,
    name_order_tmp: wgpu::Buffer,
    name_id_by_token: wgpu::Buffer,
    language_name_id: wgpu::Buffer,
    language_decl_symbol_slot: LaniusBuffer<u32>,
    language_decl_kind: LaniusBuffer<u32>,
    language_decl_tag: LaniusBuffer<u32>,
    language_decl_name_id: wgpu::Buffer,
    language_type_code_by_name_id: wgpu::Buffer,
    radix_block_histogram: wgpu::Buffer,
    radix_block_bucket_prefix: wgpu::Buffer,
    radix_bucket_total: wgpu::Buffer,
    radix_bucket_base: wgpu::Buffer,
    run_head_mask: wgpu::Buffer,
    adjacent_equal_mask: wgpu::Buffer,
    run_head_prefix: wgpu::Buffer,
    sorted_name_id: wgpu::Buffer,
    name_id_by_input: wgpu::Buffer,
    unique_name_count: wgpu::Buffer,
    module_path: Option<ModulePathState>,
    method_module_id_by_file_id_implicit_root: wgpu::Buffer,
    module_type_path_type: wgpu::Buffer,
    module_type_path_status: wgpu::Buffer,
    module_value_path_expr_head: wgpu::Buffer,
    module_value_path_call_head: wgpu::Buffer,
    module_value_path_call_open: wgpu::Buffer,
    module_value_path_const_head: wgpu::Buffer,
    module_value_path_const_end: wgpu::Buffer,
    module_value_path_status: wgpu::Buffer,
    visible_decl: wgpu::Buffer,
    visible_type: wgpu::Buffer,
    hir_value_decl_name_present: wgpu::Buffer,
    hir_visible_decl_flag: wgpu::Buffer,
    hir_visible_decl_prefix: wgpu::Buffer,
    hir_visible_decl_scan_local_prefix: wgpu::Buffer,
    hir_visible_decl_scan_block_sum: wgpu::Buffer,
    hir_visible_decl_scan_prefix_a: wgpu::Buffer,
    hir_visible_decl_scan_prefix_b: wgpu::Buffer,
    hir_visible_decl_count_out: wgpu::Buffer,
    hir_visible_decl_owner_fn: wgpu::Buffer,
    hir_visible_decl_name_id: wgpu::Buffer,
    hir_visible_decl_token: wgpu::Buffer,
    hir_visible_decl_scope_end: wgpu::Buffer,
    hir_visible_decl_key_order: wgpu::Buffer,
    hir_visible_decl_key_order_tmp: wgpu::Buffer,
    hir_visible_decl_key_radix_dispatch_args: wgpu::Buffer,
    hir_visible_decl_key_radix_block_histogram: wgpu::Buffer,
    hir_visible_decl_key_radix_block_bucket_prefix: wgpu::Buffer,
    hir_visible_decl_key_radix_bucket_total: wgpu::Buffer,
    hir_visible_decl_key_radix_bucket_base: wgpu::Buffer,
    hir_visible_decl_scope_tree: wgpu::Buffer,
    token_active_dispatch_args: wgpu::Buffer,
    hir_active_dispatch_args: wgpu::Buffer,
    token_hir_active_dispatch_args: wgpu::Buffer,
    hir_active_count: wgpu::Buffer,
    hir_active_dispatch: wgpu::BindGroup,
    loop_delta: wgpu::Buffer,
    loop_depth_inblock: wgpu::Buffer,
    loop_block_sum: wgpu::Buffer,
    loop_prefix_a: wgpu::Buffer,
    loop_prefix_b: wgpu::Buffer,
    loop_block_prefix: wgpu::Buffer,
    loop_depth: wgpu::Buffer,
    enclosing_fn: wgpu::Buffer,
    enclosing_fn_end: wgpu::Buffer,
    fn_event_value: wgpu::Buffer,
    fn_event_end: wgpu::Buffer,
    fn_event_index: wgpu::Buffer,
    fn_event_inblock: wgpu::Buffer,
    fn_block_sum: wgpu::Buffer,
    fn_prefix_a: wgpu::Buffer,
    fn_prefix_b: wgpu::Buffer,
    fn_block_prefix: wgpu::Buffer,
    call_fn_index: wgpu::Buffer,
    call_intrinsic_tag: wgpu::Buffer,
    fn_entrypoint_tag: wgpu::Buffer,
    call_return_type: wgpu::Buffer,
    call_return_type_token: wgpu::Buffer,
    call_param_count: wgpu::Buffer,
    call_param_type: wgpu::Buffer,
    call_param_ref_tag: wgpu::Buffer,
    call_param_ref_payload: wgpu::Buffer,
    call_arg_record: wgpu::Buffer,
    call_arg_node: wgpu::Buffer,
    function_lookup_key: wgpu::Buffer,
    function_lookup_fn: wgpu::Buffer,
    method_decl_receiver_ref_tag: wgpu::Buffer,
    method_decl_receiver_ref_payload: wgpu::Buffer,
    method_decl_module_id: wgpu::Buffer,
    method_decl_impl_node: wgpu::Buffer,
    method_decl_name_token: wgpu::Buffer,
    method_decl_name_id: wgpu::Buffer,
    method_decl_param_offset: wgpu::Buffer,
    method_decl_receiver_mode: wgpu::Buffer,
    method_decl_visibility: wgpu::Buffer,
    method_module_count_out_implicit_root: wgpu::Buffer,
    method_key_to_fn_token: wgpu::Buffer,
    method_key_order_tmp: wgpu::Buffer,
    method_key_status: wgpu::Buffer,
    method_key_duplicate_of: wgpu::Buffer,
    method_key_radix_block_histogram: wgpu::Buffer,
    method_key_radix_block_bucket_prefix: wgpu::Buffer,
    method_key_radix_bucket_total: wgpu::Buffer,
    method_key_radix_bucket_base: wgpu::Buffer,
    method_call_receiver_ref_tag: wgpu::Buffer,
    method_call_receiver_ref_payload: wgpu::Buffer,
    method_call_name_id: wgpu::Buffer,
    method_call_site_module_id: wgpu::Buffer,
    type_expr_ref_tag: wgpu::Buffer,
    type_expr_ref_payload: wgpu::Buffer,
    type_instance_kind: wgpu::Buffer,
    type_instance_head_token: wgpu::Buffer,
    type_decl_generic_param_count: wgpu::Buffer,
    type_decl_generic_param_count_by_node: wgpu::Buffer,
    type_decl_const_param_count_by_node: wgpu::Buffer,
    type_decl_hir_node_by_token: wgpu::Buffer,
    type_generic_param_slot_by_token: wgpu::Buffer,
    type_const_param_slot_by_token: wgpu::Buffer,
    type_instance_decl_token: wgpu::Buffer,
    type_instance_arg_start: wgpu::Buffer,
    type_instance_arg_count: wgpu::Buffer,
    type_instance_arg_ref_tag: wgpu::Buffer,
    type_instance_arg_ref_payload: wgpu::Buffer,
    type_instance_elem_ref_tag: wgpu::Buffer,
    type_instance_elem_ref_payload: wgpu::Buffer,
    type_instance_len_kind: wgpu::Buffer,
    type_instance_len_payload: wgpu::Buffer,
    type_instance_state: wgpu::Buffer,
    predicate_owner_node: wgpu::Buffer,
    predicate_subject_token: wgpu::Buffer,
    predicate_bound_token: wgpu::Buffer,
    predicate_bound_arg_count: wgpu::Buffer,
    predicate_bound_first_arg_token: wgpu::Buffer,
    predicate_bound_second_arg_token: wgpu::Buffer,
    predicate_status: wgpu::Buffer,
    fn_return_ref_tag: wgpu::Buffer,
    fn_return_ref_payload: wgpu::Buffer,
    decl_type_ref_tag: wgpu::Buffer,
    decl_type_ref_payload: wgpu::Buffer,
    member_result_context_instance: wgpu::Buffer,
    member_result_ref_tag: wgpu::Buffer,
    member_result_ref_payload: wgpu::Buffer,
    member_result_field_ordinal: wgpu::Buffer,
    struct_init_field_expected_ref_tag: wgpu::Buffer,
    struct_init_field_expected_ref_payload: wgpu::Buffer,
    struct_init_field_context_instance: wgpu::Buffer,
    struct_init_field_ordinal: wgpu::Buffer,
    struct_init_field_ordinal_by_node: wgpu::Buffer,
    name_scan_steps: Vec<NameScanStep>,
    name_bind_groups: NameBindGroups,
    language_name_bind_groups: LanguageNameBindGroups,
    loop_params: LaniusBuffer<LoopDepthParams>,
    loop_scan_steps: Vec<LoopDepthScanStep>,
    fn_params: LaniusBuffer<FnContextParams>,
    fn_scan_steps: Vec<FnContextScanStep>,
    loop_bind_groups: LoopDepthBindGroups,
    fn_context_bind_groups: FnContextBindGroups,
    visible_bind_groups: VisibleBindGroups,
    calls: CallBindGroups,
    methods: MethodBindGroups,
    predicates: Option<PredicateBindGroups>,
    type_instances: TypeInstanceBindGroups,
    conditions_hir: wgpu::BindGroup,
    tokens: wgpu::BindGroup,
    control: wgpu::BindGroup,
    scope: wgpu::BindGroup,
    scope_hir: wgpu::BindGroup,
}

pub struct GpuCodegenBuffers<'a> {
    pub name_id_by_token: &'a wgpu::Buffer,
    pub enclosing_fn: &'a wgpu::Buffer,
    pub visible_decl: &'a wgpu::Buffer,
    pub visible_type: &'a wgpu::Buffer,
    pub path_count_out: &'a wgpu::Buffer,
    pub path_owner_token: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub decl_count_out: &'a wgpu::Buffer,
    pub decl_kind: &'a wgpu::Buffer,
    pub decl_name_token: &'a wgpu::Buffer,
    pub decl_id_by_name_token: &'a wgpu::Buffer,
    pub decl_hir_node: &'a wgpu::Buffer,
    pub decl_parent_type_decl: &'a wgpu::Buffer,
    pub decl_type_ref_tag: &'a wgpu::Buffer,
    pub decl_type_ref_payload: &'a wgpu::Buffer,
    pub type_expr_ref_tag: &'a wgpu::Buffer,
    pub type_expr_ref_payload: &'a wgpu::Buffer,
    pub module_value_path_call_head: &'a wgpu::Buffer,
    pub module_value_path_call_open: &'a wgpu::Buffer,
    pub module_value_path_const_head: &'a wgpu::Buffer,
    pub module_value_path_const_end: &'a wgpu::Buffer,
    pub call_fn_index: &'a wgpu::Buffer,
    pub call_intrinsic_tag: &'a wgpu::Buffer,
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub call_return_type: &'a wgpu::Buffer,
    pub call_return_type_token: &'a wgpu::Buffer,
    pub call_param_count: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub method_decl_module_id: &'a wgpu::Buffer,
    pub method_decl_name_token: &'a wgpu::Buffer,
    pub method_decl_name_id: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub method_decl_receiver_mode: &'a wgpu::Buffer,
    pub method_decl_visibility: &'a wgpu::Buffer,
    pub method_key_to_fn_token: &'a wgpu::Buffer,
    pub method_key_status: &'a wgpu::Buffer,
    pub method_call_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_call_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_call_name_id: &'a wgpu::Buffer,
    pub method_call_site_module_id: &'a wgpu::Buffer,
    pub type_instance_kind: &'a wgpu::Buffer,
    pub type_instance_decl_token: &'a wgpu::Buffer,
    pub type_instance_arg_start: &'a wgpu::Buffer,
    pub type_instance_arg_count: &'a wgpu::Buffer,
    pub type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub fn_return_ref_tag: &'a wgpu::Buffer,
    pub fn_return_ref_payload: &'a wgpu::Buffer,
    pub member_result_ref_tag: &'a wgpu::Buffer,
    pub member_result_ref_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_tag: &'a wgpu::Buffer,
    pub struct_init_field_expected_ref_payload: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal_by_node: &'a wgpu::Buffer,
}

pub struct OwnedGpuCodegenBuffers {
    name_id_by_token: wgpu::Buffer,
    enclosing_fn: wgpu::Buffer,
    visible_decl: wgpu::Buffer,
    visible_type: wgpu::Buffer,
    path_count_out: wgpu::Buffer,
    path_owner_token: wgpu::Buffer,
    path_id_by_owner_hir: wgpu::Buffer,
    resolved_value_decl: wgpu::Buffer,
    resolved_value_status: wgpu::Buffer,
    decl_count_out: wgpu::Buffer,
    decl_kind: wgpu::Buffer,
    decl_name_token: wgpu::Buffer,
    decl_id_by_name_token: wgpu::Buffer,
    decl_hir_node: wgpu::Buffer,
    decl_parent_type_decl: wgpu::Buffer,
    decl_type_ref_tag: wgpu::Buffer,
    decl_type_ref_payload: wgpu::Buffer,
    type_expr_ref_tag: wgpu::Buffer,
    type_expr_ref_payload: wgpu::Buffer,
    module_value_path_call_head: wgpu::Buffer,
    module_value_path_call_open: wgpu::Buffer,
    module_value_path_const_head: wgpu::Buffer,
    module_value_path_const_end: wgpu::Buffer,
    call_fn_index: wgpu::Buffer,
    call_intrinsic_tag: wgpu::Buffer,
    fn_entrypoint_tag: wgpu::Buffer,
    call_return_type: wgpu::Buffer,
    call_return_type_token: wgpu::Buffer,
    call_param_count: wgpu::Buffer,
    call_param_type: wgpu::Buffer,
    method_decl_module_id: wgpu::Buffer,
    method_decl_name_token: wgpu::Buffer,
    method_decl_name_id: wgpu::Buffer,
    method_decl_receiver_ref_tag: wgpu::Buffer,
    method_decl_receiver_ref_payload: wgpu::Buffer,
    method_decl_param_offset: wgpu::Buffer,
    method_decl_receiver_mode: wgpu::Buffer,
    method_decl_visibility: wgpu::Buffer,
    method_key_to_fn_token: wgpu::Buffer,
    method_key_status: wgpu::Buffer,
    method_call_receiver_ref_tag: wgpu::Buffer,
    method_call_receiver_ref_payload: wgpu::Buffer,
    method_call_name_id: wgpu::Buffer,
    method_call_site_module_id: wgpu::Buffer,
    type_instance_kind: wgpu::Buffer,
    type_instance_decl_token: wgpu::Buffer,
    type_instance_arg_start: wgpu::Buffer,
    type_instance_arg_count: wgpu::Buffer,
    type_instance_arg_ref_tag: wgpu::Buffer,
    type_instance_arg_ref_payload: wgpu::Buffer,
    type_instance_len_kind: wgpu::Buffer,
    type_instance_len_payload: wgpu::Buffer,
    fn_return_ref_tag: wgpu::Buffer,
    fn_return_ref_payload: wgpu::Buffer,
    member_result_ref_tag: wgpu::Buffer,
    member_result_ref_payload: wgpu::Buffer,
    member_result_field_ordinal: wgpu::Buffer,
    struct_init_field_expected_ref_tag: wgpu::Buffer,
    struct_init_field_expected_ref_payload: wgpu::Buffer,
    struct_init_field_ordinal: wgpu::Buffer,
    struct_init_field_ordinal_by_node: wgpu::Buffer,
}

#[derive(Clone, Copy)]
pub struct GpuX86CodegenBuffers<'a> {
    pub enclosing_fn: &'a wgpu::Buffer,
    pub visible_decl: &'a wgpu::Buffer,
    pub visible_type: &'a wgpu::Buffer,
    pub path_count_out: &'a wgpu::Buffer,
    pub path_id_by_owner_hir: &'a wgpu::Buffer,
    pub resolved_value_decl: &'a wgpu::Buffer,
    pub resolved_value_status: &'a wgpu::Buffer,
    pub decl_count_out: &'a wgpu::Buffer,
    pub decl_kind: &'a wgpu::Buffer,
    pub decl_name_token: &'a wgpu::Buffer,
    pub decl_id_by_name_token: &'a wgpu::Buffer,
    pub decl_hir_node: &'a wgpu::Buffer,
    pub decl_parent_type_decl: &'a wgpu::Buffer,
    pub decl_type_ref_tag: &'a wgpu::Buffer,
    pub decl_type_ref_payload: &'a wgpu::Buffer,
    pub call_fn_index: &'a wgpu::Buffer,
    pub call_intrinsic_tag: &'a wgpu::Buffer,
    pub fn_entrypoint_tag: &'a wgpu::Buffer,
    pub call_return_type: &'a wgpu::Buffer,
    pub call_return_type_token: &'a wgpu::Buffer,
    pub call_param_type: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_tag: &'a wgpu::Buffer,
    pub method_decl_receiver_ref_payload: &'a wgpu::Buffer,
    pub method_decl_param_offset: &'a wgpu::Buffer,
    pub type_instance_kind: &'a wgpu::Buffer,
    pub type_instance_decl_token: &'a wgpu::Buffer,
    pub type_instance_len_kind: &'a wgpu::Buffer,
    pub type_instance_len_payload: &'a wgpu::Buffer,
    pub member_result_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal: &'a wgpu::Buffer,
    pub struct_init_field_ordinal_by_node: &'a wgpu::Buffer,
}

pub struct OwnedGpuX86CodegenBuffers {
    enclosing_fn: wgpu::Buffer,
    visible_decl: wgpu::Buffer,
    visible_type: wgpu::Buffer,
    path_count_out: wgpu::Buffer,
    path_id_by_owner_hir: wgpu::Buffer,
    resolved_value_decl: wgpu::Buffer,
    resolved_value_status: wgpu::Buffer,
    decl_count_out: wgpu::Buffer,
    decl_kind: wgpu::Buffer,
    decl_name_token: wgpu::Buffer,
    decl_id_by_name_token: wgpu::Buffer,
    decl_hir_node: wgpu::Buffer,
    decl_parent_type_decl: wgpu::Buffer,
    decl_type_ref_tag: wgpu::Buffer,
    decl_type_ref_payload: wgpu::Buffer,
    call_fn_index: wgpu::Buffer,
    call_intrinsic_tag: wgpu::Buffer,
    fn_entrypoint_tag: wgpu::Buffer,
    call_return_type: wgpu::Buffer,
    call_return_type_token: wgpu::Buffer,
    call_param_type: wgpu::Buffer,
    method_decl_receiver_ref_tag: wgpu::Buffer,
    method_decl_receiver_ref_payload: wgpu::Buffer,
    method_decl_param_offset: wgpu::Buffer,
    type_instance_kind: wgpu::Buffer,
    type_instance_decl_token: wgpu::Buffer,
    type_instance_len_kind: wgpu::Buffer,
    type_instance_len_payload: wgpu::Buffer,
    member_result_field_ordinal: wgpu::Buffer,
    struct_init_field_ordinal: wgpu::Buffer,
    struct_init_field_ordinal_by_node: wgpu::Buffer,
}

impl OwnedGpuX86CodegenBuffers {
    fn copy_buffer_for_backend(
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        label: &str,
        src: &wgpu::Buffer,
        words: u32,
    ) -> wgpu::Buffer {
        let byte_len = u64::from(words.max(1)).saturating_mul(4);
        let byte_len = byte_len.min(src.size());
        let copy = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some(label),
            size: byte_len.max(4),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::COPY_SRC
                | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("type_check.codegen.backend_copy.encoder"),
        });
        encoder.copy_buffer_to_buffer(src, 0, &copy, 0, byte_len);
        queue.submit(Some(encoder.finish()));
        let _ = device.poll(wgpu::PollType::wait_indefinitely());
        copy
    }

    pub fn copy_backend_metadata_before_parser_replay(
        &mut self,
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        words: u32,
    ) {
        self.fn_entrypoint_tag = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.fn_entrypoint_tag.backend_copy",
            &self.fn_entrypoint_tag,
            words,
        );
        self.decl_type_ref_tag = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.decl_type_ref_tag.backend_copy",
            &self.decl_type_ref_tag,
            words,
        );
        self.decl_type_ref_payload = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.decl_type_ref_payload.backend_copy",
            &self.decl_type_ref_payload,
            words,
        );
        self.type_instance_kind = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.type_instance_kind.backend_copy",
            &self.type_instance_kind,
            words,
        );
        self.type_instance_decl_token = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.type_instance_decl_token.backend_copy",
            &self.type_instance_decl_token,
            words,
        );
        self.type_instance_len_kind = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.type_instance_len_kind.backend_copy",
            &self.type_instance_len_kind,
            words,
        );
        self.type_instance_len_payload = Self::copy_buffer_for_backend(
            device,
            queue,
            "type_check.codegen.type_instance_len_payload.backend_copy",
            &self.type_instance_len_payload,
            words,
        );
    }

    pub fn as_ref(&self) -> GpuX86CodegenBuffers<'_> {
        GpuX86CodegenBuffers {
            enclosing_fn: &self.enclosing_fn,
            visible_decl: &self.visible_decl,
            visible_type: &self.visible_type,
            path_count_out: &self.path_count_out,
            path_id_by_owner_hir: &self.path_id_by_owner_hir,
            resolved_value_decl: &self.resolved_value_decl,
            resolved_value_status: &self.resolved_value_status,
            decl_count_out: &self.decl_count_out,
            decl_kind: &self.decl_kind,
            decl_name_token: &self.decl_name_token,
            decl_id_by_name_token: &self.decl_id_by_name_token,
            decl_hir_node: &self.decl_hir_node,
            decl_parent_type_decl: &self.decl_parent_type_decl,
            decl_type_ref_tag: &self.decl_type_ref_tag,
            decl_type_ref_payload: &self.decl_type_ref_payload,
            call_fn_index: &self.call_fn_index,
            call_intrinsic_tag: &self.call_intrinsic_tag,
            fn_entrypoint_tag: &self.fn_entrypoint_tag,
            call_return_type: &self.call_return_type,
            call_return_type_token: &self.call_return_type_token,
            call_param_type: &self.call_param_type,
            method_decl_receiver_ref_tag: &self.method_decl_receiver_ref_tag,
            method_decl_receiver_ref_payload: &self.method_decl_receiver_ref_payload,
            method_decl_param_offset: &self.method_decl_param_offset,
            type_instance_kind: &self.type_instance_kind,
            type_instance_decl_token: &self.type_instance_decl_token,
            type_instance_len_kind: &self.type_instance_len_kind,
            type_instance_len_payload: &self.type_instance_len_payload,
            member_result_field_ordinal: &self.member_result_field_ordinal,
            struct_init_field_ordinal: &self.struct_init_field_ordinal,
            struct_init_field_ordinal_by_node: &self.struct_init_field_ordinal_by_node,
        }
    }
}

impl OwnedGpuCodegenBuffers {
    pub fn as_ref(&self) -> GpuCodegenBuffers<'_> {
        GpuCodegenBuffers {
            name_id_by_token: &self.name_id_by_token,
            enclosing_fn: &self.enclosing_fn,
            visible_decl: &self.visible_decl,
            visible_type: &self.visible_type,
            path_count_out: &self.path_count_out,
            path_owner_token: &self.path_owner_token,
            path_id_by_owner_hir: &self.path_id_by_owner_hir,
            resolved_value_decl: &self.resolved_value_decl,
            resolved_value_status: &self.resolved_value_status,
            decl_count_out: &self.decl_count_out,
            decl_kind: &self.decl_kind,
            decl_name_token: &self.decl_name_token,
            decl_id_by_name_token: &self.decl_id_by_name_token,
            decl_hir_node: &self.decl_hir_node,
            decl_parent_type_decl: &self.decl_parent_type_decl,
            decl_type_ref_tag: &self.decl_type_ref_tag,
            decl_type_ref_payload: &self.decl_type_ref_payload,
            type_expr_ref_tag: &self.type_expr_ref_tag,
            type_expr_ref_payload: &self.type_expr_ref_payload,
            module_value_path_call_head: &self.module_value_path_call_head,
            module_value_path_call_open: &self.module_value_path_call_open,
            module_value_path_const_head: &self.module_value_path_const_head,
            module_value_path_const_end: &self.module_value_path_const_end,
            call_fn_index: &self.call_fn_index,
            call_intrinsic_tag: &self.call_intrinsic_tag,
            fn_entrypoint_tag: &self.fn_entrypoint_tag,
            call_return_type: &self.call_return_type,
            call_return_type_token: &self.call_return_type_token,
            call_param_count: &self.call_param_count,
            call_param_type: &self.call_param_type,
            method_decl_module_id: &self.method_decl_module_id,
            method_decl_name_token: &self.method_decl_name_token,
            method_decl_name_id: &self.method_decl_name_id,
            method_decl_receiver_ref_tag: &self.method_decl_receiver_ref_tag,
            method_decl_receiver_ref_payload: &self.method_decl_receiver_ref_payload,
            method_decl_param_offset: &self.method_decl_param_offset,
            method_decl_receiver_mode: &self.method_decl_receiver_mode,
            method_decl_visibility: &self.method_decl_visibility,
            method_key_to_fn_token: &self.method_key_to_fn_token,
            method_key_status: &self.method_key_status,
            method_call_receiver_ref_tag: &self.method_call_receiver_ref_tag,
            method_call_receiver_ref_payload: &self.method_call_receiver_ref_payload,
            method_call_name_id: &self.method_call_name_id,
            method_call_site_module_id: &self.method_call_site_module_id,
            type_instance_kind: &self.type_instance_kind,
            type_instance_decl_token: &self.type_instance_decl_token,
            type_instance_arg_start: &self.type_instance_arg_start,
            type_instance_arg_count: &self.type_instance_arg_count,
            type_instance_arg_ref_tag: &self.type_instance_arg_ref_tag,
            type_instance_arg_ref_payload: &self.type_instance_arg_ref_payload,
            type_instance_len_kind: &self.type_instance_len_kind,
            type_instance_len_payload: &self.type_instance_len_payload,
            fn_return_ref_tag: &self.fn_return_ref_tag,
            fn_return_ref_payload: &self.fn_return_ref_payload,
            member_result_ref_tag: &self.member_result_ref_tag,
            member_result_ref_payload: &self.member_result_ref_payload,
            member_result_field_ordinal: &self.member_result_field_ordinal,
            struct_init_field_expected_ref_tag: &self.struct_init_field_expected_ref_tag,
            struct_init_field_expected_ref_payload: &self.struct_init_field_expected_ref_payload,
            struct_init_field_ordinal: &self.struct_init_field_ordinal,
            struct_init_field_ordinal_by_node: &self.struct_init_field_ordinal_by_node,
        }
    }
}
