use super::*;

pub(super) fn create_module_path_state_with_passes(
    passes: &TypeCheckPasses,
    device: &wgpu::Device,
    params: &LaniusBuffer<TypeCheckParams>,
    token_capacity: u32,
    hir_node_capacity: u32,
    token_buf: &wgpu::Buffer,
    token_count_buf: &wgpu::Buffer,
    hir_status_buf: &wgpu::Buffer,
    hir_kind_buf: &wgpu::Buffer,
    hir_token_pos_buf: &wgpu::Buffer,
    hir_token_end_buf: &wgpu::Buffer,
    status_buf: &wgpu::Buffer,
    hir_items: GpuTypeCheckHirItemBuffers<'_>,
    name_id_by_token: &wgpu::Buffer,
    language_name_id: &wgpu::Buffer,
    module_type_path_type: &wgpu::Buffer,
    module_type_path_status: &wgpu::Buffer,
    module_value_path_expr_head: &wgpu::Buffer,
    module_value_path_call_head: &wgpu::Buffer,
    module_value_path_call_open: &wgpu::Buffer,
    module_value_path_const_head: &wgpu::Buffer,
    module_value_path_const_end: &wgpu::Buffer,
    module_value_path_status: &wgpu::Buffer,
    visible_decl: &wgpu::Buffer,
    visible_type: &wgpu::Buffer,
    call_fn_index: &wgpu::Buffer,
    call_return_type: &wgpu::Buffer,
    call_return_type_token: &wgpu::Buffer,
    call_param_count: &wgpu::Buffer,
    call_param_type: &wgpu::Buffer,
    call_arg_record: &wgpu::Buffer,
    type_expr_ref_tag: &wgpu::Buffer,
    type_expr_ref_payload: &wgpu::Buffer,
    type_instance_kind: &wgpu::Buffer,
    type_instance_decl_token: &wgpu::Buffer,
    type_instance_arg_start: &wgpu::Buffer,
    type_instance_arg_count: &wgpu::Buffer,
    type_instance_arg_ref_tag: &wgpu::Buffer,
    type_instance_arg_ref_payload: &wgpu::Buffer,
    type_decl_generic_param_count: &wgpu::Buffer,
    type_instance_state: &wgpu::Buffer,
) -> Result<ModulePathState> {
    include!("module_path_body.inc")
}
