use super::*;

pub(super) struct OwnedX86ParserBuffers {
    pub(super) ll1_status: wgpu::Buffer,
    pub(super) tree_active_dispatch_args: wgpu::Buffer,
    pub(super) hir_kind: wgpu::Buffer,
    pub(super) parent: wgpu::Buffer,
    pub(super) subtree_end: wgpu::Buffer,
    pub(super) hir_item_kind: wgpu::Buffer,
    pub(super) hir_item_decl_token: wgpu::Buffer,
    pub(super) hir_item_name_token: wgpu::Buffer,
    pub(super) hir_item_namespace: wgpu::Buffer,
    pub(super) hir_item_visibility: wgpu::Buffer,
    pub(super) hir_item_path_start: wgpu::Buffer,
    pub(super) hir_token_pos: wgpu::Buffer,
    pub(super) hir_type_form: wgpu::Buffer,
    pub(super) hir_type_value_node: wgpu::Buffer,
    pub(super) hir_type_len_token: wgpu::Buffer,
    pub(super) hir_type_len_value: wgpu::Buffer,
    pub(super) hir_type_path_leaf_node: wgpu::Buffer,
    pub(super) hir_type_path_leaf_link_a: wgpu::Buffer,
    pub(super) hir_type_path_leaf_link_b: wgpu::Buffer,
    pub(super) hir_type_arg_start: wgpu::Buffer,
    pub(super) hir_type_arg_count: wgpu::Buffer,
    pub(super) hir_type_arg_next: wgpu::Buffer,
    pub(super) hir_type_arg_rank_a: wgpu::Buffer,
    pub(super) hir_type_alias_target_node: wgpu::Buffer,
    pub(super) hir_fn_return_type_node: wgpu::Buffer,
    pub(super) hir_semantic_dense_node: wgpu::Buffer,
    pub(super) hir_param_record: wgpu::Buffer,
    pub(super) hir_stmt_record: wgpu::Buffer,
    pub(super) hir_expr_record: wgpu::Buffer,
    pub(super) hir_expr_result_root_node: wgpu::Buffer,
    pub(super) hir_expr_int_value: wgpu::Buffer,
    pub(super) hir_member_receiver_node: wgpu::Buffer,
    pub(super) hir_member_name_token: wgpu::Buffer,
    pub(super) hir_call_callee_node: wgpu::Buffer,
    pub(super) hir_call_arg_start: wgpu::Buffer,
    pub(super) hir_call_arg_end: wgpu::Buffer,
    pub(super) hir_call_arg_count: wgpu::Buffer,
    pub(super) hir_call_arg_parent_call: wgpu::Buffer,
    pub(super) hir_call_arg_ordinal: wgpu::Buffer,
    pub(super) hir_array_lit_first_element: wgpu::Buffer,
    pub(super) hir_array_lit_element_count: wgpu::Buffer,
    pub(super) hir_array_element_parent_lit: wgpu::Buffer,
    pub(super) hir_array_element_ordinal: wgpu::Buffer,
    pub(super) hir_array_element_next: wgpu::Buffer,
    pub(super) hir_array_element_previous: wgpu::Buffer,
    pub(super) hir_variant_parent_enum: wgpu::Buffer,
    pub(super) hir_variant_ordinal: wgpu::Buffer,
    pub(super) hir_variant_payload_count: wgpu::Buffer,
    pub(super) hir_variant_payload_owner_a: wgpu::Buffer,
    pub(super) hir_variant_payload_owner_b: wgpu::Buffer,
    pub(super) hir_match_scrutinee_node: wgpu::Buffer,
    pub(super) hir_match_arm_start: wgpu::Buffer,
    pub(super) hir_match_arm_count: wgpu::Buffer,
    pub(super) hir_match_arm_next: wgpu::Buffer,
    pub(super) hir_match_arm_pattern_node: wgpu::Buffer,
    pub(super) hir_match_arm_payload_start: wgpu::Buffer,
    pub(super) hir_match_arm_payload_count: wgpu::Buffer,
    pub(super) hir_match_arm_result_node: wgpu::Buffer,
    pub(super) hir_struct_decl_field_count: wgpu::Buffer,
    pub(super) hir_struct_lit_head_node: wgpu::Buffer,
    pub(super) hir_struct_lit_context_stmt_node: wgpu::Buffer,
    pub(super) hir_struct_lit_field_parent_lit: wgpu::Buffer,
    pub(super) hir_struct_lit_field_start: wgpu::Buffer,
    pub(super) hir_struct_lit_field_count: wgpu::Buffer,
    pub(super) hir_struct_lit_field_value_node: wgpu::Buffer,
    pub(super) hir_struct_lit_field_next: wgpu::Buffer,
}

pub(super) struct OwnedX86DiagnosticBuffers {
    pub(super) source_len: u32,
    pub(super) tokens_out: wgpu::Buffer,
}

impl OwnedX86DiagnosticBuffers {
    pub(super) fn from_lexer_buffers(bufs: &LexerBuffers) -> Self {
        Self {
            source_len: bufs.n,
            tokens_out: bufs.tokens_out.buffer.clone(),
        }
    }
}

impl OwnedX86ParserBuffers {
    pub(super) fn from_parser_buffers(bufs: &ParserBuffers) -> Self {
        Self {
            ll1_status: bufs.ll1_status.buffer.clone(),
            tree_active_dispatch_args: bufs.tree_active_dispatch_args.buffer.clone(),
            hir_kind: bufs.hir_kind.buffer.clone(),
            parent: bufs.parent.buffer.clone(),
            subtree_end: bufs.subtree_end.buffer.clone(),
            hir_item_kind: bufs.hir_item_kind.buffer.clone(),
            hir_item_decl_token: bufs.hir_item_decl_token.buffer.clone(),
            hir_item_name_token: bufs.hir_item_name_token.buffer.clone(),
            hir_item_namespace: bufs.hir_item_namespace.buffer.clone(),
            hir_item_visibility: bufs.hir_item_visibility.buffer.clone(),
            hir_item_path_start: bufs.hir_item_path_start.buffer.clone(),
            hir_token_pos: bufs.hir_token_pos.buffer.clone(),
            hir_type_form: bufs.hir_type_form.buffer.clone(),
            hir_type_value_node: bufs.hir_type_value_node.buffer.clone(),
            hir_type_len_token: bufs.hir_type_len_token.buffer.clone(),
            hir_type_len_value: bufs.hir_type_len_value.buffer.clone(),
            hir_type_path_leaf_node: bufs.hir_type_path_leaf_node.buffer.clone(),
            hir_type_path_leaf_link_a: bufs.hir_type_path_leaf_link_a.buffer.clone(),
            hir_type_path_leaf_link_b: bufs.hir_type_path_leaf_link_b.buffer.clone(),
            hir_type_arg_start: bufs.hir_type_arg_start.buffer.clone(),
            hir_type_arg_count: bufs.hir_type_arg_count.buffer.clone(),
            hir_type_arg_next: bufs.hir_type_arg_next.buffer.clone(),
            hir_type_arg_rank_a: bufs.hir_type_arg_rank_a.buffer.clone(),
            hir_type_alias_target_node: bufs.hir_type_alias_target_node.buffer.clone(),
            hir_fn_return_type_node: bufs.hir_fn_return_type_node.buffer.clone(),
            hir_semantic_dense_node: bufs.hir_semantic_dense_node.buffer.clone(),
            hir_param_record: bufs.hir_param_record.buffer.clone(),
            hir_stmt_record: bufs.hir_stmt_record.buffer.clone(),
            hir_expr_record: bufs.hir_expr_record.buffer.clone(),
            hir_expr_result_root_node: bufs.hir_expr_result_root_node.buffer.clone(),
            hir_expr_int_value: bufs.hir_expr_int_value.buffer.clone(),
            hir_member_receiver_node: bufs.hir_member_receiver_node.buffer.clone(),
            hir_member_name_token: bufs.hir_member_name_token.buffer.clone(),
            hir_call_callee_node: bufs.hir_call_callee_node.buffer.clone(),
            hir_call_arg_start: bufs.hir_call_arg_start.buffer.clone(),
            hir_call_arg_end: bufs.hir_call_arg_end.buffer.clone(),
            hir_call_arg_count: bufs.hir_call_arg_count.buffer.clone(),
            hir_call_arg_parent_call: bufs.hir_call_arg_parent_call.buffer.clone(),
            hir_call_arg_ordinal: bufs.hir_call_arg_ordinal.buffer.clone(),
            hir_array_lit_first_element: bufs.hir_array_lit_first_element.buffer.clone(),
            hir_array_lit_element_count: bufs.hir_array_lit_element_count.buffer.clone(),
            hir_array_element_parent_lit: bufs.hir_array_element_parent_lit.buffer.clone(),
            hir_array_element_ordinal: bufs.hir_array_element_ordinal.buffer.clone(),
            hir_array_element_next: bufs.hir_array_element_next.buffer.clone(),
            hir_array_element_previous: bufs.hir_array_element_previous.buffer.clone(),
            hir_variant_parent_enum: bufs.hir_variant_parent_enum.buffer.clone(),
            hir_variant_ordinal: bufs.hir_variant_ordinal.buffer.clone(),
            hir_variant_payload_count: bufs.hir_variant_payload_count.buffer.clone(),
            hir_variant_payload_owner_a: bufs.hir_variant_payload_owner_a.buffer.clone(),
            hir_variant_payload_owner_b: bufs.hir_variant_payload_owner_b.buffer.clone(),
            hir_match_scrutinee_node: bufs.hir_match_scrutinee_node.buffer.clone(),
            hir_match_arm_start: bufs.hir_match_arm_start.buffer.clone(),
            hir_match_arm_count: bufs.hir_match_arm_count.buffer.clone(),
            hir_match_arm_next: bufs.hir_match_arm_next.buffer.clone(),
            hir_match_arm_pattern_node: bufs.hir_match_arm_pattern_node.buffer.clone(),
            hir_match_arm_payload_start: bufs.hir_match_arm_payload_start.buffer.clone(),
            hir_match_arm_payload_count: bufs.hir_match_arm_payload_count.buffer.clone(),
            hir_match_arm_result_node: bufs.hir_match_arm_result_node.buffer.clone(),
            hir_struct_decl_field_count: bufs.hir_struct_decl_field_count.buffer.clone(),
            hir_struct_lit_head_node: bufs.hir_struct_lit_head_node.buffer.clone(),
            hir_struct_lit_context_stmt_node: bufs.hir_struct_lit_context_stmt_node.buffer.clone(),
            hir_struct_lit_field_parent_lit: bufs.hir_struct_lit_field_parent_lit.buffer.clone(),
            hir_struct_lit_field_start: bufs.hir_struct_lit_field_start.buffer.clone(),
            hir_struct_lit_field_count: bufs.hir_struct_lit_field_count.buffer.clone(),
            hir_struct_lit_field_value_node: bufs.hir_struct_lit_field_value_node.buffer.clone(),
            hir_struct_lit_field_next: bufs.hir_struct_lit_field_next.buffer.clone(),
        }
    }
}

#[allow(dead_code)]
pub(super) struct OwnedTypecheckParserBuffers {
    pub(super) ll1_status: wgpu::Buffer,
    pub(super) node_kind: wgpu::Buffer,
    pub(super) parent: wgpu::Buffer,
    pub(super) first_child: wgpu::Buffer,
    pub(super) next_sibling: wgpu::Buffer,
    pub(super) subtree_end: wgpu::Buffer,
    pub(super) hir_kind: wgpu::Buffer,
    pub(super) hir_token_pos: wgpu::Buffer,
    pub(super) hir_token_end: wgpu::Buffer,
    pub(super) hir_token_file_id: wgpu::Buffer,
    pub(super) hir_semantic_count: wgpu::Buffer,
    pub(super) hir_semantic_dense_node: wgpu::Buffer,
    pub(super) hir_semantic_parent: wgpu::Buffer,
    pub(super) hir_semantic_prefix_before_node: wgpu::Buffer,
    pub(super) hir_type_form: wgpu::Buffer,
    pub(super) hir_type_value_node: wgpu::Buffer,
    pub(super) hir_type_len_token: wgpu::Buffer,
    pub(super) hir_type_len_value: wgpu::Buffer,
    pub(super) hir_type_path_leaf_node: wgpu::Buffer,
    pub(super) hir_bound_path_owner_by_leaf: wgpu::Buffer,
    pub(super) hir_type_path_leaf_value_a: wgpu::Buffer,
    pub(super) hir_type_arg_start: wgpu::Buffer,
    pub(super) hir_type_arg_count: wgpu::Buffer,
    pub(super) hir_type_arg_next: wgpu::Buffer,
    pub(super) hir_type_arg_rank_b: wgpu::Buffer,
    pub(super) hir_type_arg_previous: wgpu::Buffer,
    pub(super) hir_type_alias_target_node: wgpu::Buffer,
    pub(super) hir_type_alias_owner_link_a: wgpu::Buffer,
    pub(super) hir_type_alias_owner_link_b: wgpu::Buffer,
    pub(super) hir_type_alias_owner_value_a: wgpu::Buffer,
    pub(super) hir_type_alias_owner_value_b: wgpu::Buffer,
    pub(super) hir_fn_return_type_node: wgpu::Buffer,
    pub(super) hir_fn_signature_owner_link_b: wgpu::Buffer,
    pub(super) hir_fn_signature_function_owner_a: wgpu::Buffer,
    pub(super) hir_fn_signature_function_owner_b: wgpu::Buffer,
    pub(super) hir_item_kind: wgpu::Buffer,
    pub(super) hir_item_name_token: wgpu::Buffer,
    pub(super) hir_item_namespace: wgpu::Buffer,
    pub(super) hir_item_visibility: wgpu::Buffer,
    pub(super) hir_item_path_start: wgpu::Buffer,
    pub(super) hir_item_path_end: wgpu::Buffer,
    pub(super) hir_item_file_id: wgpu::Buffer,
    pub(super) hir_item_import_target_kind: wgpu::Buffer,
    pub(super) hir_param_record: wgpu::Buffer,
    pub(super) hir_param_type_node: wgpu::Buffer,
    pub(super) hir_method_owner_node: wgpu::Buffer,
    pub(super) hir_method_impl_node: wgpu::Buffer,
    pub(super) hir_method_name_token: wgpu::Buffer,
    pub(super) hir_method_first_param_token: wgpu::Buffer,
    pub(super) hir_method_receiver_mode: wgpu::Buffer,
    pub(super) hir_method_visibility: wgpu::Buffer,
    pub(super) hir_method_signature_flags: wgpu::Buffer,
    pub(super) hir_method_impl_receiver_type_node: wgpu::Buffer,
    pub(super) hir_stmt_record: wgpu::Buffer,
    pub(super) hir_stmt_scope_end: wgpu::Buffer,
    pub(super) hir_nearest_stmt_node: wgpu::Buffer,
    pub(super) hir_nearest_block_node: wgpu::Buffer,
    pub(super) hir_nearest_loop_node: wgpu::Buffer,
    pub(super) hir_nearest_fn_node: wgpu::Buffer,
    pub(super) hir_expr_record: wgpu::Buffer,
    pub(super) hir_expr_result_node: wgpu::Buffer,
    pub(super) hir_expr_result_root_node: wgpu::Buffer,
    pub(super) hir_expr_int_value: wgpu::Buffer,
    pub(super) hir_member_receiver_node: wgpu::Buffer,
    pub(super) hir_member_receiver_token: wgpu::Buffer,
    pub(super) hir_member_name_token: wgpu::Buffer,
    pub(super) hir_call_callee_node: wgpu::Buffer,
    pub(super) hir_call_context_stmt_node: wgpu::Buffer,
    pub(super) hir_call_arg_start: wgpu::Buffer,
    pub(super) hir_call_arg_end: wgpu::Buffer,
    pub(super) hir_call_arg_count: wgpu::Buffer,
    pub(super) hir_call_arg_parent_call: wgpu::Buffer,
    pub(super) hir_call_arg_ordinal: wgpu::Buffer,
    pub(super) hir_call_arg_owner_a: wgpu::Buffer,
    pub(super) hir_call_arg_owner_b: wgpu::Buffer,
    pub(super) hir_call_arg_link_a: wgpu::Buffer,
    pub(super) hir_call_arg_link_b: wgpu::Buffer,
    pub(super) hir_call_arg_rank_a: wgpu::Buffer,
    pub(super) hir_call_arg_rank_b: wgpu::Buffer,
    pub(super) hir_array_lit_first_element: wgpu::Buffer,
    pub(super) hir_array_lit_element_count: wgpu::Buffer,
    pub(super) hir_array_lit_context_stmt_node: wgpu::Buffer,
    pub(super) hir_array_element_parent_lit: wgpu::Buffer,
    pub(super) hir_array_element_next: wgpu::Buffer,
    pub(super) hir_array_element_previous: wgpu::Buffer,
    pub(super) hir_variant_parent_enum: wgpu::Buffer,
    pub(super) hir_variant_payload_start: wgpu::Buffer,
    pub(super) hir_variant_payload_count: wgpu::Buffer,
    pub(super) hir_variant_payload_node: wgpu::Buffer,
    pub(super) hir_variant_rank_a: wgpu::Buffer,
    pub(super) hir_variant_payload_owner_a: wgpu::Buffer,
    pub(super) hir_variant_payload_owner_b: wgpu::Buffer,
    pub(super) hir_variant_payload_link_a: wgpu::Buffer,
    pub(super) hir_variant_payload_link_b: wgpu::Buffer,
    pub(super) hir_variant_payload_rank_a: wgpu::Buffer,
    pub(super) hir_variant_payload_rank_b: wgpu::Buffer,
    pub(super) hir_match_scrutinee_node: wgpu::Buffer,
    pub(super) hir_match_arm_start: wgpu::Buffer,
    pub(super) hir_match_arm_count: wgpu::Buffer,
    pub(super) hir_match_arm_next: wgpu::Buffer,
    pub(super) hir_match_arm_pattern_node: wgpu::Buffer,
    pub(super) hir_match_arm_payload_start: wgpu::Buffer,
    pub(super) hir_match_arm_payload_count: wgpu::Buffer,
    pub(super) hir_match_arm_result_node: wgpu::Buffer,
    pub(super) hir_match_arm_previous: wgpu::Buffer,
    pub(super) hir_match_payload_owner_arm: wgpu::Buffer,
    pub(super) hir_match_payload_match_node: wgpu::Buffer,
    pub(super) hir_match_payload_ordinal: wgpu::Buffer,
    pub(super) hir_match_rank_node: wgpu::Buffer,
    pub(super) hir_match_rank_local_prefix: wgpu::Buffer,
    pub(super) hir_struct_field_parent_struct: wgpu::Buffer,
    pub(super) hir_struct_field_ordinal: wgpu::Buffer,
    pub(super) hir_struct_field_type_node: wgpu::Buffer,
    pub(super) hir_struct_decl_field_start: wgpu::Buffer,
    pub(super) hir_struct_decl_field_count: wgpu::Buffer,
    pub(super) hir_struct_lit_head_node: wgpu::Buffer,
    pub(super) hir_struct_lit_context_stmt_node: wgpu::Buffer,
    pub(super) hir_struct_lit_field_start: wgpu::Buffer,
    pub(super) hir_struct_lit_field_count: wgpu::Buffer,
    pub(super) hir_struct_lit_field_parent_lit: wgpu::Buffer,
    pub(super) hir_struct_lit_field_value_node: wgpu::Buffer,
    pub(super) hir_list_rank_flag: wgpu::Buffer,
    pub(super) hir_list_rank_node: wgpu::Buffer,
    pub(super) hir_list_rank_local_prefix: wgpu::Buffer,
    pub(super) default_token_file_id: wgpu::Buffer,
    pub(super) out_headers: wgpu::Buffer,
    pub(super) semantic_token_kinds: wgpu::Buffer,
    pub(super) token_brace_semantic_kind: wgpu::Buffer,
    pub(super) token_bracket_semantic_kind: wgpu::Buffer,
    pub(super) token_statement_context_kind: wgpu::Buffer,
    pub(super) token_brace_match_depth: wgpu::Buffer,
    pub(super) token_depth_brace_inblock: wgpu::Buffer,
    pub(super) token_depth_bracket_inblock: wgpu::Buffer,
    pub(super) tree_prefix: wgpu::Buffer,
    pub(super) sc_offsets: wgpu::Buffer,
    pub(super) emit_offsets: wgpu::Buffer,
    pub(super) pack_sc_prefix_a: wgpu::Buffer,
    pub(super) pack_sc_prefix_b: wgpu::Buffer,
    pub(super) pack_emit_prefix_a: wgpu::Buffer,
    pub(super) pack_emit_prefix_b: wgpu::Buffer,
    pub(super) match_for_index: wgpu::Buffer,
}

impl OwnedTypecheckParserBuffers {
    pub(super) fn from_parser_buffers(bufs: &ParserBuffers) -> Self {
        Self {
            ll1_status: bufs.ll1_status.buffer.clone(),
            node_kind: bufs.node_kind.buffer.clone(),
            parent: bufs.parent.buffer.clone(),
            first_child: bufs.first_child.buffer.clone(),
            next_sibling: bufs.next_sibling.buffer.clone(),
            subtree_end: bufs.subtree_end.buffer.clone(),
            hir_kind: bufs.hir_kind.buffer.clone(),
            hir_token_pos: bufs.hir_token_pos.buffer.clone(),
            hir_token_end: bufs.hir_token_end.buffer.clone(),
            hir_token_file_id: bufs.hir_token_file_id.buffer.clone(),
            hir_semantic_count: bufs.hir_semantic_count.buffer.clone(),
            hir_semantic_dense_node: bufs.hir_semantic_dense_node.buffer.clone(),
            hir_semantic_parent: bufs.hir_semantic_parent.buffer.clone(),
            hir_semantic_prefix_before_node: bufs.hir_semantic_prefix_before_node.buffer.clone(),
            hir_type_form: bufs.hir_type_form.buffer.clone(),
            hir_type_value_node: bufs.hir_type_value_node.buffer.clone(),
            hir_type_len_token: bufs.hir_type_len_token.buffer.clone(),
            hir_type_len_value: bufs.hir_type_len_value.buffer.clone(),
            hir_type_path_leaf_node: bufs.hir_type_path_leaf_node.buffer.clone(),
            hir_bound_path_owner_by_leaf: bufs.hir_bound_path_owner_by_leaf.buffer.clone(),
            hir_type_path_leaf_value_a: bufs.hir_type_path_leaf_value_a.buffer.clone(),
            hir_type_arg_start: bufs.hir_type_arg_start.buffer.clone(),
            hir_type_arg_count: bufs.hir_type_arg_count.buffer.clone(),
            hir_type_arg_next: bufs.hir_type_arg_next.buffer.clone(),
            hir_type_arg_rank_b: bufs.hir_type_arg_rank_b.buffer.clone(),
            hir_type_arg_previous: bufs.hir_type_arg_previous.buffer.clone(),
            hir_type_alias_target_node: bufs.hir_type_alias_target_node.buffer.clone(),
            hir_type_alias_owner_link_a: bufs.hir_type_alias_owner_link_a.buffer.clone(),
            hir_type_alias_owner_link_b: bufs.hir_type_alias_owner_link_b.buffer.clone(),
            hir_type_alias_owner_value_a: bufs.hir_type_alias_owner_value_a.buffer.clone(),
            hir_type_alias_owner_value_b: bufs.hir_type_alias_owner_value_b.buffer.clone(),
            hir_fn_return_type_node: bufs.hir_fn_return_type_node.buffer.clone(),
            hir_fn_signature_owner_link_b: bufs.hir_fn_signature_owner_link_b.buffer.clone(),
            hir_fn_signature_function_owner_a: bufs
                .hir_fn_signature_function_owner_a
                .buffer
                .clone(),
            hir_fn_signature_function_owner_b: bufs
                .hir_fn_signature_function_owner_b
                .buffer
                .clone(),
            hir_item_kind: bufs.hir_item_kind.buffer.clone(),
            hir_item_name_token: bufs.hir_item_name_token.buffer.clone(),
            hir_item_namespace: bufs.hir_item_namespace.buffer.clone(),
            hir_item_visibility: bufs.hir_item_visibility.buffer.clone(),
            hir_item_path_start: bufs.hir_item_path_start.buffer.clone(),
            hir_item_path_end: bufs.hir_item_path_end.buffer.clone(),
            hir_item_file_id: bufs.hir_item_file_id.buffer.clone(),
            hir_item_import_target_kind: bufs.hir_item_import_target_kind.buffer.clone(),
            hir_param_record: bufs.hir_param_record.buffer.clone(),
            hir_param_type_node: bufs.hir_param_type_node.buffer.clone(),
            hir_method_owner_node: bufs.hir_method_owner_node.buffer.clone(),
            hir_method_impl_node: bufs.hir_method_impl_node.buffer.clone(),
            hir_method_name_token: bufs.hir_method_name_token.buffer.clone(),
            hir_method_first_param_token: bufs.hir_method_first_param_token.buffer.clone(),
            hir_method_receiver_mode: bufs.hir_method_receiver_mode.buffer.clone(),
            hir_method_visibility: bufs.hir_method_visibility.buffer.clone(),
            hir_method_signature_flags: bufs.hir_method_signature_flags.buffer.clone(),
            hir_method_impl_receiver_type_node: bufs
                .hir_method_impl_receiver_type_node
                .buffer
                .clone(),
            hir_stmt_record: bufs.hir_stmt_record.buffer.clone(),
            hir_stmt_scope_end: bufs.hir_stmt_scope_end.buffer.clone(),
            hir_nearest_stmt_node: bufs.hir_nearest_stmt_node.buffer.clone(),
            hir_nearest_block_node: bufs.hir_nearest_block_node.buffer.clone(),
            hir_nearest_loop_node: bufs.hir_nearest_loop_node.buffer.clone(),
            hir_nearest_fn_node: bufs.hir_nearest_fn_node.buffer.clone(),
            hir_expr_record: bufs.hir_expr_record.buffer.clone(),
            hir_expr_result_node: bufs.hir_expr_result_node.buffer.clone(),
            hir_expr_result_root_node: bufs.hir_expr_result_root_node.buffer.clone(),
            hir_expr_int_value: bufs.hir_expr_int_value.buffer.clone(),
            hir_member_receiver_node: bufs.hir_member_receiver_node.buffer.clone(),
            hir_member_receiver_token: bufs.hir_member_receiver_token.buffer.clone(),
            hir_member_name_token: bufs.hir_member_name_token.buffer.clone(),
            hir_call_callee_node: bufs.hir_call_callee_node.buffer.clone(),
            hir_call_context_stmt_node: bufs.hir_call_context_stmt_node.buffer.clone(),
            hir_call_arg_start: bufs.hir_call_arg_start.buffer.clone(),
            hir_call_arg_end: bufs.hir_call_arg_end.buffer.clone(),
            hir_call_arg_count: bufs.hir_call_arg_count.buffer.clone(),
            hir_call_arg_parent_call: bufs.hir_call_arg_parent_call.buffer.clone(),
            hir_call_arg_ordinal: bufs.hir_call_arg_ordinal.buffer.clone(),
            hir_call_arg_owner_a: bufs.hir_call_arg_owner_a.buffer.clone(),
            hir_call_arg_owner_b: bufs.hir_call_arg_owner_b.buffer.clone(),
            hir_call_arg_link_a: bufs.hir_call_arg_link_a.buffer.clone(),
            hir_call_arg_link_b: bufs.hir_call_arg_link_b.buffer.clone(),
            hir_call_arg_rank_a: bufs.hir_call_arg_rank_a.buffer.clone(),
            hir_call_arg_rank_b: bufs.hir_call_arg_rank_b.buffer.clone(),
            hir_array_lit_first_element: bufs.hir_array_lit_first_element.buffer.clone(),
            hir_array_lit_element_count: bufs.hir_array_lit_element_count.buffer.clone(),
            hir_array_lit_context_stmt_node: bufs.hir_array_lit_context_stmt_node.buffer.clone(),
            hir_array_element_parent_lit: bufs.hir_array_element_parent_lit.buffer.clone(),
            hir_array_element_next: bufs.hir_array_element_next.buffer.clone(),
            hir_array_element_previous: bufs.hir_array_element_previous.buffer.clone(),
            hir_variant_parent_enum: bufs.hir_variant_parent_enum.buffer.clone(),
            hir_variant_payload_start: bufs.hir_variant_payload_start.buffer.clone(),
            hir_variant_payload_count: bufs.hir_variant_payload_count.buffer.clone(),
            hir_variant_payload_node: bufs.hir_variant_payload_node.buffer.clone(),
            hir_variant_rank_a: bufs.hir_variant_rank_a.buffer.clone(),
            hir_variant_payload_owner_a: bufs.hir_variant_payload_owner_a.buffer.clone(),
            hir_variant_payload_owner_b: bufs.hir_variant_payload_owner_b.buffer.clone(),
            hir_variant_payload_link_a: bufs.hir_variant_payload_link_a.buffer.clone(),
            hir_variant_payload_link_b: bufs.hir_variant_payload_link_b.buffer.clone(),
            hir_variant_payload_rank_a: bufs.hir_variant_payload_rank_a.buffer.clone(),
            hir_variant_payload_rank_b: bufs.hir_variant_payload_rank_b.buffer.clone(),
            hir_match_scrutinee_node: bufs.hir_match_scrutinee_node.buffer.clone(),
            hir_match_arm_start: bufs.hir_match_arm_start.buffer.clone(),
            hir_match_arm_count: bufs.hir_match_arm_count.buffer.clone(),
            hir_match_arm_next: bufs.hir_match_arm_next.buffer.clone(),
            hir_match_arm_pattern_node: bufs.hir_match_arm_pattern_node.buffer.clone(),
            hir_match_arm_payload_start: bufs.hir_match_arm_payload_start.buffer.clone(),
            hir_match_arm_payload_count: bufs.hir_match_arm_payload_count.buffer.clone(),
            hir_match_arm_result_node: bufs.hir_match_arm_result_node.buffer.clone(),
            hir_match_arm_previous: bufs.hir_match_arm_previous.buffer.clone(),
            hir_match_payload_owner_arm: bufs.hir_match_payload_owner_arm.buffer.clone(),
            hir_match_payload_match_node: bufs.hir_match_payload_match_node.buffer.clone(),
            hir_match_payload_ordinal: bufs.hir_match_payload_ordinal.buffer.clone(),
            hir_match_rank_node: bufs.hir_match_rank_node.buffer.clone(),
            hir_match_rank_local_prefix: bufs.hir_match_rank_local_prefix.buffer.clone(),
            hir_struct_field_parent_struct: bufs.hir_struct_field_parent_struct.buffer.clone(),
            hir_struct_field_ordinal: bufs.hir_struct_field_ordinal.buffer.clone(),
            hir_struct_field_type_node: bufs.hir_struct_field_type_node.buffer.clone(),
            hir_struct_decl_field_start: bufs.hir_struct_decl_field_start.buffer.clone(),
            hir_struct_decl_field_count: bufs.hir_struct_decl_field_count.buffer.clone(),
            hir_struct_lit_head_node: bufs.hir_struct_lit_head_node.buffer.clone(),
            hir_struct_lit_context_stmt_node: bufs.hir_struct_lit_context_stmt_node.buffer.clone(),
            hir_struct_lit_field_start: bufs.hir_struct_lit_field_start.buffer.clone(),
            hir_struct_lit_field_count: bufs.hir_struct_lit_field_count.buffer.clone(),
            hir_struct_lit_field_parent_lit: bufs.hir_struct_lit_field_parent_lit.buffer.clone(),
            hir_struct_lit_field_value_node: bufs.hir_struct_lit_field_value_node.buffer.clone(),
            hir_list_rank_flag: bufs.hir_list_rank_flag.buffer.clone(),
            hir_list_rank_node: bufs.hir_list_rank_node.buffer.clone(),
            hir_list_rank_local_prefix: bufs.hir_list_rank_local_prefix.buffer.clone(),
            default_token_file_id: bufs.default_token_file_id.buffer.clone(),
            out_headers: bufs.out_headers.buffer.clone(),
            semantic_token_kinds: bufs.semantic_token_kinds.buffer.clone(),
            token_brace_semantic_kind: bufs.token_brace_semantic_kind.buffer.clone(),
            token_bracket_semantic_kind: bufs.token_bracket_semantic_kind.buffer.clone(),
            token_statement_context_kind: bufs.token_statement_context_kind.buffer.clone(),
            token_brace_match_depth: bufs.token_brace_match_depth.buffer.clone(),
            token_depth_brace_inblock: bufs.token_depth_brace_inblock.buffer.clone(),
            token_depth_bracket_inblock: bufs.token_depth_bracket_inblock.buffer.clone(),
            tree_prefix: bufs.tree_prefix.buffer.clone(),
            sc_offsets: bufs.sc_offsets.buffer.clone(),
            emit_offsets: bufs.emit_offsets.buffer.clone(),
            pack_sc_prefix_a: bufs.pack_sc_prefix_a.buffer.clone(),
            pack_sc_prefix_b: bufs.pack_sc_prefix_b.buffer.clone(),
            pack_emit_prefix_a: bufs.pack_emit_prefix_a.buffer.clone(),
            pack_emit_prefix_b: bufs.pack_emit_prefix_b.buffer.clone(),
            match_for_index: bufs.match_for_index.buffer.clone(),
        }
    }

    pub(super) fn hir_item_buffers(&self) -> gpu_type_checker::GpuTypeCheckHirItemBuffers<'_> {
        gpu_type_checker::GpuTypeCheckHirItemBuffers {
            node_kind: &self.node_kind,
            parent: &self.parent,
            first_child: &self.first_child,
            next_sibling: &self.next_sibling,
            subtree_end: &self.subtree_end,
            kind: &self.hir_item_kind,
            name_token: &self.hir_item_name_token,
            type_form: &self.hir_type_form,
            type_value_node: &self.hir_type_value_node,
            type_len_token: &self.hir_type_len_token,
            type_len_value: &self.hir_type_len_value,
            type_path_leaf_node: &self.hir_type_path_leaf_node,
            bound_path_owner_by_leaf: &self.hir_bound_path_owner_by_leaf,
            type_arg_start: &self.hir_type_arg_start,
            type_arg_count: &self.hir_type_arg_count,
            type_arg_next: &self.hir_type_arg_next,
            type_alias_target_node: &self.hir_type_alias_target_node,
            fn_return_type_node: &self.hir_fn_return_type_node,
            param_record: &self.hir_param_record,
            param_type_node: &self.hir_param_type_node,
            method_owner_node: &self.hir_method_owner_node,
            method_impl_node: &self.hir_method_impl_node,
            method_name_token: &self.hir_method_name_token,
            method_first_param_token: &self.hir_method_first_param_token,
            method_receiver_mode: &self.hir_method_receiver_mode,
            method_visibility: &self.hir_method_visibility,
            method_signature_flags: &self.hir_method_signature_flags,
            method_impl_receiver_type_node: &self.hir_method_impl_receiver_type_node,
            expr_record: &self.hir_expr_record,
            expr_result_node: &self.hir_expr_result_node,
            expr_result_root_node: &self.hir_expr_result_root_node,
            expr_int_value: &self.hir_expr_int_value,
            member_receiver_node: &self.hir_member_receiver_node,
            member_receiver_token: &self.hir_member_receiver_token,
            member_name_token: &self.hir_member_name_token,
            stmt_record: &self.hir_stmt_record,
            stmt_scope_end: &self.hir_stmt_scope_end,
            nearest_stmt_node: &self.hir_nearest_stmt_node,
            nearest_block_node: &self.hir_nearest_block_node,
            nearest_loop_node: &self.hir_nearest_loop_node,
            nearest_fn_node: &self.hir_nearest_fn_node,
            array_lit_first_element: &self.hir_array_lit_first_element,
            array_lit_element_count: &self.hir_array_lit_element_count,
            array_lit_context_stmt_node: &self.hir_array_lit_context_stmt_node,
            array_element_parent_lit: &self.hir_array_element_parent_lit,
            array_element_next: &self.hir_array_element_next,
            namespace: &self.hir_item_namespace,
            visibility: &self.hir_item_visibility,
            path_start: &self.hir_item_path_start,
            path_end: &self.hir_item_path_end,
            file_id: &self.hir_item_file_id,
            import_target_kind: &self.hir_item_import_target_kind,
            call_callee_node: &self.hir_call_callee_node,
            call_context_stmt_node: &self.hir_call_context_stmt_node,
            call_arg_start: &self.hir_call_arg_start,
            call_arg_end: &self.hir_call_arg_end,
            call_arg_count: &self.hir_call_arg_count,
            call_arg_parent_call: &self.hir_call_arg_parent_call,
            call_arg_ordinal: &self.hir_call_arg_ordinal,
            variant_parent_enum: &self.hir_variant_parent_enum,
            variant_payload_start: &self.hir_variant_payload_start,
            variant_payload_count: &self.hir_variant_payload_count,
            variant_payload_node: &self.hir_variant_payload_node,
            match_scrutinee_node: &self.hir_match_scrutinee_node,
            match_arm_start: &self.hir_match_arm_start,
            match_arm_count: &self.hir_match_arm_count,
            match_arm_next: &self.hir_match_arm_next,
            match_arm_pattern_node: &self.hir_match_arm_pattern_node,
            match_arm_payload_start: &self.hir_match_arm_payload_start,
            match_arm_payload_count: &self.hir_match_arm_payload_count,
            match_arm_result_node: &self.hir_match_arm_result_node,
            match_payload_owner_arm: &self.hir_match_payload_owner_arm,
            match_payload_match_node: &self.hir_match_payload_match_node,
            match_payload_ordinal: &self.hir_match_payload_ordinal,
            struct_field_parent_struct: &self.hir_struct_field_parent_struct,
            struct_field_ordinal: &self.hir_struct_field_ordinal,
            struct_field_type_node: &self.hir_struct_field_type_node,
            struct_decl_field_start: &self.hir_struct_decl_field_start,
            struct_decl_field_count: &self.hir_struct_decl_field_count,
            struct_lit_head_node: &self.hir_struct_lit_head_node,
            struct_lit_context_stmt_node: &self.hir_struct_lit_context_stmt_node,
            struct_lit_field_start: &self.hir_struct_lit_field_start,
            struct_lit_field_count: &self.hir_struct_lit_field_count,
            struct_lit_field_parent_lit: &self.hir_struct_lit_field_parent_lit,
            struct_lit_field_value_node: &self.hir_struct_lit_field_value_node,
            semantic_dense_node: &self.hir_semantic_dense_node,
            semantic_count: &self.hir_semantic_count,
        }
    }
}
