import Lanius.Extraction.VerifiedFrontend.Artifact.Number.Artifact
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_canonical verifiedFrontendNumber_token_canonical_trace_checked_kernel for verifiedFrontendNumberArtifact
end Lanius.Extraction
