import Lanius.Extraction.VerifiedFrontend.Surface.Number.Claims.Assembly
import Lanius.Extraction.VerifiedFrontend.Surface.Number.Origins.Trace
import Lanius.Extraction.VerifiedFrontend.Surface.Number.Decode.Assembly
namespace Lanius.Extraction
set_option maxRecDepth 500000
def verifiedFrontendNumberReconstructionKernel : ProvenanceSurfaceReconstruction := {
  reconstructed := verifiedFrontendNumberReconstructedKernel
  claims := verifiedFrontendNumberClaimsKernel
  origins := verifiedFrontendNumberOrigins
}
theorem verifiedFrontendNumber_reconstruction_found_kernel :
    reconstructArtifactSurfaceWithProvenanceView verifiedFrontendNumberArtifact verifiedFrontendNumberView
      verifiedFrontendNumberOrigins = some verifiedFrontendNumberReconstructionKernel :=
  reconstructArtifactSurfaceWithProvenanceView_of_components verifiedFrontendNumberView
    verifiedFrontendNumberOrigins verifiedFrontendNumberReconstructedKernel verifiedFrontendNumberClaimsKernel
    verifiedFrontendNumber_reconstructed_found_kernel verifiedFrontendNumber_claims_found_kernel
def verifiedFrontendNumberSurfaceKernel : CheckedSurfaceArtifact verifiedFrontendNumberArtifact :=
  CheckedSurfaceArtifact.ofOriginsWithParse verifiedFrontendNumberView verifiedFrontendNumberOrigins
    verifiedFrontendNumberParseValidTraceKernel verifiedFrontendNumberReconstructionKernel
    verifiedFrontendNumber_reconstruction_found_kernel verifiedFrontendNumberDecodedSurfaceKernel
    verifiedFrontendNumber_decoded_surface_found_kernel verifiedFrontendNumber_claims_equal_kernel
    verifiedFrontendNumber_origins_checked_kernel
theorem verifiedFrontendNumber_surface_checked_kernel : SurfaceArtifactValid verifiedFrontendNumberArtifact :=
  CheckedSurfaceArtifact.valid verifiedFrontendNumberSurfaceKernel
end Lanius.Extraction
