use super::*;
use crate::gpu::buffers::LaniusBuffer;

/// Owned parser buffers retained for x86 codegen after parser driver scopes end.
pub(super) struct OwnedX86ParserBuffers {
    pub(super) ll1_status: LaniusBuffer<u32>,
    pub(super) tree_active_dispatch_args: LaniusBuffer<u32>,
    pub(super) tree_pointer_jump_dispatch_args: LaniusBuffer<u32>,
    pub(super) hir_kind: LaniusBuffer<u32>,
    pub(super) parent: LaniusBuffer<u32>,
    pub(super) subtree_end: LaniusBuffer<u32>,
    pub(super) hir_item_kind: LaniusBuffer<u32>,
    pub(super) hir_item_decl_token: LaniusBuffer<u32>,
    pub(super) hir_item_name_token: LaniusBuffer<u32>,
    pub(super) hir_item_namespace: LaniusBuffer<u32>,
    pub(super) hir_item_visibility: LaniusBuffer<u32>,
    pub(super) hir_item_path_start: LaniusBuffer<u32>,
    pub(super) hir_token_pos: LaniusBuffer<u32>,
    pub(super) hir_type_form: LaniusBuffer<u32>,
    pub(super) hir_type_value_node: LaniusBuffer<u32>,
    pub(super) hir_type_len_token: LaniusBuffer<u32>,
    pub(super) hir_type_len_value: LaniusBuffer<u32>,
    pub(super) hir_type_path_leaf_node: LaniusBuffer<u32>,
    pub(super) hir_type_path_leaf_link_a: LaniusBuffer<u32>,
    pub(super) hir_type_path_leaf_link_b: LaniusBuffer<u32>,
    pub(super) hir_type_arg_start: LaniusBuffer<u32>,
    pub(super) hir_type_arg_count: LaniusBuffer<u32>,
    pub(super) hir_type_arg_next: LaniusBuffer<u32>,
    pub(super) hir_type_arg_rank_a: LaniusBuffer<u32>,
    pub(super) hir_type_alias_target_node: LaniusBuffer<u32>,
    pub(super) hir_fn_return_type_node: LaniusBuffer<u32>,
    pub(super) hir_nearest_fn_node: LaniusBuffer<u32>,
    pub(super) hir_semantic_dense_node: LaniusBuffer<u32>,
    pub(super) hir_param_record: LaniusBuffer<u32>,
    pub(super) hir_stmt_record: LaniusBuffer<u32>,
    pub(super) hir_nearest_loop_node: LaniusBuffer<u32>,
    pub(super) hir_expr_record: LaniusBuffer<u32>,
    pub(super) hir_expr_result_root_node: LaniusBuffer<u32>,
    pub(super) hir_expr_int_value: LaniusBuffer<u32>,
    pub(super) hir_expr_float_bits: LaniusBuffer<u32>,
    pub(super) hir_expr_string_start: LaniusBuffer<u32>,
    pub(super) hir_expr_string_len: LaniusBuffer<u32>,
    pub(super) hir_string_data_offset: LaniusBuffer<u32>,
    pub(super) hir_string_decoded_len: LaniusBuffer<u32>,
    pub(super) hir_string_data_words: LaniusBuffer<u32>,
    pub(super) hir_string_node: LaniusBuffer<u32>,
    pub(super) hir_string_count: LaniusBuffer<u32>,
    pub(super) hir_member_receiver_node: LaniusBuffer<u32>,
    pub(super) hir_member_name_token: LaniusBuffer<u32>,
    pub(super) hir_call_callee_node: LaniusBuffer<u32>,
    pub(super) hir_call_context_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_call_arg_start: LaniusBuffer<u32>,
    pub(super) hir_call_arg_end: LaniusBuffer<u32>,
    pub(super) hir_call_arg_count: LaniusBuffer<u32>,
    pub(super) hir_call_arg_parent_call: LaniusBuffer<u32>,
    pub(super) hir_call_arg_ordinal: LaniusBuffer<u32>,
    pub(super) hir_array_lit_first_element: LaniusBuffer<u32>,
    pub(super) hir_array_lit_element_count: LaniusBuffer<u32>,
    pub(super) hir_array_element_parent_lit: LaniusBuffer<u32>,
    pub(super) hir_array_element_ordinal: LaniusBuffer<u32>,
    pub(super) hir_array_element_next: LaniusBuffer<u32>,
    pub(super) hir_nearest_array_element_node: LaniusBuffer<u32>,
    pub(super) hir_array_element_previous: LaniusBuffer<u32>,
    pub(super) hir_variant_parent_enum: LaniusBuffer<u32>,
    pub(super) hir_variant_ordinal: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_count: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_owner_a: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_owner_b: LaniusBuffer<u32>,
    pub(super) hir_match_scrutinee_node: LaniusBuffer<u32>,
    pub(super) hir_match_arm_start: LaniusBuffer<u32>,
    pub(super) hir_match_arm_count: LaniusBuffer<u32>,
    pub(super) hir_match_arm_next: LaniusBuffer<u32>,
    pub(super) hir_match_arm_pattern_node: LaniusBuffer<u32>,
    pub(super) hir_match_arm_payload_start: LaniusBuffer<u32>,
    pub(super) hir_match_arm_payload_count: LaniusBuffer<u32>,
    pub(super) hir_match_arm_result_node: LaniusBuffer<u32>,
    pub(super) hir_struct_field_parent_struct: LaniusBuffer<u32>,
    pub(super) hir_struct_field_ordinal: LaniusBuffer<u32>,
    pub(super) hir_struct_field_type_node: LaniusBuffer<u32>,
    pub(super) hir_struct_decl_field_start: LaniusBuffer<u32>,
    pub(super) hir_struct_decl_field_count: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_head_node: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_context_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_parent_lit: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_start: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_count: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_value_node: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_next: LaniusBuffer<u32>,
}

/// Owned lexer buffers retained for x86 diagnostic mapping.
pub(super) struct OwnedX86DiagnosticBuffers {
    pub(super) source_len: u32,
    pub(super) tokens_out: LaniusBuffer<crate::lexer::GpuToken>,
}

impl OwnedX86DiagnosticBuffers {
    /// Clones the lexer buffers needed by x86 diagnostics.
    pub(super) fn from_lexer_buffers(bufs: &LexerBuffers) -> Self {
        Self {
            source_len: bufs.n,
            tokens_out: bufs.tokens_out.clone(),
        }
    }
}

impl OwnedX86ParserBuffers {
    /// Clones parser buffers needed by x86 codegen.
    pub(super) fn from_parser_buffers(bufs: &ParserBuffers) -> Self {
        Self {
            ll1_status: bufs.ll1_status.clone(),
            tree_active_dispatch_args: bufs.tree_active_dispatch_args.clone(),
            tree_pointer_jump_dispatch_args: bufs.tree_pointer_jump_dispatch_args.clone(),
            hir_kind: bufs.hir_kind.clone(),
            parent: bufs.parent.clone(),
            subtree_end: bufs.subtree_end.clone(),
            hir_item_kind: bufs.hir_item_kind.clone(),
            hir_item_decl_token: bufs.hir_item_decl_token.clone(),
            hir_item_name_token: bufs.hir_item_name_token.clone(),
            hir_item_namespace: bufs.hir_item_namespace.clone(),
            hir_item_visibility: bufs.hir_item_visibility.clone(),
            hir_item_path_start: bufs.hir_item_path_start.clone(),
            hir_token_pos: bufs.hir_token_pos.clone(),
            hir_type_form: bufs.hir_type_form.clone(),
            hir_type_value_node: bufs.hir_type_value_node.clone(),
            hir_type_len_token: bufs.hir_type_len_token.clone(),
            hir_type_len_value: bufs.hir_type_len_value.clone(),
            hir_type_path_leaf_node: bufs.hir_type_path_leaf_node.clone(),
            hir_type_path_leaf_link_a: bufs.hir_type_path_leaf_link_a.clone(),
            hir_type_path_leaf_link_b: bufs.hir_type_path_leaf_link_b.clone(),
            hir_type_arg_start: bufs.hir_type_arg_start.clone(),
            hir_type_arg_count: bufs.hir_type_arg_count.clone(),
            hir_type_arg_next: bufs.hir_type_arg_next.clone(),
            hir_type_arg_rank_a: bufs.hir_type_arg_rank_a.clone(),
            hir_type_alias_target_node: bufs.hir_type_alias_target_node.clone(),
            hir_fn_return_type_node: bufs.hir_fn_return_type_node.clone(),
            hir_nearest_fn_node: bufs.hir_nearest_fn_node.clone(),
            hir_semantic_dense_node: bufs.hir_semantic_dense_node.clone(),
            hir_param_record: bufs.hir_param_record.clone(),
            hir_stmt_record: bufs.hir_stmt_record.clone(),
            hir_nearest_loop_node: bufs.hir_nearest_loop_node.clone(),
            hir_expr_record: bufs.hir_expr_record.clone(),
            hir_expr_result_root_node: bufs.hir_expr_result_root_node.clone(),
            hir_expr_int_value: bufs.hir_expr_int_value.clone(),
            hir_expr_float_bits: bufs.hir_expr_float_bits.clone(),
            hir_expr_string_start: bufs.hir_expr_string_start.clone(),
            hir_expr_string_len: bufs.hir_expr_string_len.clone(),
            hir_string_data_offset: bufs.hir_string_data_offset.clone(),
            hir_string_decoded_len: bufs.hir_string_decoded_len.clone(),
            hir_string_data_words: bufs.hir_string_data_words.clone(),
            hir_string_node: bufs.hir_string_node.clone(),
            hir_string_count: bufs.hir_string_count.clone(),
            hir_member_receiver_node: bufs.hir_member_receiver_node.clone(),
            hir_member_name_token: bufs.hir_member_name_token.clone(),
            hir_call_callee_node: bufs.hir_call_callee_node.clone(),
            hir_call_context_stmt_node: bufs.hir_call_context_stmt_node.clone(),
            hir_call_arg_start: bufs.hir_call_arg_start.clone(),
            hir_call_arg_end: bufs.hir_call_arg_end.clone(),
            hir_call_arg_count: bufs.hir_call_arg_count.clone(),
            hir_call_arg_parent_call: bufs.hir_call_arg_parent_call.clone(),
            hir_call_arg_ordinal: bufs.hir_call_arg_ordinal.clone(),
            hir_array_lit_first_element: bufs.hir_array_lit_first_element.clone(),
            hir_array_lit_element_count: bufs.hir_array_lit_element_count.clone(),
            hir_array_element_parent_lit: bufs.hir_array_element_parent_lit.clone(),
            hir_array_element_ordinal: bufs.hir_array_element_ordinal.clone(),
            hir_array_element_next: bufs.hir_array_element_next.clone(),
            hir_nearest_array_element_node: bufs.hir_nearest_array_element_node.clone(),
            hir_array_element_previous: bufs.hir_array_element_previous.clone(),
            hir_variant_parent_enum: bufs.hir_variant_parent_enum.clone(),
            hir_variant_ordinal: bufs.hir_variant_ordinal.clone(),
            hir_variant_payload_count: bufs.hir_variant_payload_count.clone(),
            hir_variant_payload_owner_a: bufs.hir_variant_payload_owner_a.clone(),
            hir_variant_payload_owner_b: bufs.hir_variant_payload_owner_b.clone(),
            hir_match_scrutinee_node: bufs.hir_match_scrutinee_node.clone(),
            hir_match_arm_start: bufs.hir_match_arm_start.clone(),
            hir_match_arm_count: bufs.hir_match_arm_count.clone(),
            hir_match_arm_next: bufs.hir_match_arm_next.clone(),
            hir_match_arm_pattern_node: bufs.hir_match_arm_pattern_node.clone(),
            hir_match_arm_payload_start: bufs.hir_match_arm_payload_start.clone(),
            hir_match_arm_payload_count: bufs.hir_match_arm_payload_count.clone(),
            hir_match_arm_result_node: bufs.hir_match_arm_result_node.clone(),
            hir_struct_field_parent_struct: bufs.hir_struct_field_parent_struct.clone(),
            hir_struct_field_ordinal: bufs.hir_struct_field_ordinal.clone(),
            hir_struct_field_type_node: bufs.hir_struct_field_type_node.clone(),
            hir_struct_decl_field_start: bufs.hir_struct_decl_field_start.clone(),
            hir_struct_decl_field_count: bufs.hir_struct_decl_field_count.clone(),
            hir_struct_lit_head_node: bufs.hir_struct_lit_head_node.clone(),
            hir_struct_lit_context_stmt_node: bufs.hir_struct_lit_context_stmt_node.clone(),
            hir_struct_lit_field_parent_lit: bufs.hir_struct_lit_field_parent_lit.clone(),
            hir_struct_lit_field_start: bufs.hir_struct_lit_field_start.clone(),
            hir_struct_lit_field_count: bufs.hir_struct_lit_field_count.clone(),
            hir_struct_lit_field_value_node: bufs.hir_struct_lit_field_value_node.clone(),
            hir_struct_lit_field_next: bufs.hir_struct_lit_field_next.clone(),
        }
    }
}

#[allow(dead_code)]
/// Owned parser buffers retained for type-check recording and diagnostics.
pub(super) struct OwnedTypecheckParserBuffers {
    pub(super) parser_feature_flags: u32,
    pub(super) module_record_capacity: u32,
    pub(super) call_param_row_capacity: u32,
    pub(super) call_arg_row_capacity: u32,
    pub(super) ll1_status: LaniusBuffer<u32>,
    pub(super) node_kind: LaniusBuffer<u32>,
    pub(super) parent: LaniusBuffer<u32>,
    pub(super) first_child: LaniusBuffer<u32>,
    pub(super) next_sibling: LaniusBuffer<u32>,
    pub(super) subtree_end: LaniusBuffer<u32>,
    pub(super) hir_kind: LaniusBuffer<u32>,
    pub(super) hir_token_pos: LaniusBuffer<u32>,
    pub(super) hir_token_end: LaniusBuffer<u32>,
    pub(super) hir_token_file_id: LaniusBuffer<u32>,
    pub(super) hir_semantic_count: LaniusBuffer<u32>,
    pub(super) hir_semantic_dense_node: LaniusBuffer<u32>,
    pub(super) hir_semantic_subtree_end: Box<LaniusBuffer<u32>>,
    pub(super) hir_semantic_parent: LaniusBuffer<u32>,
    pub(super) hir_semantic_depth: LaniusBuffer<u32>,
    pub(super) hir_semantic_prefix_before_node: LaniusBuffer<u32>,
    pub(super) hir_type_form: LaniusBuffer<u32>,
    pub(super) hir_type_value_node: LaniusBuffer<u32>,
    pub(super) hir_type_len_token: LaniusBuffer<u32>,
    pub(super) hir_type_len_value: LaniusBuffer<u32>,
    pub(super) hir_type_file_id: LaniusBuffer<u32>,
    pub(super) hir_type_path_leaf_node: LaniusBuffer<u32>,
    pub(super) hir_bound_path_owner_by_leaf: LaniusBuffer<u32>,
    pub(super) hir_path_segment_owner: LaniusBuffer<u32>,
    pub(super) hir_path_segment_rank: LaniusBuffer<u32>,
    pub(super) hir_path_segment_count: LaniusBuffer<u32>,
    pub(super) hir_string_data_offset: LaniusBuffer<u32>,
    pub(super) hir_string_decoded_len: LaniusBuffer<u32>,
    pub(super) hir_string_data_words: LaniusBuffer<u32>,
    pub(super) hir_string_node: LaniusBuffer<u32>,
    pub(super) hir_string_count: LaniusBuffer<u32>,
    pub(super) hir_string_pool_len: LaniusBuffer<u32>,
    pub(super) hir_type_path_leaf_value_a: LaniusBuffer<u32>,
    pub(super) hir_type_arg_start: LaniusBuffer<u32>,
    pub(super) hir_type_arg_count: LaniusBuffer<u32>,
    pub(super) hir_type_arg_next: LaniusBuffer<u32>,
    pub(super) hir_type_arg_owner_a: LaniusBuffer<u32>,
    pub(super) hir_type_arg_rank_a: LaniusBuffer<u32>,
    pub(super) hir_type_arg_rank_b: LaniusBuffer<u32>,
    pub(super) hir_type_root_owner: LaniusBuffer<u32>,
    pub(super) hir_type_arg_previous: LaniusBuffer<u32>,
    pub(super) hir_type_alias_target_node: LaniusBuffer<u32>,
    pub(super) hir_type_alias_owner_link_a: LaniusBuffer<u32>,
    pub(super) hir_type_alias_owner_link_b: LaniusBuffer<u32>,
    pub(super) hir_type_alias_owner_value_a: LaniusBuffer<u32>,
    pub(super) hir_type_alias_owner_value_b: LaniusBuffer<u32>,
    pub(super) hir_fn_return_type_node: LaniusBuffer<u32>,
    pub(super) hir_fn_signature_owner_link_b: LaniusBuffer<u32>,
    pub(super) hir_fn_signature_function_owner_a: LaniusBuffer<u32>,
    pub(super) hir_fn_signature_function_owner_b: LaniusBuffer<u32>,
    pub(super) hir_item_kind: LaniusBuffer<u32>,
    pub(super) hir_item_name_token: LaniusBuffer<u32>,
    pub(super) hir_item_namespace: LaniusBuffer<u32>,
    pub(super) hir_item_visibility: LaniusBuffer<u32>,
    pub(super) hir_item_path_start: LaniusBuffer<u32>,
    pub(super) hir_item_path_end: LaniusBuffer<u32>,
    pub(super) hir_item_path_node: LaniusBuffer<u32>,
    pub(super) hir_item_file_id: LaniusBuffer<u32>,
    pub(super) hir_item_import_target_kind: LaniusBuffer<u32>,
    pub(super) hir_param_record: LaniusBuffer<u32>,
    pub(super) hir_param_type_node: LaniusBuffer<u32>,
    pub(super) hir_method_owner_node: LaniusBuffer<u32>,
    pub(super) hir_method_impl_node: LaniusBuffer<u32>,
    pub(super) hir_method_name_token: LaniusBuffer<u32>,
    pub(super) hir_method_first_param_token: LaniusBuffer<u32>,
    pub(super) hir_method_receiver_mode: LaniusBuffer<u32>,
    pub(super) hir_method_visibility: LaniusBuffer<u32>,
    pub(super) hir_method_signature_flags: LaniusBuffer<u32>,
    pub(super) hir_method_impl_receiver_type_node: LaniusBuffer<u32>,
    pub(super) hir_stmt_record: LaniusBuffer<u32>,
    pub(super) hir_stmt_scope_end: LaniusBuffer<u32>,
    pub(super) hir_nearest_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_nearest_block_node: LaniusBuffer<u32>,
    pub(super) hir_nearest_enclosing_control_node: LaniusBuffer<u32>,
    pub(super) hir_nearest_loop_node: LaniusBuffer<u32>,
    pub(super) hir_nearest_fn_node: LaniusBuffer<u32>,
    pub(super) hir_expr_record: LaniusBuffer<u32>,
    pub(super) hir_expr_name_role: LaniusBuffer<u32>,
    pub(super) hir_expr_result_node: LaniusBuffer<u32>,
    pub(super) hir_expr_result_root_node: LaniusBuffer<u32>,
    pub(super) hir_expr_int_value: LaniusBuffer<u32>,
    pub(super) hir_member_receiver_node: LaniusBuffer<u32>,
    pub(super) hir_member_receiver_token: LaniusBuffer<u32>,
    pub(super) hir_member_name_token: LaniusBuffer<u32>,
    pub(super) hir_call_callee_node: LaniusBuffer<u32>,
    pub(super) hir_call_callee_path_node: LaniusBuffer<u32>,
    pub(super) hir_call_parent_by_callee: LaniusBuffer<u32>,
    pub(super) hir_call_context_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_call_arg_start: LaniusBuffer<u32>,
    pub(super) hir_call_arg_end: LaniusBuffer<u32>,
    pub(super) hir_call_arg_count: LaniusBuffer<u32>,
    pub(super) hir_call_arg_parent_call: LaniusBuffer<u32>,
    pub(super) hir_call_arg_ordinal: LaniusBuffer<u32>,
    pub(super) hir_call_arg_owner_a: LaniusBuffer<u32>,
    pub(super) hir_call_arg_owner_b: LaniusBuffer<u32>,
    pub(super) hir_call_arg_link_a: LaniusBuffer<u32>,
    pub(super) hir_call_arg_link_b: LaniusBuffer<u32>,
    pub(super) hir_call_arg_rank_a: LaniusBuffer<u32>,
    pub(super) hir_call_arg_rank_b: LaniusBuffer<u32>,
    pub(super) hir_array_lit_first_element: LaniusBuffer<u32>,
    pub(super) hir_array_lit_element_count: LaniusBuffer<u32>,
    pub(super) hir_array_lit_context_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_array_element_parent_lit: LaniusBuffer<u32>,
    pub(super) hir_nearest_array_element_node: LaniusBuffer<u32>,
    pub(super) hir_array_element_next: LaniusBuffer<u32>,
    pub(super) hir_array_element_previous: LaniusBuffer<u32>,
    pub(super) hir_variant_parent_enum: LaniusBuffer<u32>,
    pub(super) hir_variant_ordinal: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_start: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_count: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_node: LaniusBuffer<u32>,
    pub(super) hir_variant_rank_a: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_owner_a: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_owner_b: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_link_a: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_link_b: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_rank_a: LaniusBuffer<u32>,
    pub(super) hir_variant_payload_rank_b: LaniusBuffer<u32>,
    pub(super) hir_match_scrutinee_node: LaniusBuffer<u32>,
    pub(super) hir_match_arm_start: LaniusBuffer<u32>,
    pub(super) hir_match_arm_count: LaniusBuffer<u32>,
    pub(super) hir_match_arm_next: LaniusBuffer<u32>,
    pub(super) hir_match_arm_pattern_node: LaniusBuffer<u32>,
    pub(super) hir_match_pattern_owner_arm: LaniusBuffer<u32>,
    pub(super) hir_match_arm_payload_start: LaniusBuffer<u32>,
    pub(super) hir_match_arm_payload_count: LaniusBuffer<u32>,
    pub(super) hir_match_arm_result_node: LaniusBuffer<u32>,
    pub(super) hir_match_arm_previous: LaniusBuffer<u32>,
    pub(super) hir_match_payload_owner_arm: LaniusBuffer<u32>,
    pub(super) hir_match_payload_match_node: LaniusBuffer<u32>,
    pub(super) hir_match_payload_ordinal: LaniusBuffer<u32>,
    pub(super) hir_match_rank_node: LaniusBuffer<u32>,
    pub(super) hir_match_rank_local_prefix: LaniusBuffer<u32>,
    pub(super) hir_match_arm_owner_a: LaniusBuffer<u32>,
    pub(super) hir_struct_field_parent_struct: LaniusBuffer<u32>,
    pub(super) hir_struct_field_ordinal: LaniusBuffer<u32>,
    pub(super) hir_struct_field_type_node: LaniusBuffer<u32>,
    pub(super) hir_struct_decl_field_start: LaniusBuffer<u32>,
    pub(super) hir_struct_decl_field_count: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_head_node: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_context_stmt_node: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_start: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_count: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_parent_lit: LaniusBuffer<u32>,
    pub(super) hir_struct_lit_field_value_node: LaniusBuffer<u32>,
    pub(super) hir_list_rank_flag: LaniusBuffer<u32>,
    pub(super) hir_list_rank_node: LaniusBuffer<u32>,
    pub(super) hir_list_rank_local_prefix: LaniusBuffer<u32>,
    pub(super) default_token_file_id: LaniusBuffer<u32>,
    pub(super) out_headers: LaniusBuffer<crate::parser::buffers::ActionHeader>,
    pub(super) semantic_token_kinds: LaniusBuffer<u32>,
    pub(super) token_brace_semantic_kind: LaniusBuffer<u32>,
    pub(super) token_bracket_semantic_kind: LaniusBuffer<u32>,
    pub(super) token_statement_context_kind: LaniusBuffer<u32>,
    pub(super) token_brace_match_depth: LaniusBuffer<i32>,
    pub(super) token_depth_brace_inblock: LaniusBuffer<i32>,
    pub(super) token_depth_bracket_inblock: LaniusBuffer<i32>,
    pub(super) tree_prefix: LaniusBuffer<i32>,
    pub(super) sc_offsets: LaniusBuffer<u32>,
    pub(super) emit_offsets: LaniusBuffer<u32>,
    pub(super) pack_sc_prefix_a: LaniusBuffer<u32>,
    pub(super) pack_sc_prefix_b: LaniusBuffer<u32>,
    pub(super) pack_emit_prefix_a: LaniusBuffer<u32>,
    pub(super) pack_emit_prefix_b: LaniusBuffer<u32>,
    pub(super) match_for_index: LaniusBuffer<u32>,
}

impl OwnedTypecheckParserBuffers {
    /// Clones parser buffers needed by type-check recording.
    pub(super) fn from_parser_buffers(bufs: &ParserBuffers) -> Self {
        Self {
            parser_feature_flags: bufs.parser_feature_flags,
            module_record_capacity: bufs.tree_capacity,
            call_param_row_capacity: bufs.tree_capacity,
            call_arg_row_capacity: bufs.tree_capacity,
            ll1_status: bufs.ll1_status.clone(),
            node_kind: bufs.node_kind.clone(),
            parent: bufs.parent.clone(),
            first_child: bufs.first_child.clone(),
            next_sibling: bufs.next_sibling.clone(),
            subtree_end: bufs.subtree_end.clone(),
            hir_kind: bufs.hir_kind.clone(),
            hir_token_pos: bufs.hir_token_pos.clone(),
            hir_token_end: bufs.hir_token_end.clone(),
            hir_token_file_id: bufs.hir_token_file_id.clone(),
            hir_semantic_count: bufs.hir_semantic_count.clone(),
            hir_semantic_dense_node: bufs.hir_semantic_dense_node.clone(),
            hir_semantic_subtree_end: Box::new(bufs.hir_semantic_subtree_end.clone()),
            hir_semantic_parent: bufs.hir_semantic_parent.clone(),
            hir_semantic_depth: bufs.hir_semantic_depth.clone(),
            hir_semantic_prefix_before_node: bufs.hir_semantic_prefix_before_node.clone(),
            hir_type_form: bufs.hir_type_form.clone(),
            hir_type_value_node: bufs.hir_type_value_node.clone(),
            hir_type_len_token: bufs.hir_type_len_token.clone(),
            hir_type_len_value: bufs.hir_type_len_value.clone(),
            hir_type_file_id: bufs.hir_type_file_id.clone(),
            hir_type_path_leaf_node: bufs.hir_type_path_leaf_node.clone(),
            hir_bound_path_owner_by_leaf: bufs.hir_bound_path_owner_by_leaf.clone(),
            hir_path_segment_owner: bufs.hir_path_segment_owner_a.clone(),
            hir_path_segment_rank: bufs.hir_path_segment_rank_a.clone(),
            hir_path_segment_count: bufs.hir_path_segment_count.clone(),
            hir_string_data_offset: bufs.hir_string_data_offset.clone(),
            hir_string_decoded_len: bufs.hir_string_decoded_len.clone(),
            hir_string_data_words: bufs.hir_string_data_words.clone(),
            hir_string_node: bufs.hir_string_node.clone(),
            hir_string_count: bufs.hir_string_count.clone(),
            hir_string_pool_len: bufs.hir_string_pool_len.clone(),
            hir_type_path_leaf_value_a: bufs.hir_type_path_leaf_value_a.clone(),
            hir_type_arg_start: bufs.hir_type_arg_start.clone(),
            hir_type_arg_count: bufs.hir_type_arg_count.clone(),
            hir_type_arg_next: bufs.hir_type_arg_next.clone(),
            hir_type_arg_owner_a: bufs.hir_type_arg_owner_a.clone(),
            hir_type_arg_rank_a: bufs.hir_type_arg_rank_a.clone(),
            hir_type_arg_rank_b: bufs.hir_type_arg_rank_b.clone(),
            hir_type_root_owner: bufs.hir_type_root_owner.clone(),
            hir_type_arg_previous: bufs.hir_type_arg_previous.clone(),
            hir_type_alias_target_node: bufs.hir_type_alias_target_node.clone(),
            hir_type_alias_owner_link_a: bufs.hir_type_alias_owner_link_a.clone(),
            hir_type_alias_owner_link_b: bufs.hir_type_alias_owner_link_b.clone(),
            hir_type_alias_owner_value_a: bufs.hir_type_alias_owner_value_a.clone(),
            hir_type_alias_owner_value_b: bufs.hir_type_alias_owner_value_b.clone(),
            hir_fn_return_type_node: bufs.hir_fn_return_type_node.clone(),
            hir_fn_signature_owner_link_b: bufs.hir_fn_signature_owner_link_b.clone(),
            hir_fn_signature_function_owner_a: bufs.hir_fn_signature_function_owner_a.clone(),
            hir_fn_signature_function_owner_b: bufs.hir_fn_signature_function_owner_b.clone(),
            hir_item_kind: bufs.hir_item_kind.clone(),
            hir_item_name_token: bufs.hir_item_name_token.clone(),
            hir_item_namespace: bufs.hir_item_namespace.clone(),
            hir_item_visibility: bufs.hir_item_visibility.clone(),
            hir_item_path_start: bufs.hir_item_path_start.clone(),
            hir_item_path_end: bufs.hir_item_path_end.clone(),
            hir_item_path_node: bufs.hir_item_path_node.clone(),
            hir_item_file_id: bufs.hir_item_file_id.clone(),
            hir_item_import_target_kind: bufs.hir_item_import_target_kind.clone(),
            hir_param_record: bufs.hir_param_record.clone(),
            hir_param_type_node: bufs.hir_param_type_node.clone(),
            hir_method_owner_node: bufs.hir_method_owner_node.clone(),
            hir_method_impl_node: bufs.hir_method_impl_node.clone(),
            hir_method_name_token: bufs.hir_method_name_token.clone(),
            hir_method_first_param_token: bufs.hir_method_first_param_token.clone(),
            hir_method_receiver_mode: bufs.hir_method_receiver_mode.clone(),
            hir_method_visibility: bufs.hir_method_visibility.clone(),
            hir_method_signature_flags: bufs.hir_method_signature_flags.clone(),
            hir_method_impl_receiver_type_node: bufs.hir_method_impl_receiver_type_node.clone(),
            hir_stmt_record: bufs.hir_stmt_record.clone(),
            hir_stmt_scope_end: bufs.hir_stmt_scope_end.clone(),
            hir_nearest_stmt_node: bufs.hir_nearest_stmt_node.clone(),
            hir_nearest_block_node: bufs.hir_nearest_block_node.clone(),
            hir_nearest_enclosing_control_node: bufs.hir_nearest_enclosing_control_node.clone(),
            hir_nearest_loop_node: bufs.hir_nearest_loop_node.clone(),
            hir_nearest_fn_node: bufs.hir_nearest_fn_node.clone(),
            hir_expr_record: bufs.hir_expr_record.clone(),
            hir_expr_name_role: bufs.hir_expr_name_role.clone(),
            hir_expr_result_node: bufs.hir_expr_result_node.clone(),
            hir_expr_result_root_node: bufs.hir_expr_result_root_node.clone(),
            hir_expr_int_value: bufs.hir_expr_int_value.clone(),
            hir_member_receiver_node: bufs.hir_member_receiver_node.clone(),
            hir_member_receiver_token: bufs.hir_member_receiver_token.clone(),
            hir_member_name_token: bufs.hir_member_name_token.clone(),
            hir_call_callee_node: bufs.hir_call_callee_node.clone(),
            hir_call_callee_path_node: bufs.hir_call_callee_path_node.clone(),
            hir_call_parent_by_callee: bufs.hir_call_parent_by_callee.clone(),
            hir_call_context_stmt_node: bufs.hir_call_context_stmt_node.clone(),
            hir_call_arg_start: bufs.hir_call_arg_start.clone(),
            hir_call_arg_end: bufs.hir_call_arg_end.clone(),
            hir_call_arg_count: bufs.hir_call_arg_count.clone(),
            hir_call_arg_parent_call: bufs.hir_call_arg_parent_call.clone(),
            hir_call_arg_ordinal: bufs.hir_call_arg_ordinal.clone(),
            hir_call_arg_owner_a: bufs.hir_call_arg_owner_a.clone(),
            hir_call_arg_owner_b: bufs.hir_call_arg_owner_b.clone(),
            hir_call_arg_link_a: bufs.hir_call_arg_link_a.clone(),
            hir_call_arg_link_b: bufs.hir_call_arg_link_b.clone(),
            hir_call_arg_rank_a: bufs.hir_call_arg_rank_a.clone(),
            hir_call_arg_rank_b: bufs.hir_call_arg_rank_b.clone(),
            hir_array_lit_first_element: bufs.hir_array_lit_first_element.clone(),
            hir_array_lit_element_count: bufs.hir_array_lit_element_count.clone(),
            hir_array_lit_context_stmt_node: bufs.hir_array_lit_context_stmt_node.clone(),
            hir_array_element_parent_lit: bufs.hir_array_element_parent_lit.clone(),
            hir_nearest_array_element_node: bufs.hir_nearest_array_element_node.clone(),
            hir_array_element_next: bufs.hir_array_element_next.clone(),
            hir_array_element_previous: bufs.hir_array_element_previous.clone(),
            hir_variant_parent_enum: bufs.hir_variant_parent_enum.clone(),
            hir_variant_ordinal: bufs.hir_variant_ordinal.clone(),
            hir_variant_payload_start: bufs.hir_variant_payload_start.clone(),
            hir_variant_payload_count: bufs.hir_variant_payload_count.clone(),
            hir_variant_payload_node: bufs.hir_variant_payload_node.clone(),
            hir_variant_rank_a: bufs.hir_variant_rank_a.clone(),
            hir_variant_payload_owner_a: bufs.hir_variant_payload_owner_a.clone(),
            hir_variant_payload_owner_b: bufs.hir_variant_payload_owner_b.clone(),
            hir_variant_payload_link_a: bufs.hir_variant_payload_link_a.clone(),
            hir_variant_payload_link_b: bufs.hir_variant_payload_link_b.clone(),
            hir_variant_payload_rank_a: bufs.hir_variant_payload_rank_a.clone(),
            hir_variant_payload_rank_b: bufs.hir_variant_payload_rank_b.clone(),
            hir_match_scrutinee_node: bufs.hir_match_scrutinee_node.clone(),
            hir_match_arm_start: bufs.hir_match_arm_start.clone(),
            hir_match_arm_count: bufs.hir_match_arm_count.clone(),
            hir_match_arm_next: bufs.hir_match_arm_next.clone(),
            hir_match_arm_pattern_node: bufs.hir_match_arm_pattern_node.clone(),
            hir_match_pattern_owner_arm: bufs.hir_match_pattern_owner_arm.clone(),
            hir_match_arm_payload_start: bufs.hir_match_arm_payload_start.clone(),
            hir_match_arm_payload_count: bufs.hir_match_arm_payload_count.clone(),
            hir_match_arm_result_node: bufs.hir_match_arm_result_node.clone(),
            hir_match_arm_previous: bufs.hir_match_arm_previous.clone(),
            hir_match_payload_owner_arm: bufs.hir_match_payload_owner_arm.clone(),
            hir_match_payload_match_node: bufs.hir_match_payload_match_node.clone(),
            hir_match_payload_ordinal: bufs.hir_match_payload_ordinal.clone(),
            hir_match_rank_node: bufs.hir_match_rank_node.clone(),
            hir_match_rank_local_prefix: bufs.hir_match_rank_local_prefix.clone(),
            hir_match_arm_owner_a: bufs.hir_match_arm_owner_a.clone(),
            hir_struct_field_parent_struct: bufs.hir_struct_field_parent_struct.clone(),
            hir_struct_field_ordinal: bufs.hir_struct_field_ordinal.clone(),
            hir_struct_field_type_node: bufs.hir_struct_field_type_node.clone(),
            hir_struct_decl_field_start: bufs.hir_struct_decl_field_start.clone(),
            hir_struct_decl_field_count: bufs.hir_struct_decl_field_count.clone(),
            hir_struct_lit_head_node: bufs.hir_struct_lit_head_node.clone(),
            hir_struct_lit_context_stmt_node: bufs.hir_struct_lit_context_stmt_node.clone(),
            hir_struct_lit_field_start: bufs.hir_struct_lit_field_start.clone(),
            hir_struct_lit_field_count: bufs.hir_struct_lit_field_count.clone(),
            hir_struct_lit_field_parent_lit: bufs.hir_struct_lit_field_parent_lit.clone(),
            hir_struct_lit_field_value_node: bufs.hir_struct_lit_field_value_node.clone(),
            hir_list_rank_flag: bufs.hir_list_rank_flag.clone(),
            hir_list_rank_node: bufs.hir_list_rank_node.clone(),
            hir_list_rank_local_prefix: bufs.hir_list_rank_local_prefix.clone(),
            default_token_file_id: bufs.default_token_file_id.clone(),
            out_headers: bufs.out_headers.clone(),
            semantic_token_kinds: bufs.semantic_token_kinds.clone(),
            token_brace_semantic_kind: bufs.token_brace_semantic_kind.clone(),
            token_bracket_semantic_kind: bufs.token_bracket_semantic_kind.clone(),
            token_statement_context_kind: bufs.token_statement_context_kind.clone(),
            token_brace_match_depth: bufs.token_brace_match_depth.clone(),
            token_depth_brace_inblock: bufs.token_depth_brace_inblock.clone(),
            token_depth_bracket_inblock: bufs.token_depth_bracket_inblock.clone(),
            tree_prefix: bufs.tree_prefix.clone(),
            sc_offsets: bufs.sc_offsets.clone(),
            emit_offsets: bufs.emit_offsets.clone(),
            pack_sc_prefix_a: bufs.pack_sc_prefix_a.clone(),
            pack_sc_prefix_b: bufs.pack_sc_prefix_b.clone(),
            pack_emit_prefix_a: bufs.pack_emit_prefix_a.clone(),
            pack_emit_prefix_b: bufs.pack_emit_prefix_b.clone(),
            match_for_index: bufs.match_for_index.clone(),
        }
    }

    /// Builds the borrowed HIR-item buffer view expected by type-check kernels.
    pub(super) fn hir_item_buffers(&self) -> gpu_type_checker::GpuTypeCheckHirItemBuffers<'_> {
        gpu_type_checker::GpuTypeCheckHirItemBuffers {
            parser_feature_flags: self.parser_feature_flags,
            module_record_capacity: self.module_record_capacity,
            call_param_row_capacity: self.call_param_row_capacity,
            call_arg_row_capacity: self.call_arg_row_capacity,
            node_kind: &self.node_kind,
            parent: &self.parent,
            first_child: &self.first_child,
            next_sibling: &self.next_sibling,
            subtree_end: &self.subtree_end,
            kind: &self.hir_item_kind,
            name_token: &self.hir_item_name_token,
            type_form: &self.hir_type_form,
            type_value_node: &self.hir_type_value_node,
            type_len_token: &self.hir_type_len_token,
            type_len_value: &self.hir_type_len_value,
            type_file_id: &self.hir_type_file_id,
            type_path_leaf_node: &self.hir_type_path_leaf_node,
            bound_path_owner_by_leaf: &self.hir_bound_path_owner_by_leaf,
            path_segment_owner: &self.hir_path_segment_owner,
            path_segment_rank: &self.hir_path_segment_rank,
            path_segment_count: &self.hir_path_segment_count,
            type_arg_start: &self.hir_type_arg_start,
            type_arg_count: &self.hir_type_arg_count,
            type_arg_next: &self.hir_type_arg_next,
            type_arg_owner: &self.hir_type_arg_owner_a,
            type_arg_rank: &self.hir_type_arg_rank_a,
            type_root_owner: &self.hir_type_root_owner,
            type_alias_target_node: &self.hir_type_alias_target_node,
            fn_return_type_node: &self.hir_fn_return_type_node,
            param_record: &self.hir_param_record,
            param_type_node: &self.hir_param_type_node,
            method_owner_node: &self.hir_method_owner_node,
            method_impl_node: &self.hir_method_impl_node,
            method_name_token: &self.hir_method_name_token,
            method_first_param_token: &self.hir_method_first_param_token,
            method_receiver_mode: &self.hir_method_receiver_mode,
            method_visibility: &self.hir_method_visibility,
            method_signature_flags: &self.hir_method_signature_flags,
            method_impl_receiver_type_node: &self.hir_method_impl_receiver_type_node,
            expr_record: &self.hir_expr_record,
            expr_name_role: &self.hir_expr_name_role,
            expr_result_node: &self.hir_expr_result_node,
            expr_result_root_node: &self.hir_expr_result_root_node,
            expr_int_value: &self.hir_expr_int_value,
            member_receiver_node: &self.hir_member_receiver_node,
            member_receiver_token: &self.hir_member_receiver_token,
            member_name_token: &self.hir_member_name_token,
            stmt_record: &self.hir_stmt_record,
            stmt_scope_end: &self.hir_stmt_scope_end,
            nearest_stmt_node: &self.hir_nearest_stmt_node,
            nearest_block_node: &self.hir_nearest_block_node,
            nearest_enclosing_control_node: &self.hir_nearest_enclosing_control_node,
            nearest_loop_node: &self.hir_nearest_loop_node,
            nearest_fn_node: &self.hir_nearest_fn_node,
            array_lit_first_element: &self.hir_array_lit_first_element,
            array_lit_element_count: &self.hir_array_lit_element_count,
            array_lit_context_stmt_node: &self.hir_array_lit_context_stmt_node,
            array_element_parent_lit: &self.hir_array_element_parent_lit,
            nearest_array_element_node: &self.hir_nearest_array_element_node,
            array_element_next: &self.hir_array_element_next,
            namespace: &self.hir_item_namespace,
            visibility: &self.hir_item_visibility,
            path_start: &self.hir_item_path_start,
            path_end: &self.hir_item_path_end,
            path_node: &self.hir_item_path_node,
            file_id: &self.hir_item_file_id,
            import_target_kind: &self.hir_item_import_target_kind,
            call_callee_node: &self.hir_call_callee_node,
            call_callee_path_node: &self.hir_call_callee_path_node,
            call_parent_by_callee: &self.hir_call_parent_by_callee,
            call_context_stmt_node: &self.hir_call_context_stmt_node,
            call_arg_start: &self.hir_call_arg_start,
            call_arg_end: &self.hir_call_arg_end,
            call_arg_count: &self.hir_call_arg_count,
            call_arg_parent_call: &self.hir_call_arg_parent_call,
            call_arg_ordinal: &self.hir_call_arg_ordinal,
            variant_parent_enum: &self.hir_variant_parent_enum,
            variant_payload_start: &self.hir_variant_payload_start,
            variant_payload_count: &self.hir_variant_payload_count,
            variant_payload_node: &self.hir_variant_payload_node,
            match_scrutinee_node: &self.hir_match_scrutinee_node,
            match_arm_start: &self.hir_match_arm_start,
            match_arm_count: &self.hir_match_arm_count,
            match_arm_next: &self.hir_match_arm_next,
            match_arm_pattern_node: &self.hir_match_arm_pattern_node,
            match_pattern_owner_arm: &self.hir_match_pattern_owner_arm,
            match_arm_payload_start: &self.hir_match_arm_payload_start,
            match_arm_payload_count: &self.hir_match_arm_payload_count,
            match_arm_result_node: &self.hir_match_arm_result_node,
            match_payload_owner_arm: &self.hir_match_payload_owner_arm,
            match_payload_match_node: &self.hir_match_payload_match_node,
            match_payload_ordinal: &self.hir_match_payload_ordinal,
            struct_field_parent_struct: &self.hir_struct_field_parent_struct,
            struct_field_ordinal: &self.hir_struct_field_ordinal,
            struct_field_type_node: &self.hir_struct_field_type_node,
            struct_decl_field_start: &self.hir_struct_decl_field_start,
            struct_decl_field_count: &self.hir_struct_decl_field_count,
            struct_lit_head_node: &self.hir_struct_lit_head_node,
            struct_lit_context_stmt_node: &self.hir_struct_lit_context_stmt_node,
            struct_lit_field_start: &self.hir_struct_lit_field_start,
            struct_lit_field_count: &self.hir_struct_lit_field_count,
            struct_lit_field_parent_lit: &self.hir_struct_lit_field_parent_lit,
            struct_lit_field_value_node: &self.hir_struct_lit_field_value_node,
            semantic_dense_node: &self.hir_semantic_dense_node,
            semantic_count: &self.hir_semantic_count,
            semantic_subtree_end: &self.hir_semantic_subtree_end,
        }
    }

    /// Builds the checked HIR view used by semantic-interface type discovery.
    pub(super) fn semantic_interface_hir_buffers(
        &self,
    ) -> gpu_type_checker::GpuSemanticInterfaceHirBuffers<'_> {
        gpu_type_checker::GpuSemanticInterfaceHirBuffers {
            hir_status: &self.ll1_status,
            hir_kind: &self.hir_kind,
            hir_token_pos: &self.hir_token_pos,
            hir_type_arg_owner: &self.hir_type_arg_owner_a,
            hir_type_arg_rank: &self.hir_type_arg_rank_a,
            hir_type_arg_count: &self.hir_type_arg_count,
            hir_type_form: &self.hir_type_form,
            hir_type_value_node: &self.hir_type_value_node,
            hir_type_len_token: &self.hir_type_len_token,
            hir_type_len_value: &self.hir_type_len_value,
            hir_fn_return_type_node: &self.hir_fn_return_type_node,
            hir_type_alias_target_node: &self.hir_type_alias_target_node,
            hir_stmt_record: &self.hir_stmt_record,
            hir_param_record: &self.hir_param_record,
            hir_param_type_node: &self.hir_param_type_node,
            hir_struct_field_parent_struct: &self.hir_struct_field_parent_struct,
            hir_struct_field_type_node: &self.hir_struct_field_type_node,
            hir_variant_payload_count: &self.hir_variant_payload_count,
            hir_variant_payload_node: &self.hir_variant_payload_node,
            hir_variant_parent_enum: &self.hir_variant_parent_enum,
            hir_variant_ordinal: &self.hir_variant_ordinal,
            hir_struct_field_ordinal: &self.hir_struct_field_ordinal,
            hir_struct_decl_field_count: &self.hir_struct_decl_field_count,
        }
    }
}
