import Lanius.Extraction.VerifiedFrontend.Artifact.Symbol.Artifact
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
kernel_parse_semantic verifiedFrontendSymbol_semantic_trace_checked_kernel for
  verifiedFrontendSymbolArtifact
end Lanius.Extraction
