use super::super::*;

pub(in crate::type_checker) struct CreateInputs<'a> {
    pub(in crate::type_checker) params: &'a LaniusBuffer<TypeCheckParams>,
    pub(in crate::type_checker) source_file_capacity: u32,
    pub(in crate::type_checker) token_capacity: u32,
    pub(in crate::type_checker) hir_node_capacity: u32,
    pub(in crate::type_checker) token_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) token_count_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_status_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_kind_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_token_pos_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_token_end_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) status_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_active_count_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_items: GpuTypeCheckHirItemBuffers<'a>,
    pub(in crate::type_checker) name_id_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) language_name_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_name_token_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_id_by_name_token_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_kind_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_hir_node_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_parent_type_decl_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_type_path_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_type_path_status: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_expr_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_open: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_const_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_const_end: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_status: &'a wgpu::Buffer,
    pub(in crate::type_checker) predicate_syntax_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) visible_decl: &'a wgpu::Buffer,
    pub(in crate::type_checker) visible_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) enclosing_fn: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_fn_index: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_return_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_return_type_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) method_call_name_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_record: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_node: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_node: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_expr_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_expr_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_kind: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_decl_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_decl_generic_param_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_generic_param_slot_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_state: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_type_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_type_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) fn_return_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) fn_return_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) record_family_bits_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) record_family_flag_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) external_scratch: Option<GpuTypeCheckExternalScratchBuffers<'a>>,
}
