import Lanius.Extraction.VerifiedFrontend.Surface.Digits.Parse.View
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_nodes_cached_chunk verifiedFrontendDigits_nodes_0_trace_checked_kernel,
  verifiedFrontendDigits_nodes_0_trace_length_kernel for
  verifiedFrontendDigitsArtifact, verifiedFrontendDigitsParseView, 0, 1000
end Lanius.Extraction
