import Lanius.Extraction.VerifiedFrontend.Surface.Token.View.Artifact
import Lanius.Extraction.VerifiedFrontend.Artifact.Token.Artifact
import Lanius.Extraction.ParseChunks

namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_semantic verifiedFrontendToken_semantic_trace_checked_kernel for verifiedFrontendTokenArtifact
end Lanius.Extraction

namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_root verifiedFrontendToken_root_trace_present_kernel,
  verifiedFrontendTokenRootTraceKernel, verifiedFrontendToken_root_trace_found_kernel,
  verifiedFrontendToken_root_trace_shape_kernel for verifiedFrontendTokenArtifact, verifiedFrontendTokenView
end Lanius.Extraction
