use encase::ShaderType;

use super::{
    BracketsBlockPrefixScanStep,
    BracketsHistogramScanStep,
    HirSemanticPrefixScanStep,
    PackOffsetScanStep,
    PackTotalReduceStep,
    TokenDelimiterScanStep,
    TreePrefixMaxBuildStep,
    TreePrefixScanStep,
};
use crate::gpu::buffers::LaniusBuffer;

#[repr(C)]
#[derive(Clone, Copy, ShaderType, Default)]
pub struct ActionHeader {
    pub push_len: u32,
    pub emit_len: u32,
    pub pop_tag: u32,
    pub pop_count: u32,
}

#[repr(C)]
#[derive(Clone, Copy, ShaderType)]
pub struct TokenDelimiterParams {
    pub n_tokens: u32,
    pub n_blocks: u32,
    pub scan_step: u32,
}

#[repr(C)]
#[derive(Clone, Copy, ShaderType)]
pub struct TokenBraceMatchParams {
    pub n_tokens: u32,
}

/// All GPU-side buffers for the parser pipeline (no readbacks/staging here).
pub struct ParserBuffers {
    // sizes
    pub n_tokens: u32,
    pub n_kinds: u32,
    pub total_sc: u32,
    pub total_emit: u32,
    pub tree_count_uses_status: bool,
    pub tree_capacity: u32,

    // canonical LL(1) parser tables and outputs
    pub ll1_predict: LaniusBuffer<u32>,
    pub ll1_prod_rhs_off: LaniusBuffer<u32>,
    pub ll1_prod_rhs_len: LaniusBuffer<u32>,
    pub ll1_prod_rhs: LaniusBuffer<u32>,
    pub ll1_emit: LaniusBuffer<u32>,
    pub ll1_emit_pos: LaniusBuffer<u32>,
    pub ll1_status: LaniusBuffer<u32>,

    // pair→header
    pub params_llp: LaniusBuffer<super::super::passes::llp_pairs::LLPParams>,
    pub semantic_token_kinds: LaniusBuffer<u32>,
    pub token_delimiter_params: LaniusBuffer<TokenDelimiterParams>,
    pub token_delimiter_scan_steps: Vec<TokenDelimiterScanStep>,
    pub token_input_capacity: u32,
    pub token_delimiter_n_blocks: u32,
    pub token_depth_paren_inblock: LaniusBuffer<i32>,
    pub token_depth_brace_inblock: LaniusBuffer<i32>,
    pub token_depth_bracket_inblock: LaniusBuffer<i32>,
    pub token_depth_angle_inblock: LaniusBuffer<i32>,
    pub token_block_sum_paren: LaniusBuffer<i32>,
    pub token_block_sum_brace: LaniusBuffer<i32>,
    pub token_block_sum_bracket: LaniusBuffer<i32>,
    pub token_block_sum_angle: LaniusBuffer<i32>,
    pub token_prefix_paren_a: LaniusBuffer<i32>,
    pub token_prefix_paren_b: LaniusBuffer<i32>,
    pub token_block_prefix_paren: LaniusBuffer<i32>,
    pub token_prefix_brace_a: LaniusBuffer<i32>,
    pub token_prefix_brace_b: LaniusBuffer<i32>,
    pub token_block_prefix_brace: LaniusBuffer<i32>,
    pub token_prefix_bracket_a: LaniusBuffer<i32>,
    pub token_prefix_bracket_b: LaniusBuffer<i32>,
    pub token_block_prefix_bracket: LaniusBuffer<i32>,
    pub token_prefix_angle_a: LaniusBuffer<i32>,
    pub token_prefix_angle_b: LaniusBuffer<i32>,
    pub token_block_prefix_angle: LaniusBuffer<i32>,
    pub token_top_brace_owner_block: LaniusBuffer<u32>,
    pub token_top_brace_owner_prefix_a: LaniusBuffer<u32>,
    pub token_top_brace_owner_prefix_b: LaniusBuffer<u32>,
    pub token_top_brace_owner_block_prefix: LaniusBuffer<u32>,
    pub token_statement_event_block: LaniusBuffer<u32>,
    pub token_statement_event_prefix_a: LaniusBuffer<u32>,
    pub token_statement_event_prefix_b: LaniusBuffer<u32>,
    pub token_statement_event_block_prefix: LaniusBuffer<u32>,
    pub token_brace_semantic_kind: LaniusBuffer<u32>,
    pub token_bracket_semantic_kind: LaniusBuffer<u32>,
    pub token_statement_context_kind: LaniusBuffer<u32>,
    pub token_impl_header_kind: LaniusBuffer<u32>,
    pub token_impl_context_event: LaniusBuffer<u32>,
    pub token_type_path_context_kind: LaniusBuffer<u32>,
    pub token_where_context_event: LaniusBuffer<u32>,
    pub token_match_pattern_context_event: LaniusBuffer<u32>,
    // Delimiter-pair match records.
    pub token_brace_match_params: LaniusBuffer<TokenBraceMatchParams>,
    pub token_brace_match_depth: LaniusBuffer<i32>,
    pub token_brace_match_block_min: LaniusBuffer<i32>,
    pub token_brace_match_min_tree_base: u32,
    pub token_brace_match_min_tree: LaniusBuffer<i32>,
    pub token_brace_match_min_tree_steps: Vec<TreePrefixMaxBuildStep>,
    pub token_bracket_match_depth: LaniusBuffer<i32>,
    pub token_bracket_match_block_min: LaniusBuffer<i32>,
    pub token_bracket_match_min_tree: LaniusBuffer<i32>,
    pub token_paren_match_depth: LaniusBuffer<i32>,
    pub token_paren_match_block_min: LaniusBuffer<i32>,
    pub token_paren_match_min_tree: LaniusBuffer<i32>,
    pub token_angle_match_depth: LaniusBuffer<i32>,
    pub token_angle_match_block_min: LaniusBuffer<i32>,
    pub token_angle_match_min_tree: LaniusBuffer<i32>,
    pub token_feature_flags: LaniusBuffer<u32>,
    pub token_count: LaniusBuffer<u32>,
    pub default_token_file_id: LaniusBuffer<u32>,
    pub source_file_token_end_params:
        LaniusBuffer<super::super::passes::source_file_token_end::Params>,
    pub source_file_token_end: LaniusBuffer<u32>,
    pub active_pair_thread_dispatch_args: LaniusBuffer<u32>,
    pub active_pair_group_dispatch_args: LaniusBuffer<u32>,
    pub action_table: LaniusBuffer<u8>,
    pub out_headers: LaniusBuffer<ActionHeader>,

    // pack varlen
    pub params_pack: LaniusBuffer<super::super::passes::pack::varlen::PackParams>,
    pub sc_offsets: LaniusBuffer<u32>,
    pub emit_offsets: LaniusBuffer<u32>,
    pub pack_sc_prefix_a: LaniusBuffer<u32>,
    pub pack_sc_prefix_b: LaniusBuffer<u32>,
    pub pack_emit_prefix_a: LaniusBuffer<u32>,
    pub pack_emit_prefix_b: LaniusBuffer<u32>,
    pub pack_offset_scan_steps: Vec<PackOffsetScanStep>,
    pub pack_total_reduce_steps: Vec<PackTotalReduceStep>,
    pub projected_status: LaniusBuffer<u32>,
    pub tables_blob: LaniusBuffer<u32>,
    pub out_sc: LaniusBuffer<u32>,
    pub out_emit: LaniusBuffer<u32>,
    pub out_emit_pos: LaniusBuffer<u32>,

    // -------- Brackets (parallel) --------
    pub b01_params: LaniusBuffer<super::super::passes::brackets::scan_inblock::Params>,
    pub b02_params: LaniusBuffer<super::super::passes::brackets::scan_block_prefix::Params>,
    pub b02_scan_steps: Vec<BracketsBlockPrefixScanStep>,
    pub b03_params: LaniusBuffer<super::super::passes::brackets::apply_prefix::Params>,
    pub b04_params: LaniusBuffer<super::super::passes::brackets::histogram_layers::Params>,
    pub b05_params: LaniusBuffer<super::super::passes::brackets::scan_histograms::Params>,
    pub b06_params: LaniusBuffer<super::super::passes::brackets::scatter_by_layer::Params>,
    pub b07_params: LaniusBuffer<super::super::passes::brackets::pse_pair::Params>, // PSE-style pair-by-layer
    pub b05_scan_steps: Vec<BracketsHistogramScanStep>,

    pub b_exscan_inblock: LaniusBuffer<i32>,
    pub b_block_sum: LaniusBuffer<i32>,
    pub b_block_minpref: LaniusBuffer<i32>,
    pub b_block_maxdepth: LaniusBuffer<i32>,
    pub b_block_prefix: LaniusBuffer<i32>,
    pub b_block_prefix_sum_a: LaniusBuffer<i32>,
    pub b_block_prefix_sum_b: LaniusBuffer<i32>,
    pub b_block_prefix_min_a: LaniusBuffer<i32>,
    pub b_block_prefix_min_b: LaniusBuffer<i32>,

    pub depths_out: LaniusBuffer<i32>, // [final, min]
    pub valid_out: LaniusBuffer<u32>,

    pub b_depth_exscan: LaniusBuffer<i32>,
    pub b_layer: LaniusBuffer<u32>,

    pub b_hist_push: LaniusBuffer<u32>,
    pub b_hist_pop: LaniusBuffer<u32>,
    pub b_off_push: LaniusBuffer<u32>,
    pub b_off_pop: LaniusBuffer<u32>,
    pub b_cur_push: LaniusBuffer<u32>,
    pub b_cur_pop: LaniusBuffer<u32>,
    pub b_pushes_by_layer: LaniusBuffer<u32>,
    pub b_pops_by_layer: LaniusBuffer<u32>,
    pub b_slot_for_index: LaniusBuffer<u32>,
    pub match_for_index: LaniusBuffer<u32>,

    // counts used at dispatch
    pub b_n_blocks: u32,
    pub b_n_layers: u32,

    // -------- Tree parent recovery --------
    pub tree_prefix_params: LaniusBuffer<super::super::passes::tree::prefix::local::Params>,
    pub tree_prefix_scan_steps: Vec<TreePrefixScanStep>,
    pub tree_n_node_blocks: u32,
    pub tree_n_prefix_blocks: u32,
    pub tree_active_dispatch_args: LaniusBuffer<u32>,
    pub tree_enum_dispatch_args: LaniusBuffer<u32>,
    pub tree_match_dispatch_args: LaniusBuffer<u32>,
    pub tree_struct_dispatch_args: LaniusBuffer<u32>,
    pub hir_semantic_dispatch_args: LaniusBuffer<u32>,
    pub tree_prefix_inblock: LaniusBuffer<i32>,
    pub tree_block_sum: LaniusBuffer<i32>,
    pub tree_block_prefix_a: LaniusBuffer<i32>,
    pub tree_block_prefix_b: LaniusBuffer<i32>,
    pub tree_block_prefix: LaniusBuffer<i32>,
    pub tree_prefix: LaniusBuffer<i32>,
    pub tree_prefix_block_max: LaniusBuffer<i32>,
    pub tree_prefix_block_max_tree_base: u32,
    pub tree_prefix_block_max_tree: LaniusBuffer<i32>,
    pub tree_prefix_max_build_steps: Vec<TreePrefixMaxBuildStep>,
    pub tree_params: LaniusBuffer<super::super::passes::tree::parent::Params>,
    pub tree_span_params: LaniusBuffer<super::super::passes::tree::spans::Params>,
    pub tree_prev_sibling_params:
        LaniusBuffer<super::super::passes::tree::prev::sibling::clear::Params>,
    pub prod_arity: LaniusBuffer<u32>,
    pub node_kind: LaniusBuffer<u32>,
    pub parent: LaniusBuffer<u32>,
    pub first_child: LaniusBuffer<u32>,
    pub next_sibling: LaniusBuffer<u32>,
    pub prev_sibling: LaniusBuffer<u32>,
    pub subtree_end: LaniusBuffer<u32>,

    // -------- HIR-facing classification --------
    pub hir_params: LaniusBuffer<super::super::passes::hir::nodes::Params>,
    pub hir_span_params: LaniusBuffer<super::super::passes::hir::spans::Params>,
    pub hir_type_fields_params: LaniusBuffer<super::super::passes::hir::types::fields::Params>,
    pub hir_item_fields_params: LaniusBuffer<super::super::passes::hir::item::fields::Params>,
    pub hir_param_fields_params: LaniusBuffer<super::super::passes::hir::param::fields::Params>,
    pub hir_method_fields_params: LaniusBuffer<super::super::passes::hir::method::fields::Params>,
    pub hir_expr_fields_params: LaniusBuffer<super::super::passes::hir::expr::fields::Params>,
    pub hir_member_fields_params: LaniusBuffer<super::super::passes::hir::member::fields::Params>,
    pub hir_stmt_fields_params: LaniusBuffer<super::super::passes::hir::stmt_fields::Params>,
    pub hir_call_fields_params: LaniusBuffer<super::super::passes::hir::call::fields::Params>,
    pub hir_array_fields_params: LaniusBuffer<super::super::passes::hir::array::fields::Params>,
    pub hir_enum_match_fields_params:
        LaniusBuffer<super::super::passes::hir::enums::match_fields::Params>,
    pub hir_struct_fields_params: LaniusBuffer<super::super::passes::hir::structs::fields::Params>,
    pub hir_kind: LaniusBuffer<u32>,
    pub hir_semantic_block_count: LaniusBuffer<u32>,
    pub hir_semantic_prefix_scan_steps: Vec<HirSemanticPrefixScanStep>,
    pub hir_semantic_flag: LaniusBuffer<u32>,
    pub hir_semantic_local_prefix: LaniusBuffer<u32>,
    pub hir_semantic_block_prefix_a: LaniusBuffer<u32>,
    pub hir_semantic_block_prefix_b: LaniusBuffer<u32>,
    pub hir_node_dense_id: LaniusBuffer<u32>,
    pub hir_semantic_prefix_before_node: LaniusBuffer<u32>,
    pub hir_semantic_dense_node: LaniusBuffer<u32>,
    pub hir_semantic_subtree_end: LaniusBuffer<u32>,
    pub hir_semantic_parent: LaniusBuffer<u32>,
    pub hir_semantic_first_child: LaniusBuffer<u32>,
    pub hir_semantic_next_sibling: LaniusBuffer<u32>,
    pub hir_semantic_depth: LaniusBuffer<u32>,
    pub hir_semantic_child_index: LaniusBuffer<u32>,
    pub hir_semantic_parent_link_a: LaniusBuffer<u32>,
    pub hir_semantic_parent_link_b: LaniusBuffer<u32>,
    pub hir_semantic_parent_value_a: LaniusBuffer<u32>,
    pub hir_semantic_parent_value_b: LaniusBuffer<u32>,
    pub hir_semantic_depth_link_a: LaniusBuffer<u32>,
    pub hir_semantic_depth_link_b: LaniusBuffer<u32>,
    pub hir_semantic_depth_value_a: LaniusBuffer<u32>,
    pub hir_semantic_depth_value_b: LaniusBuffer<u32>,
    pub hir_semantic_child_index_link_a: LaniusBuffer<u32>,
    pub hir_semantic_child_index_link_b: LaniusBuffer<u32>,
    pub hir_semantic_child_index_rank_a: LaniusBuffer<u32>,
    pub hir_semantic_child_index_rank_b: LaniusBuffer<u32>,
    pub hir_semantic_count: LaniusBuffer<u32>,
    pub hir_token_pos: LaniusBuffer<u32>,
    pub hir_token_end: LaniusBuffer<u32>,
    pub hir_token_file_id: LaniusBuffer<u32>,
    pub hir_type_form: LaniusBuffer<u32>,
    pub hir_type_value_node: LaniusBuffer<u32>,
    pub hir_type_len_token: LaniusBuffer<u32>,
    pub hir_type_len_value: LaniusBuffer<u32>,
    pub hir_type_file_id: LaniusBuffer<u32>,
    pub hir_type_path_leaf_node: LaniusBuffer<u32>,
    pub hir_bound_path_owner_by_leaf: LaniusBuffer<u32>,
    pub hir_type_path_leaf_link_a: LaniusBuffer<u32>,
    pub hir_type_path_leaf_link_b: LaniusBuffer<u32>,
    pub hir_type_path_leaf_value_a: LaniusBuffer<u32>,
    pub hir_type_path_leaf_value_b: LaniusBuffer<u32>,
    pub hir_type_arg_start: LaniusBuffer<u32>,
    pub hir_type_arg_count: LaniusBuffer<u32>,
    pub hir_type_arg_next: LaniusBuffer<u32>,
    pub hir_type_alias_target_node: LaniusBuffer<u32>,
    pub hir_fn_return_type_node: LaniusBuffer<u32>,
    pub hir_fn_signature_owner_link_a: LaniusBuffer<u32>,
    pub hir_fn_signature_owner_link_b: LaniusBuffer<u32>,
    pub hir_fn_signature_return_owner_a: LaniusBuffer<u32>,
    pub hir_fn_signature_return_owner_b: LaniusBuffer<u32>,
    pub hir_fn_signature_function_owner_a: LaniusBuffer<u32>,
    pub hir_fn_signature_function_owner_b: LaniusBuffer<u32>,
    pub hir_type_arg_owner_a: LaniusBuffer<u32>,
    pub hir_type_arg_owner_b: LaniusBuffer<u32>,
    pub hir_type_arg_link_a: LaniusBuffer<u32>,
    pub hir_type_arg_link_b: LaniusBuffer<u32>,
    pub hir_type_arg_rank_a: LaniusBuffer<u32>,
    pub hir_type_arg_rank_b: LaniusBuffer<u32>,
    pub hir_type_arg_previous: LaniusBuffer<u32>,
    pub hir_type_alias_owner_link_a: LaniusBuffer<u32>,
    pub hir_type_alias_owner_link_b: LaniusBuffer<u32>,
    pub hir_type_alias_owner_value_a: LaniusBuffer<u32>,
    pub hir_type_alias_owner_value_b: LaniusBuffer<u32>,
    pub hir_item_kind: LaniusBuffer<u32>,
    pub hir_item_name_token: LaniusBuffer<u32>,
    pub hir_item_decl_token: LaniusBuffer<u32>,
    pub hir_item_namespace: LaniusBuffer<u32>,
    pub hir_item_visibility: LaniusBuffer<u32>,
    pub hir_item_path_start: LaniusBuffer<u32>,
    pub hir_item_path_end: LaniusBuffer<u32>,
    pub hir_item_path_node: LaniusBuffer<u32>,
    pub hir_item_file_id: LaniusBuffer<u32>,
    pub hir_item_import_target_kind: LaniusBuffer<u32>,
    pub hir_param_record: LaniusBuffer<u32>,
    pub hir_param_type_node: LaniusBuffer<u32>,
    pub hir_method_owner_node: LaniusBuffer<u32>,
    pub hir_method_impl_node: LaniusBuffer<u32>,
    pub hir_method_name_token: LaniusBuffer<u32>,
    pub hir_method_first_param_token: LaniusBuffer<u32>,
    pub hir_method_receiver_mode: LaniusBuffer<u32>,
    pub hir_method_visibility: LaniusBuffer<u32>,
    pub hir_method_signature_flags: LaniusBuffer<u32>,
    pub hir_method_impl_receiver_type_node: LaniusBuffer<u32>,
    pub hir_param_owner_a: LaniusBuffer<u32>,
    pub hir_param_owner_b: LaniusBuffer<u32>,
    pub hir_param_link_a: LaniusBuffer<u32>,
    pub hir_param_link_b: LaniusBuffer<u32>,
    pub hir_param_rank_a: LaniusBuffer<u32>,
    pub hir_param_rank_b: LaniusBuffer<u32>,
    pub hir_param_previous: LaniusBuffer<u32>,
    pub hir_variant_parent_enum: LaniusBuffer<u32>,
    pub hir_variant_ordinal: LaniusBuffer<u32>,
    pub hir_variant_payload_start: LaniusBuffer<u32>,
    pub hir_variant_payload_count: LaniusBuffer<u32>,
    pub hir_variant_payload_node: LaniusBuffer<u32>,
    pub hir_variant_owner_a: LaniusBuffer<u32>,
    pub hir_variant_owner_b: LaniusBuffer<u32>,
    pub hir_variant_link_a: LaniusBuffer<u32>,
    pub hir_variant_link_b: LaniusBuffer<u32>,
    pub hir_variant_rank_a: LaniusBuffer<u32>,
    pub hir_variant_rank_b: LaniusBuffer<u32>,
    pub hir_variant_payload_owner_a: LaniusBuffer<u32>,
    pub hir_variant_payload_owner_b: LaniusBuffer<u32>,
    pub hir_variant_payload_link_a: LaniusBuffer<u32>,
    pub hir_variant_payload_link_b: LaniusBuffer<u32>,
    pub hir_variant_payload_rank_a: LaniusBuffer<u32>,
    pub hir_variant_payload_rank_b: LaniusBuffer<u32>,
    pub hir_list_rank_flag: LaniusBuffer<u32>,
    pub hir_list_rank_local_prefix: LaniusBuffer<u32>,
    pub hir_list_rank_block_sum: LaniusBuffer<u32>,
    pub hir_list_rank_block_prefix_a: LaniusBuffer<u32>,
    pub hir_list_rank_block_prefix_b: LaniusBuffer<u32>,
    pub hir_list_rank_node: LaniusBuffer<u32>,
    pub hir_list_rank_count: LaniusBuffer<u32>,
    pub hir_list_rank_dispatch_args: LaniusBuffer<u32>,
    pub hir_enum_rank_flag: LaniusBuffer<u32>,
    pub hir_enum_rank_local_prefix: LaniusBuffer<u32>,
    pub hir_enum_rank_block_sum: LaniusBuffer<u32>,
    pub hir_enum_rank_block_prefix_a: LaniusBuffer<u32>,
    pub hir_enum_rank_block_prefix_b: LaniusBuffer<u32>,
    pub hir_enum_rank_node: LaniusBuffer<u32>,
    pub hir_enum_rank_count: LaniusBuffer<u32>,
    pub hir_enum_rank_dispatch_args: LaniusBuffer<u32>,
    pub hir_match_scrutinee_node: LaniusBuffer<u32>,
    pub hir_match_arm_start: LaniusBuffer<u32>,
    pub hir_match_arm_count: LaniusBuffer<u32>,
    pub hir_match_arm_next: LaniusBuffer<u32>,
    pub hir_match_arm_pattern_node: LaniusBuffer<u32>,
    pub hir_match_arm_payload_start: LaniusBuffer<u32>,
    pub hir_match_arm_payload_count: LaniusBuffer<u32>,
    pub hir_match_arm_result_node: LaniusBuffer<u32>,
    pub hir_match_payload_owner_arm: LaniusBuffer<u32>,
    pub hir_match_payload_match_node: LaniusBuffer<u32>,
    pub hir_match_payload_ordinal: LaniusBuffer<u32>,
    pub hir_match_arm_owner_a: LaniusBuffer<u32>,
    pub hir_match_arm_owner_b: LaniusBuffer<u32>,
    pub hir_match_arm_link_a: LaniusBuffer<u32>,
    pub hir_match_arm_link_b: LaniusBuffer<u32>,
    pub hir_match_arm_rank_a: LaniusBuffer<u32>,
    pub hir_match_arm_rank_b: LaniusBuffer<u32>,
    pub hir_match_arm_previous: LaniusBuffer<u32>,
    pub hir_match_payload_owner_a: LaniusBuffer<u32>,
    pub hir_match_payload_owner_b: LaniusBuffer<u32>,
    pub hir_match_payload_link_a: LaniusBuffer<u32>,
    pub hir_match_payload_link_b: LaniusBuffer<u32>,
    pub hir_match_payload_rank_a: LaniusBuffer<u32>,
    pub hir_match_payload_rank_b: LaniusBuffer<u32>,
    pub hir_match_rank_flag: LaniusBuffer<u32>,
    pub hir_match_rank_local_prefix: LaniusBuffer<u32>,
    pub hir_match_rank_block_sum: LaniusBuffer<u32>,
    pub hir_match_rank_block_prefix_a: LaniusBuffer<u32>,
    pub hir_match_rank_block_prefix_b: LaniusBuffer<u32>,
    pub hir_match_rank_node: LaniusBuffer<u32>,
    pub hir_match_rank_count: LaniusBuffer<u32>,
    pub hir_match_rank_dispatch_args: LaniusBuffer<u32>,
    pub hir_call_callee_node: LaniusBuffer<u32>,
    pub hir_call_context_stmt_node: LaniusBuffer<u32>,
    pub hir_call_arg_start: LaniusBuffer<u32>,
    pub hir_call_arg_end: LaniusBuffer<u32>,
    pub hir_call_arg_count: LaniusBuffer<u32>,
    // Packed `parent_call_node | ordinal << 28` call-argument record. The
    // ordinal view shares this storage so consumers can read the split ordinal
    // record without keeping a second tree-capacity GPU buffer.
    pub hir_call_arg_parent_call: LaniusBuffer<u32>,
    pub hir_call_arg_ordinal: LaniusBuffer<u32>,
    pub hir_call_arg_owner_a: LaniusBuffer<u32>,
    pub hir_call_arg_owner_b: LaniusBuffer<u32>,
    pub hir_call_arg_link_a: LaniusBuffer<u32>,
    pub hir_call_arg_link_b: LaniusBuffer<u32>,
    pub hir_call_arg_rank_a: LaniusBuffer<u32>,
    pub hir_call_arg_rank_b: LaniusBuffer<u32>,
    pub hir_array_lit_first_element: LaniusBuffer<u32>,
    pub hir_array_lit_element_count: LaniusBuffer<u32>,
    pub hir_array_lit_context_stmt_node: LaniusBuffer<u32>,
    pub hir_array_element_parent_lit: LaniusBuffer<u32>,
    pub hir_array_element_ordinal: LaniusBuffer<u32>,
    pub hir_array_element_next: LaniusBuffer<u32>,
    pub hir_array_element_owner_a: LaniusBuffer<u32>,
    pub hir_array_element_owner_b: LaniusBuffer<u32>,
    pub hir_array_element_link_a: LaniusBuffer<u32>,
    pub hir_array_element_link_b: LaniusBuffer<u32>,
    pub hir_array_element_rank_a: LaniusBuffer<u32>,
    pub hir_array_element_rank_b: LaniusBuffer<u32>,
    pub hir_array_element_previous: LaniusBuffer<u32>,
    // Compatibility-sized dummies. `hir_expr_record` is the authoritative
    // expression metadata buffer; these are kept at one word until older
    // host-facing debug surfaces are fully removed.
    pub hir_expr_form: LaniusBuffer<u32>,
    pub hir_expr_left_node: LaniusBuffer<u32>,
    pub hir_expr_right_node: LaniusBuffer<u32>,
    pub hir_expr_value_token: LaniusBuffer<u32>,
    pub hir_expr_record: LaniusBuffer<u32>,
    pub hir_expr_result_node: LaniusBuffer<u32>,
    pub hir_expr_result_root_node: LaniusBuffer<u32>,
    pub hir_expr_result_root_scratch_node: LaniusBuffer<u32>,
    pub hir_binary_span_link_a: LaniusBuffer<u32>,
    pub hir_binary_span_link_b: LaniusBuffer<u32>,
    pub hir_binary_span_start_a: LaniusBuffer<u32>,
    pub hir_binary_span_start_b: LaniusBuffer<u32>,
    pub hir_expr_int_value: LaniusBuffer<u32>,
    pub hir_member_receiver_node: LaniusBuffer<u32>,
    pub hir_member_receiver_token: LaniusBuffer<u32>,
    pub hir_member_name_token: LaniusBuffer<u32>,
    pub hir_stmt_record: LaniusBuffer<u32>,
    pub hir_stmt_scope_end: LaniusBuffer<u32>,
    pub hir_nearest_stmt_node: LaniusBuffer<u32>,
    pub hir_nearest_block_node: LaniusBuffer<u32>,
    pub hir_nearest_enclosing_control_node: LaniusBuffer<u32>,
    pub hir_nearest_loop_node: LaniusBuffer<u32>,
    pub hir_nearest_fn_node: LaniusBuffer<u32>,
    pub hir_struct_field_parent_struct: LaniusBuffer<u32>,
    pub hir_struct_field_ordinal: LaniusBuffer<u32>,
    pub hir_struct_field_type_node: LaniusBuffer<u32>,
    pub hir_struct_decl_field_start: LaniusBuffer<u32>,
    pub hir_struct_decl_field_count: LaniusBuffer<u32>,
    pub hir_struct_lit_head_node: LaniusBuffer<u32>,
    pub hir_struct_lit_context_stmt_node: LaniusBuffer<u32>,
    pub hir_struct_lit_field_start: LaniusBuffer<u32>,
    pub hir_struct_lit_field_count: LaniusBuffer<u32>,
    pub hir_struct_lit_field_parent_lit: LaniusBuffer<u32>,
    pub hir_struct_lit_field_value_node: LaniusBuffer<u32>,
    pub hir_struct_lit_field_next: LaniusBuffer<u32>,
    pub hir_struct_field_owner_a: LaniusBuffer<u32>,
    pub hir_struct_field_owner_b: LaniusBuffer<u32>,
    pub hir_struct_field_link_a: LaniusBuffer<u32>,
    pub hir_struct_field_link_b: LaniusBuffer<u32>,
    pub hir_struct_field_rank_a: LaniusBuffer<u32>,
    pub hir_struct_field_rank_b: LaniusBuffer<u32>,
    pub hir_struct_lit_field_owner_a: LaniusBuffer<u32>,
    pub hir_struct_lit_field_owner_b: LaniusBuffer<u32>,
    pub hir_struct_lit_field_link_a: LaniusBuffer<u32>,
    pub hir_struct_lit_field_link_b: LaniusBuffer<u32>,
    pub hir_struct_lit_field_rank_a: LaniusBuffer<u32>,
    pub hir_struct_lit_field_rank_b: LaniusBuffer<u32>,
    pub hir_struct_lit_field_previous: LaniusBuffer<u32>,
    pub hir_stmt_context_link_a: LaniusBuffer<u32>,
    pub hir_stmt_context_link_b: LaniusBuffer<u32>,
    pub hir_contextual_stmt_value_a: LaniusBuffer<u32>,
    pub hir_contextual_stmt_value_b: LaniusBuffer<u32>,
    pub hir_nearest_stmt_value_a: LaniusBuffer<u32>,
    pub hir_nearest_stmt_value_b: LaniusBuffer<u32>,
    pub hir_nearest_block_value_a: LaniusBuffer<u32>,
    pub hir_nearest_block_value_b: LaniusBuffer<u32>,
    pub hir_nearest_enclosing_control_value_a: LaniusBuffer<u32>,
    pub hir_nearest_enclosing_control_value_b: LaniusBuffer<u32>,
    pub hir_nearest_loop_value_a: LaniusBuffer<u32>,
    pub hir_nearest_loop_value_b: LaniusBuffer<u32>,
    pub hir_nearest_fn_value_a: LaniusBuffer<u32>,
    pub hir_nearest_fn_value_b: LaniusBuffer<u32>,
    pub hir_struct_rank_flag: LaniusBuffer<u32>,
    pub hir_struct_rank_local_prefix: LaniusBuffer<u32>,
    pub hir_struct_rank_block_sum: LaniusBuffer<u32>,
    pub hir_struct_rank_block_prefix_a: LaniusBuffer<u32>,
    pub hir_struct_rank_block_prefix_b: LaniusBuffer<u32>,
    pub hir_struct_rank_node: LaniusBuffer<u32>,
    pub hir_struct_rank_count: LaniusBuffer<u32>,
    pub hir_struct_rank_dispatch_args: LaniusBuffer<u32>,
}
