// src/type_checker/record/module_paths.rs

use super::*;

/// Records module, import, declaration, path, and projection relation passes.
pub(in crate::type_checker) fn record_module_path_state_with_passes(
    passes: &TypeCheckPasses,
    encoder: &mut wgpu::CommandEncoder,
    state: &ModulePathState,
    hir_active_dispatch_args: &wgpu::Buffer,
    mut timer: Option<&mut crate::gpu::timer::GpuTimer>,
) -> Result<()> {
    let hir_work = state.n_blocks.saturating_mul(256).max(1);
    let parser_hir_work = state.parser_hir_n_blocks.saturating_mul(256).max(1);
    let module_work = state.module_n_blocks.saturating_mul(256).max(1);
    let record_n_blocks = state.record_n_blocks.max(1);
    let file_map_clear_work = hir_work;

    record_compute_indirect(
        encoder,
        &passes.modules_mark_records,
        &state.bind_groups.mark_records,
        "type_check.modules.mark_records",
        hir_active_dispatch_args,
    )?;
    stamp_typecheck_timer(&mut timer, encoder, "typecheck.modules.mark_records.done");
    record_compute_indirect(
        encoder,
        &passes.modules_extract_record_flag,
        &state.bind_groups.extract_path_record_flag,
        "type_check.modules.extract_path_record_flag",
        hir_active_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        state.n_blocks,
        hir_active_dispatch_args,
        &state.bind_groups.path_scan,
        "type_check.modules.path_record_scan",
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_paths,
        &state.bind_groups.scatter_paths,
        "type_check.modules.scatter_paths",
        hir_active_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.count_dispatch_args,
        &state.bind_groups.path_dispatch_args,
        "type_check.modules.path_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_count_path_segments,
        &state.bind_groups.count_path_segments,
        "type_check.modules.count_path_segments",
        &state.path_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.path_dispatch_args,
        &state.bind_groups.path_segment_scan,
        "type_check.modules.path_segment_scan",
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_path_segments,
        &state.bind_groups.scatter_path_segments,
        "type_check.modules.scatter_path_segments",
        &state.path_dispatch_args,
    )?;
    stamp_typecheck_timer(&mut timer, encoder, "typecheck.modules.paths.done");
    record_compute_indirect(
        encoder,
        &passes.modules_extract_record_flag,
        &state.bind_groups.extract_module_record_flag,
        "type_check.modules.extract_module_record_flag",
        hir_active_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        state.n_blocks,
        hir_active_dispatch_args,
        &state.bind_groups.module_scan,
        "type_check.modules.module_record_scan",
    )?;
    record_compute(
        encoder,
        &passes.modules_scatter_module_records,
        &state.bind_groups.scatter_module_records,
        "type_check.modules.scatter_module_records",
        hir_work.max(module_work),
    )?;
    let module_key_work = state
        .module_n_blocks
        .saturating_mul(256)
        .saturating_mul(MODULE_KEY_SEGMENT_ROW_WIDTH as u32)
        .max(1);
    record_compute(
        encoder,
        &passes.modules_build_module_keys,
        &state.bind_groups.build_module_keys,
        "type_check.modules.build_module_keys",
        module_key_work,
    )?;
    record_compute(
        encoder,
        &passes.names_radix_dispatch_args,
        &state.bind_groups.module_key_radix_dispatch,
        "type_check.modules.module_key_radix_dispatch_args",
        1,
    )?;
    for i in 0..state.bind_groups.sort_module_key_scatter.len() {
        record_compute_indirect(
            encoder,
            &passes.modules_sort_module_keys_histogram,
            &state.bind_groups.sort_module_key_histogram[i],
            "type_check.modules.sort_module_keys_histogram",
            &state.module_key_radix_dispatch_args,
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_prefix,
            &state.bind_groups.sort_module_key_bucket_prefix[i],
            "type_check.modules.sort_module_keys_bucket_prefix",
            NAME_RADIX_BUCKETS.saturating_mul(256),
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_bases,
            &state.bind_groups.sort_module_key_bucket_bases[i],
            "type_check.modules.sort_module_keys_bucket_bases",
            256,
        )?;
        record_compute_indirect(
            encoder,
            &passes.modules_sort_module_keys_scatter,
            &state.bind_groups.sort_module_key_scatter[i],
            "type_check.modules.sort_module_keys_scatter",
            &state.module_key_radix_dispatch_args,
        )?;
    }
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.sort_module_keys.done",
    );
    record_compute_indirect(
        encoder,
        &passes.modules_validate_modules,
        &state.bind_groups.validate_modules,
        "type_check.modules.validate_modules",
        &state.module_key_radix_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.modules_clear_file_module_map,
        &state.bind_groups.clear_file_module_map,
        "type_check.modules.clear_file_module_map",
        file_map_clear_work,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_build_file_module_map,
        &state.bind_groups.build_file_module_map,
        "type_check.modules.build_file_module_map",
        &state.module_key_radix_dispatch_args,
    )?;
    stamp_typecheck_timer(&mut timer, encoder, "typecheck.modules.module_maps.done");
    record_compute_indirect(
        encoder,
        &passes.modules_extract_record_flag,
        &state.bind_groups.extract_import_record_flag,
        "type_check.modules.extract_import_record_flag",
        hir_active_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        state.n_blocks,
        hir_active_dispatch_args,
        &state.bind_groups.import_scan,
        "type_check.modules.import_record_scan",
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_import_records,
        &state.bind_groups.scatter_import_records,
        "type_check.modules.scatter_import_records",
        hir_active_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.count_dispatch_args,
        &state.bind_groups.import_dispatch_args,
        "type_check.modules.import_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_extract_record_flag,
        &state.bind_groups.extract_decl_record_flag,
        "type_check.modules.extract_decl_record_flag",
        hir_active_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        state.n_blocks,
        hir_active_dispatch_args,
        &state.bind_groups.decl_scan,
        "type_check.modules.decl_record_scan",
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_decl_core_records,
        &state.bind_groups.scatter_decl_core_records,
        "type_check.modules.scatter_decl_core_records",
        hir_active_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.modules_clear_decl_lookup,
        &state.bind_groups.clear_decl_lookup,
        "type_check.modules.clear_decl_lookup",
        state.token_capacity.max(1),
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_decl_span_records,
        &state.bind_groups.scatter_decl_span_records,
        "type_check.modules.scatter_decl_span_records",
        hir_active_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_attach_record_modules,
        &state.bind_groups.attach_record_modules,
        "type_check.modules.attach_record_modules",
        hir_active_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_imports,
        &state.bind_groups.resolve_imports,
        "type_check.modules.resolve_imports",
        &state.import_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.names_radix_dispatch_args,
        &state.bind_groups.import_edge_key_radix_dispatch,
        "type_check.modules.import_edge_key_radix_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_seed_import_edge_key_order,
        &state.bind_groups.seed_import_edge_key_order,
        "type_check.modules.seed_import_edge_key_order",
        &state.import_edge_key_radix_dispatch_args,
    )?;
    for i in 0..state.bind_groups.sort_import_edge_key_scatter.len() {
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_edges,
            &state.bind_groups.sort_import_edge_key_histogram[i],
            "type_check.modules.sort_import_edges_histogram",
            &state.import_edge_key_radix_dispatch_args,
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_prefix,
            &state.bind_groups.sort_import_edge_key_bucket_prefix[i],
            "type_check.modules.sort_import_edges_bucket_prefix",
            NAME_RADIX_BUCKETS.saturating_mul(256),
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_bases,
            &state.bind_groups.sort_import_edge_key_bucket_bases[i],
            "type_check.modules.sort_import_edges_bucket_bases",
            256,
        )?;
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_edges_scatter,
            &state.bind_groups.sort_import_edge_key_scatter[i],
            "type_check.modules.sort_import_edges_scatter",
            &state.import_edge_key_radix_dispatch_args,
        )?;
    }
    record_compute_indirect(
        encoder,
        &passes.modules_validate_import_cycles,
        &state.bind_groups.validate_import_cycles,
        "type_check.modules.validate_import_cycles",
        &state.import_edge_key_radix_dispatch_args,
    )?;
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.record_scans_and_import_decl_records.done",
    );
    record_compute(
        encoder,
        &passes.names_radix_dispatch_args,
        &state.bind_groups.decl_key_radix_dispatch,
        "type_check.modules.decl_key_radix_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_seed_decl_key_order,
        &state.bind_groups.seed_decl_key_order,
        "type_check.modules.seed_decl_key_order",
        &state.decl_key_radix_dispatch_args,
    )?;
    for i in 0..state.bind_groups.sort_decl_key_scatter.len() {
        record_compute_indirect(
            encoder,
            &passes.modules_sort_decl_keys,
            &state.bind_groups.sort_decl_key_histogram[i],
            "type_check.modules.sort_decl_keys_histogram",
            &state.decl_key_radix_dispatch_args,
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_prefix,
            &state.bind_groups.sort_decl_key_bucket_prefix[i],
            "type_check.modules.sort_decl_keys_bucket_prefix",
            NAME_RADIX_BUCKETS.saturating_mul(256),
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_bases,
            &state.bind_groups.sort_decl_key_bucket_bases[i],
            "type_check.modules.sort_decl_keys_bucket_bases",
            256,
        )?;
        record_compute_indirect(
            encoder,
            &passes.modules_sort_decl_keys_scatter,
            &state.bind_groups.sort_decl_key_scatter[i],
            "type_check.modules.sort_decl_keys_scatter",
            &state.decl_key_radix_dispatch_args,
        )?;
    }
    stamp_typecheck_timer(&mut timer, encoder, "typecheck.modules.sort_decl_keys.done");
    record_compute_indirect(
        encoder,
        &passes.modules_validate_decls,
        &state.bind_groups.validate_decls,
        "type_check.modules.validate_decls",
        &state.decl_key_radix_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_mark_decl_namespace_keys,
        &state.bind_groups.mark_decl_namespace_keys,
        "type_check.modules.mark_decl_namespace_keys",
        &state.decl_key_radix_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.decl_key_radix_dispatch_args,
        &state.bind_groups.decl_type_key_scan,
        "type_check.modules.decl_type_key_scan",
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.decl_key_radix_dispatch_args,
        &state.bind_groups.decl_value_key_scan,
        "type_check.modules.decl_value_key_scan",
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_decl_namespace_keys,
        &state.bind_groups.scatter_decl_namespace_keys,
        "type_check.modules.scatter_decl_namespace_keys",
        &state.decl_key_radix_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_mark_public_decl_keys,
        &state.bind_groups.mark_public_decl_keys,
        "type_check.modules.mark_public_decl_keys",
        &state.decl_key_radix_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.decl_key_radix_dispatch_args,
        &state.bind_groups.decl_type_public_scan,
        "type_check.modules.decl_type_public_scan",
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.decl_key_radix_dispatch_args,
        &state.bind_groups.decl_value_public_scan,
        "type_check.modules.decl_value_public_scan",
    )?;
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.decl_namespace_keys.done",
    );
    record_compute_indirect(
        encoder,
        &passes.modules_count_import_visibility,
        &state.bind_groups.count_import_visibility,
        "type_check.modules.count_import_visibility",
        &state.import_dispatch_args,
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.import_dispatch_args,
        &state.bind_groups.import_visible_type_scan,
        "type_check.modules.import_visible_type_scan",
    )?;
    record_counted_u32_scan_bind_groups_with_passes(
        passes,
        encoder,
        record_n_blocks,
        &state.import_dispatch_args,
        &state.bind_groups.import_visible_value_scan,
        "type_check.modules.import_visible_value_scan",
    )?;
    record_compute(
        encoder,
        &passes.names_radix_dispatch_args,
        &state.bind_groups.import_visible_type_key_radix_dispatch,
        "type_check.modules.import_visible_type_key_radix_dispatch_args",
        1,
    )?;
    record_compute(
        encoder,
        &passes.names_radix_dispatch_args,
        &state.bind_groups.import_visible_value_key_radix_dispatch,
        "type_check.modules.import_visible_value_key_radix_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_import_visibility,
        &state.bind_groups.scatter_import_visible_type,
        "type_check.modules.scatter_import_visible_type",
        &state.import_visible_type_key_radix_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_scatter_import_visibility,
        &state.bind_groups.scatter_import_visible_value,
        "type_check.modules.scatter_import_visible_value",
        &state.import_visible_value_key_radix_dispatch_args,
    )?;
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.import_visibility_scatter.done",
    );
    for i in 0..state.bind_groups.sort_import_visible_type_key_scatter.len() {
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_visible_keys,
            &state.bind_groups.sort_import_visible_type_key_histogram[i],
            "type_check.modules.sort_import_visible_type_keys_histogram",
            &state.import_visible_type_key_radix_dispatch_args,
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_prefix,
            &state.bind_groups.sort_import_visible_type_key_bucket_prefix[i],
            "type_check.modules.sort_import_visible_type_keys_bucket_prefix",
            NAME_RADIX_BUCKETS.saturating_mul(256),
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_bases,
            &state.bind_groups.sort_import_visible_type_key_bucket_bases[i],
            "type_check.modules.sort_import_visible_type_keys_bucket_bases",
            256,
        )?;
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_visible_keys_scatter,
            &state.bind_groups.sort_import_visible_type_key_scatter[i],
            "type_check.modules.sort_import_visible_type_keys_scatter",
            &state.import_visible_type_key_radix_dispatch_args,
        )?;
    }
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.sort_import_visible_type_keys.done",
    );
    for i in 0..state
        .bind_groups
        .sort_import_visible_value_key_scatter
        .len()
    {
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_visible_keys,
            &state.bind_groups.sort_import_visible_value_key_histogram[i],
            "type_check.modules.sort_import_visible_value_keys_histogram",
            &state.import_visible_value_key_radix_dispatch_args,
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_prefix,
            &state
                .bind_groups
                .sort_import_visible_value_key_bucket_prefix[i],
            "type_check.modules.sort_import_visible_value_keys_bucket_prefix",
            NAME_RADIX_BUCKETS.saturating_mul(256),
        )?;
        record_compute(
            encoder,
            &passes.names_radix_bucket_bases,
            &state.bind_groups.sort_import_visible_value_key_bucket_bases[i],
            "type_check.modules.sort_import_visible_value_keys_bucket_bases",
            256,
        )?;
        record_compute_indirect(
            encoder,
            &passes.modules_sort_import_visible_keys_scatter,
            &state.bind_groups.sort_import_visible_value_key_scatter[i],
            "type_check.modules.sort_import_visible_value_keys_scatter",
            &state.import_visible_value_key_radix_dispatch_args,
        )?;
    }
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.sort_import_visible_value_keys.done",
    );
    record_compute_indirect(
        encoder,
        &passes.modules_build_import_visible_key_tables,
        &state.bind_groups.build_import_visible_type_key_table,
        "type_check.modules.build_import_visible_type_key_table",
        &state.import_visible_type_key_radix_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_build_import_visible_key_tables,
        &state.bind_groups.build_import_visible_value_key_table,
        "type_check.modules.build_import_visible_value_key_table",
        &state.import_visible_value_key_radix_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.count_pair_max_dispatch_args,
        &state.bind_groups.import_visible_validate_dispatch_args,
        "type_check.modules.import_visible_validate_dispatch_args",
        1,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_validate_import_visible_keys,
        &state.bind_groups.initialize_import_visible_keys,
        "type_check.modules.initialize_import_visible_keys",
        &state.import_visible_validate_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_validate_import_visible_keys,
        &state.bind_groups.validate_import_visible_keys,
        "type_check.modules.validate_import_visible_keys",
        &state.import_visible_validate_dispatch_args,
    )?;
    stamp_typecheck_timer(
        &mut timer,
        encoder,
        "typecheck.modules.import_visible_tables.done",
    );
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_local_paths,
        &state.bind_groups.resolve_local_type_paths,
        "type_check.modules.resolve_local_type_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_local_paths,
        &state.bind_groups.resolve_local_value_paths,
        "type_check.modules.resolve_local_value_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_imported_paths,
        &state.bind_groups.resolve_imported_type_paths,
        "type_check.modules.resolve_imported_type_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_imported_paths,
        &state.bind_groups.resolve_imported_value_paths,
        "type_check.modules.resolve_imported_value_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_qualified_paths,
        &state.bind_groups.resolve_qualified_type_paths,
        "type_check.modules.resolve_qualified_type_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_resolve_qualified_paths,
        &state.bind_groups.resolve_qualified_value_paths,
        "type_check.modules.resolve_qualified_value_paths",
        &state.path_dispatch_args,
    )?;
    stamp_typecheck_timer(&mut timer, encoder, "typecheck.modules.resolve_paths.done");
    record_compute(
        encoder,
        &passes.modules_clear_type_path_types,
        &state.bind_groups.clear_type_path_types,
        "type_check.modules.clear_type_path_types",
        state.token_capacity.max(1),
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_project_type_paths,
        &state.bind_groups.project_type_paths,
        "type_check.modules.project_type_paths",
        &state.path_dispatch_args,
    )?;
    record_compute(
        encoder,
        &passes.modules_mark_value_call_paths,
        &state.bind_groups.mark_value_call_paths,
        "type_check.modules.mark_value_call_paths",
        parser_hir_work,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_project_value_paths,
        &state.bind_groups.project_value_paths,
        "type_check.modules.project_value_paths",
        &state.path_dispatch_args,
    )?;
    record_compute_indirect(
        encoder,
        &passes.modules_validate_type_paths,
        &state.bind_groups.validate_type_paths,
        "type_check.modules.validate_type_paths",
        &state.path_dispatch_args,
    )
}
