import Lanius.Extraction.VerifiedFrontend.Surface.TokenScan.Parse.View.Assembly
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_nodes_cached_chunk verifiedFrontendTokenScan_nodes_0_trace_checked_kernel,
  verifiedFrontendTokenScan_nodes_0_trace_length_kernel for
  verifiedFrontendTokenScanArtifact, verifiedFrontendTokenScanParseView, 0, 651
end Lanius.Extraction
