import Lanius.Extraction.VerifiedFrontend.Surface.TokenScan.View
import Lanius.Extraction.ParseChunks

namespace Lanius.Extraction

set_option maxRecDepth 500000
set_option maxHeartbeats 0

kernel_parse_nodes_cached_chunk verifiedFrontendTokenScan_nodes_2_trace_checked_kernel,
  verifiedFrontendTokenScan_nodes_2_trace_length_kernel for
  verifiedFrontendTokenScanArtifact, verifiedFrontendTokenScanParseView, 434, 217

end Lanius.Extraction
