-- This file is generated by `cargo run -p laniusc-formal-export --bin generate-lean-grammar`.
-- Its checked-in contents are part of the trusted formal grammar.
import Lanius.Extraction.Grammar

namespace Lanius.Extraction

def laniusGrammar : Grammar := {
  n_kinds := 191
  n_nonterminals := 136
  start_nonterminal := 48
  split_token_kind := 44
  split_component_kind := 13
  canonical_kinds := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 4, 4, 20, 20, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 6, 6, 27, 27, 5, 5, 21, 21, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 4, 5, 1, 1, 1, 8, 36, 36, 36, 20, 21, 37, 22, 23, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 8, 38, 38, 1, 8, 8, 75, 113, 38, 56, 56, 57, 57, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 22, 23, 12, 13, 12, 13, 36, 36, 36, 36, 36, 4, 5, 4, 5, 25, 6, 37, 66, 66, 22, 23, 22, 23, 1, 1, 1, 1, 36, 36, 36, 36, 32, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 100, 105, 1, 12, 13, 36, 105, 25, 98, 98, 182, 1, 12, 13, 36, 1, 32, 189, 8]
  productions := [
    ⟨48, [253]⟩, -- production 0
    ⟨62, [252, 253]⟩, -- production 1
    ⟨62, []⟩, -- production 2
    ⟨61, [66, 283]⟩, -- production 3
    ⟨61, [241]⟩, -- production 4
    ⟨61, [238]⟩, -- production 5
    ⟨61, [250]⟩, -- production 6
    ⟨61, [260]⟩, -- production 7
    ⟨61, [309]⟩, -- production 8
    ⟨61, [246]⟩, -- production 9
    ⟨61, [305]⟩, -- production 10
    ⟨50, [67, 1, 225, 76, 266, 77, 289, 323, 240]⟩, -- production 11
    ⟨49, [149, 295, 150]⟩, -- production 12
    ⟨54, [67, 1, 225, 76, 266, 77, 289, 323, 244]⟩, -- production 13
    ⟨53, [151, 295, 152]⟩, -- production 14
    ⟨47, [102, 237, 67, 1, 225, 76, 266, 77, 289, 323, 164]⟩, -- production 15
    ⟨118, [103, 153, 225, 323, 110, 315, 165]⟩, -- production 16
    ⟨55, [180, 225, 315, 323, 121, 248, 122]⟩, -- production 17
    ⟨55, [181, 225, 315, 172, 315, 323, 121, 248, 122]⟩, -- production 18
    ⟨57, []⟩, -- production 19
    ⟨57, [247, 249]⟩, -- production 20
    ⟨56, [245]⟩, -- production 21
    ⟨56, [147, 245]⟩, -- production 22
    ⟨58, [247, 249]⟩, -- production 23
    ⟨58, []⟩, -- production 24
    ⟨114, [99, 154, 225, 323, 123, 307, 124]⟩, -- production 25
    ⟨116, []⟩, -- production 26
    ⟨116, [306, 308]⟩, -- production 27
    ⟨115, [67, 1, 225, 76, 266, 77, 289, 323, 146]⟩, -- production 28
    ⟨115, [148, 67, 1, 225, 76, 266, 77, 289, 323, 146]⟩, -- production 29
    ⟨117, [306, 308]⟩, -- production 30
    ⟨117, []⟩, -- production 31
    ⟨46, [188]⟩, -- production 32
    ⟨46, []⟩, -- production 33
    ⟨98, [112, 315]⟩, -- production 34
    ⟨98, []⟩, -- production 35
    ⟨132, []⟩, -- production 36
    ⟨132, [104, 324, 325]⟩, -- production 37
    ⟨133, [156, 107, 316]⟩, -- production 38
    ⟨134, [157, 326]⟩, -- production 39
    ⟨134, []⟩, -- production 40
    ⟨135, [324, 325]⟩, -- production 41
    ⟨135, []⟩, -- production 42
    ⟨59, [96, 251]⟩, -- production 43
    ⟨60, [269, 162]⟩, -- production 44
    ⟨60, [161, 162]⟩, -- production 45
    ⟨69, [97, 269, 163]⟩, -- production 46
    ⟨78, [270, 271]⟩, -- production 47
    ⟨79, [1]⟩, -- production 48
    ⟨79, [187, 184, 315, 272, 185]⟩, -- production 49
    ⟨80, [114, 114, 270, 271]⟩, -- production 50
    ⟨80, []⟩, -- production 51
    ⟨81, [186, 273]⟩, -- production 52
    ⟨81, []⟩, -- production 53
    ⟨82, [315, 272]⟩, -- production 54
    ⟨82, []⟩, -- production 55
    ⟨128, [320, 321]⟩, -- production 56
    ⟨129, [80]⟩, -- production 57
    ⟨130, [114, 114, 320, 321]⟩, -- production 58
    ⟨130, []⟩, -- production 59
    ⟨75, []⟩, -- production 60
    ⟨75, [265, 267]⟩, -- production 61
    ⟨74, [79, 108, 315]⟩, -- production 62
    ⟨74, [173, 291]⟩, -- production 63
    ⟨74, [144, 178]⟩, -- production 64
    ⟨100, [108, 315]⟩, -- production 65
    ⟨100, []⟩, -- production 66
    ⟨76, [84, 268]⟩, -- production 67
    ⟨76, []⟩, -- production 68
    ⟨124, [319, 312]⟩, -- production 69
    ⟨124, [85, 315, 314]⟩, -- production 70
    ⟨18, [22, 295, 23]⟩, -- production 71
    ⟨52, [88, 295, 89]⟩, -- production 72
    ⟨104, [294, 295]⟩, -- production 73
    ⟨104, []⟩, -- production 74
    ⟨103, [68, 78, 255, 254, 167]⟩, -- production 75
    ⟨103, [69, 290, 168]⟩, -- production 76
    ⟨103, [70, 29, 236, 62, 243, 220]⟩, -- production 77
    ⟨29, [71, 209]⟩, -- production 78
    ⟨29, []⟩, -- production 79
    ⟨103, [72, 29, 236, 62, 209]⟩, -- production 80
    ⟨103, [100, 1, 101, 242, 209]⟩, -- production 81
    ⟨103, [73, 170]⟩, -- production 82
    ⟨103, [74, 171]⟩, -- production 83
    ⟨103, [209]⟩, -- production 84
    ⟨103, [236, 169]⟩, -- production 85
    ⟨64, [108, 315]⟩, -- production 86
    ⟨64, []⟩, -- production 87
    ⟨63, [81, 236]⟩, -- production 88
    ⟨63, []⟩, -- production 89
    ⟨99, [236]⟩, -- production 90
    ⟨99, []⟩, -- production 91
    ⟨51, [269]⟩, -- production 92
    ⟨51, [287, 288]⟩, -- production 93
    ⟨51, [182, 286]⟩, -- production 94
    ⟨51, [189, 190, 284]⟩, -- production 95
    ⟨96, [2]⟩, -- production 96
    ⟨97, [182, 286]⟩, -- production 97
    ⟨97, [189, 190, 284]⟩, -- production 98
    ⟨93, [285, 280]⟩, -- production 99
    ⟨93, [2]⟩, -- production 100
    ⟨94, [183]⟩, -- production 101
    ⟨95, [284]⟩, -- production 102
    ⟨95, []⟩, -- production 103
    ⟨45, [201]⟩, -- production 104
    ⟨10, [263, 202]⟩, -- production 105
    ⟨11, [8, 201]⟩, -- production 106
    ⟨11, [46, 201]⟩, -- production 107
    ⟨11, [47, 201]⟩, -- production 108
    ⟨11, [48, 201]⟩, -- production 109
    ⟨11, [49, 201]⟩, -- production 110
    ⟨11, [50, 201]⟩, -- production 111
    ⟨11, [51, 201]⟩, -- production 112
    ⟨11, [52, 201]⟩, -- production 113
    ⟨11, [53, 201]⟩, -- production 114
    ⟨11, [54, 201]⟩, -- production 115
    ⟨11, [55, 201]⟩, -- production 116
    ⟨11, []⟩, -- production 117
    ⟨72, [193, 264]⟩, -- production 118
    ⟨73, [18, 193, 264]⟩, -- production 119
    ⟨73, []⟩, -- production 120
    ⟨2, [205, 194]⟩, -- production 121
    ⟨3, [17, 205, 194]⟩, -- production 122
    ⟨3, []⟩, -- production 123
    ⟨14, [207, 206]⟩, -- production 124
    ⟨15, [26, 207, 206]⟩, -- production 125
    ⟨15, []⟩, -- production 126
    ⟨16, [203, 208]⟩, -- production 127
    ⟨17, [42, 203, 208]⟩, -- production 128
    ⟨17, []⟩, -- production 129
    ⟨12, [234, 204]⟩, -- production 130
    ⟨13, [25, 234, 204]⟩, -- production 131
    ⟨13, []⟩, -- production 132
    ⟨43, [217, 235]⟩, -- production 133
    ⟨44, [16, 217, 235]⟩, -- production 134
    ⟨44, [40, 217, 235]⟩, -- production 135
    ⟨44, []⟩, -- production 136
    ⟨26, [292, 218]⟩, -- production 137
    ⟨27, [12, 292, 218]⟩, -- production 138
    ⟨27, [13, 292, 218]⟩, -- production 139
    ⟨27, [14, 292, 218]⟩, -- production 140
    ⟨27, [15, 292, 218]⟩, -- production 141
    ⟨27, []⟩, -- production 142
    ⟨101, [191, 293]⟩, -- production 143
    ⟨102, [43, 191, 293]⟩, -- production 144
    ⟨102, [44, 191, 293]⟩, -- production 145
    ⟨102, []⟩, -- production 146
    ⟨0, [261, 192]⟩, -- production 147
    ⟨1, [59, 261, 192]⟩, -- production 148
    ⟨1, [61, 261, 192]⟩, -- production 149
    ⟨1, []⟩, -- production 150
    ⟨70, [322, 262]⟩, -- production 151
    ⟨71, [7, 322, 262]⟩, -- production 152
    ⟨71, [9, 322, 262]⟩, -- production 153
    ⟨71, [41, 322, 262]⟩, -- production 154
    ⟨71, []⟩, -- production 155
    ⟨131, [58, 322]⟩, -- production 156
    ⟨131, [60, 322]⟩, -- production 157
    ⟨131, [19, 322]⟩, -- production 158
    ⟨131, [279]⟩, -- production 159
    ⟨88, [281, 280]⟩, -- production 160
    ⟨89, [28, 195, 63, 280]⟩, -- production 161
    ⟨89, [30, 236, 65, 280]⟩, -- production 162
    ⟨89, [35, 109, 280]⟩, -- production 163
    ⟨89, []⟩, -- production 164
    ⟨4, []⟩, -- production 165
    ⟨4, [236, 196]⟩, -- production 166
    ⟨5, [82, 197]⟩, -- production 167
    ⟨5, []⟩, -- production 168
    ⟨6, [236, 196]⟩, -- production 169
    ⟨6, []⟩, -- production 170
    ⟨90, [31, 198, 64]⟩, -- production 171
    ⟨90, [29, 236, 62]⟩, -- production 172
    ⟨90, [269, 282]⟩, -- production 173
    ⟨90, [105]⟩, -- production 174
    ⟨90, [2]⟩, -- production 175
    ⟨90, [33]⟩, -- production 176
    ⟨90, [32]⟩, -- production 177
    ⟨90, [34]⟩, -- production 178
    ⟨7, []⟩, -- production 179
    ⟨7, [236, 199]⟩, -- production 180
    ⟨8, [83, 200]⟩, -- production 181
    ⟨8, []⟩, -- production 182
    ⟨9, [236, 199]⟩, -- production 183
    ⟨9, []⟩, -- production 184
    ⟨90, [90]⟩, -- production 185
    ⟨90, [91]⟩, -- production 186
    ⟨90, [95, 29, 236, 62, 119, 257, 120]⟩, -- production 187
    ⟨66, []⟩, -- production 188
    ⟨66, [256, 258]⟩, -- production 189
    ⟨65, [274, 113, 236]⟩, -- production 190
    ⟨67, [138, 259]⟩, -- production 191
    ⟨67, []⟩, -- production 192
    ⟨68, [256, 258]⟩, -- production 193
    ⟨68, []⟩, -- production 194
    ⟨83, [269, 275]⟩, -- production 195
    ⟨83, [2]⟩, -- production 196
    ⟨83, [90]⟩, -- production 197
    ⟨83, [91]⟩, -- production 198
    ⟨84, []⟩, -- production 199
    ⟨84, [140, 276, 141]⟩, -- production 200
    ⟨85, []⟩, -- production 201
    ⟨85, [274, 277]⟩, -- production 202
    ⟨86, [139, 278]⟩, -- production 203
    ⟨86, []⟩, -- production 204
    ⟨87, [274, 277]⟩, -- production 205
    ⟨87, []⟩, -- production 206
    ⟨61, [219]⟩, -- production 207
    ⟨28, [92, 1, 108, 315, 111, 236, 166]⟩, -- production 208
    ⟨61, [221]⟩, -- production 209
    ⟨30, [93, 1, 225, 323, 129, 230, 130]⟩, -- production 210
    ⟨39, []⟩, -- production 211
    ⟨39, [226, 232]⟩, -- production 212
    ⟨35, [1, 231]⟩, -- production 213
    ⟨40, []⟩, -- production 214
    ⟨40, [142, 227, 143]⟩, -- production 215
    ⟨36, []⟩, -- production 216
    ⟨36, [315, 228]⟩, -- production 217
    ⟨37, [137, 229]⟩, -- production 218
    ⟨37, []⟩, -- production 219
    ⟨38, [315, 228]⟩, -- production 220
    ⟨38, []⟩, -- production 221
    ⟨41, [158, 233]⟩, -- production 222
    ⟨41, []⟩, -- production 223
    ⟨42, [226, 232]⟩, -- production 224
    ⟨42, []⟩, -- production 225
    ⟨121, []⟩, -- production 226
    ⟨121, [131, 315, 310, 132]⟩, -- production 227
    ⟨119, [135, 311]⟩, -- production 228
    ⟨119, []⟩, -- production 229
    ⟨120, [315, 310]⟩, -- production 230
    ⟨120, []⟩, -- production 231
    ⟨34, []⟩, -- production 232
    ⟨34, [133, 222, 223, 134]⟩, -- production 233
    ⟨31, [155, 317]⟩, -- production 234
    ⟨31, [92, 1, 108, 315]⟩, -- production 235
    ⟨126, [107, 316]⟩, -- production 236
    ⟨126, []⟩, -- production 237
    ⟨125, [213, 318]⟩, -- production 238
    ⟨127, [145, 213, 318]⟩, -- production 239
    ⟨127, []⟩, -- production 240
    ⟨22, [214, 212]⟩, -- production 241
    ⟨22, [179, 213]⟩, -- production 242
    ⟨23, [215, 216]⟩, -- production 243
    ⟨24, [174]⟩, -- production 244
    ⟨25, [114, 114, 215, 216]⟩, -- production 245
    ⟨25, []⟩, -- production 246
    ⟨21, []⟩, -- production 247
    ⟨21, [175, 213, 210, 176]⟩, -- production 248
    ⟨19, [177, 211]⟩, -- production 249
    ⟨19, []⟩, -- production 250
    ⟨20, [213, 210]⟩, -- production 251
    ⟨20, []⟩, -- production 252
    ⟨32, [136, 224]⟩, -- production 253
    ⟨32, []⟩, -- production 254
    ⟨33, [222, 223]⟩, -- production 255
    ⟨33, []⟩, -- production 256
    ⟨61, [300]⟩, -- production 257
    ⟨109, [94, 1, 225, 323, 127, 297, 128]⟩, -- production 258
    ⟨106, []⟩, -- production 259
    ⟨106, [296, 298]⟩, -- production 260
    ⟨105, [1, 108, 315]⟩, -- production 261
    ⟨107, [159, 299]⟩, -- production 262
    ⟨107, []⟩, -- production 263
    ⟨108, [296, 298]⟩, -- production 264
    ⟨108, []⟩, -- production 265
    ⟨92, [241]⟩, -- production 266
    ⟨92, [238]⟩, -- production 267
    ⟨92, [219]⟩, -- production 268
    ⟨92, [309]⟩, -- production 269
    ⟨92, [221]⟩, -- production 270
    ⟨92, [300]⟩, -- production 271
    ⟨92, [246]⟩, -- production 272
    ⟨92, [305]⟩, -- production 273
    ⟨91, []⟩, -- production 274
    ⟨91, [125, 302, 126]⟩, -- production 275
    ⟨111, []⟩, -- production 276
    ⟨111, [301, 303]⟩, -- production 277
    ⟨110, [1, 38, 236]⟩, -- production 278
    ⟨112, [160, 304]⟩, -- production 279
    ⟨112, []⟩, -- production 280
    ⟨113, [301, 303]⟩, -- production 281
    ⟨113, []⟩, -- production 282
    ⟨123, [87, 313, 86]⟩, -- production 283
    ⟨123, [86]⟩, -- production 284
    ⟨124, [144, 315]⟩, -- production 285
    ⟨122, [2]⟩, -- production 286
    ⟨122, [1]⟩, -- production 287
    ⟨77, [265, 267]⟩, -- production 288
    ⟨77, []⟩, -- production 289
  ]
}

end Lanius.Extraction
