import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensOrigins
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensView
import Lanius.Extraction.KernelSurfacePhases
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
theorem verifiedFrontendCanonicalTokens_origin_spellings_checked_kernel :
    spellingOriginPathsValid verifiedFrontendCanonicalTokensArtifact verifiedFrontendCanonicalTokensView
      (verifiedFrontendCanonicalTokensOrigins).claims.spellings (verifiedFrontendCanonicalTokensOrigins).spellingPaths = true := by
  with_unfolding_all rfl
end Lanius.Extraction
