import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes0
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes1
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes2
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes3
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes4
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes5
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes6
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes7
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes8
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes9
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes10

namespace Lanius.Extraction
def verifiedFrontendCanonicalTokensParseNodes : List ParseNode :=
  verifiedFrontendCanonicalTokensParseNodes0 ++ (verifiedFrontendCanonicalTokensParseNodes1 ++ (verifiedFrontendCanonicalTokensParseNodes2 ++ (verifiedFrontendCanonicalTokensParseNodes3 ++ (verifiedFrontendCanonicalTokensParseNodes4 ++ (verifiedFrontendCanonicalTokensParseNodes5 ++ (verifiedFrontendCanonicalTokensParseNodes6 ++ (verifiedFrontendCanonicalTokensParseNodes7 ++ (verifiedFrontendCanonicalTokensParseNodes8 ++ (verifiedFrontendCanonicalTokensParseNodes9 ++ (verifiedFrontendCanonicalTokensParseNodes10))))))))))
end Lanius.Extraction
