import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensParseView
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_nodes_cached_chunk verifiedFrontendCanonicalTokens_nodes_10_trace_checked_kernel,
  verifiedFrontendCanonicalTokens_nodes_10_trace_length_kernel for
  verifiedFrontendCanonicalTokensArtifact, verifiedFrontendCanonicalTokensParseView, 10000, 311
end Lanius.Extraction
