import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenParseTokenHeader
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenParseTokenRaw
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenParseTokenCanonical
namespace Lanius.Extraction
theorem verifiedFrontendToken_token_trace_checked_kernel :
    checkTokenArtifact verifiedFrontendTokenArtifact = true :=
  checkTokenArtifact_of_trace_phases
    verifiedFrontendToken_token_header_trace_checked_kernel
    verifiedFrontendToken_token_raw_trace_checked_kernel
    verifiedFrontendToken_token_canonical_trace_checked_kernel
end Lanius.Extraction
