import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenClaims
import Lanius.Extraction.VerifiedFrontendPackOrigins
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_origins verifiedFrontendToken_origin_claims_equal_kernel,
  verifiedFrontendToken_origin_ids_dense_kernel,
  verifiedFrontendToken_node_origins_checked_kernel,
  verifiedFrontendToken_spelling_origins_checked_kernel,
  verifiedFrontendToken_origin_coverage_checked_kernel,
  verifiedFrontendToken_origins_checked_kernel for
  verifiedFrontendTokenArtifact, verifiedFrontendTokenView,
  verifiedFrontendTokenOrigins, verifiedFrontendTokenClaims

end Lanius.Extraction
