import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolParseView
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
kernel_parse_nodes_cached_chunk verifiedFrontendSymbol_nodes_5_trace_checked_kernel,
  verifiedFrontendSymbol_nodes_5_trace_length_kernel for
  verifiedFrontendSymbolArtifact, verifiedFrontendSymbolParseView, 7500, 744
end Lanius.Extraction
