import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenCoverage
namespace Lanius.Extraction
theorem verifiedFrontendToken_origins_checked_kernel :
    (verifiedFrontendTokenOrigins).valid verifiedFrontendTokenArtifact verifiedFrontendTokenView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendTokenView verifiedFrontendTokenOrigins
    verifiedFrontendToken_ids_dense_kernel verifiedFrontendToken_origin_nodes_checked_kernel
    verifiedFrontendToken_origin_spellings_checked_kernel verifiedFrontendToken_coverage_checked_kernel
end Lanius.Extraction
