import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerParseTokenHeader
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerParseTokenRaw
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerParseTokenCanonical
namespace Lanius.Extraction
theorem verifiedFrontendRawLexer_token_trace_checked_kernel :
    checkTokenArtifact verifiedFrontendRawLexerArtifact = true :=
  checkTokenArtifact_of_trace_phases
    verifiedFrontendRawLexer_token_header_trace_checked_kernel
    verifiedFrontendRawLexer_token_raw_trace_checked_kernel
    verifiedFrontendRawLexer_token_canonical_trace_checked_kernel
end Lanius.Extraction
