import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokens
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalView
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_parse verifiedFrontendDecimal_parse_checked_kernel for
  verifiedFrontendDecimalArtifact, verifiedFrontendDecimalView

end Lanius.Extraction
