import Lanius.Extraction.VerifiedFrontendUnitLexer
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_canonical verifiedFrontendLexer_token_canonical_trace_checked_kernel for
  verifiedFrontendLexerArtifact
end Lanius.Extraction
