import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceToken
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensView
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_parse verifiedFrontendCanonicalTokens_parse_checked_kernel for
  verifiedFrontendCanonicalTokensArtifact, verifiedFrontendCanonicalTokensView

end Lanius.Extraction
