import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerCoverage
namespace Lanius.Extraction
theorem verifiedFrontendRawLexer_origins_checked_kernel :
    (verifiedFrontendRawLexerOrigins).valid verifiedFrontendRawLexerArtifact verifiedFrontendRawLexerView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendRawLexerView verifiedFrontendRawLexerOrigins
    verifiedFrontendRawLexer_ids_dense_kernel verifiedFrontendRawLexer_origin_nodes_checked_kernel
    verifiedFrontendRawLexer_origin_spellings_checked_kernel verifiedFrontendRawLexer_coverage_checked_kernel
end Lanius.Extraction
