import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDecimalCoverage
namespace Lanius.Extraction
theorem verifiedFrontendDecimal_origins_checked_kernel :
    (verifiedFrontendDecimalOrigins).valid verifiedFrontendDecimalArtifact verifiedFrontendDecimalView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendDecimalView verifiedFrontendDecimalOrigins
    verifiedFrontendDecimal_ids_dense_kernel verifiedFrontendDecimal_origin_nodes_checked_kernel
    verifiedFrontendDecimal_origin_spellings_checked_kernel verifiedFrontendDecimal_coverage_checked_kernel
end Lanius.Extraction
