import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceRawLexerClaims
import Lanius.Extraction.VerifiedFrontendPackOrigins
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_origins verifiedFrontendRawLexer_origin_claims_equal_kernel,
  verifiedFrontendRawLexer_origin_ids_dense_kernel,
  verifiedFrontendRawLexer_node_origins_checked_kernel,
  verifiedFrontendRawLexer_spelling_origins_checked_kernel,
  verifiedFrontendRawLexer_origin_coverage_checked_kernel,
  verifiedFrontendRawLexer_origins_checked_kernel for
  verifiedFrontendRawLexerArtifact, verifiedFrontendRawLexerView,
  verifiedFrontendRawLexerOrigins, verifiedFrontendRawLexerClaims

end Lanius.Extraction
