import Lanius.Extraction.VerifiedFrontendUnitToken
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_header verifiedFrontendToken_token_header_trace_checked_kernel for verifiedFrontendTokenArtifact
end Lanius.Extraction
