import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumber
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolView
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_parse verifiedFrontendSymbol_parse_checked_kernel for
  verifiedFrontendSymbolArtifact, verifiedFrontendSymbolView

end Lanius.Extraction
