import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensCoverage
namespace Lanius.Extraction
theorem verifiedFrontendCanonicalTokens_origins_checked_kernel :
    (verifiedFrontendCanonicalTokensOrigins).valid verifiedFrontendCanonicalTokensArtifact verifiedFrontendCanonicalTokensView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendCanonicalTokensView verifiedFrontendCanonicalTokensOrigins
    verifiedFrontendCanonicalTokens_ids_dense_kernel verifiedFrontendCanonicalTokens_origin_nodes_checked_kernel
    verifiedFrontendCanonicalTokens_origin_spellings_checked_kernel verifiedFrontendCanonicalTokens_coverage_checked_kernel
end Lanius.Extraction
