import Lanius.Extraction.VerifiedFrontendUnitSymbol
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
kernel_parse_token_header verifiedFrontendSymbol_token_header_trace_checked_kernel for verifiedFrontendSymbolArtifact
end Lanius.Extraction
