import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolCoverage
namespace Lanius.Extraction
theorem verifiedFrontendSymbol_origins_checked_kernel :
    (verifiedFrontendSymbolOrigins).valid verifiedFrontendSymbolArtifact verifiedFrontendSymbolView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendSymbolView verifiedFrontendSymbolOrigins
    verifiedFrontendSymbol_ids_dense_kernel verifiedFrontendSymbol_origin_nodes_checked_kernel
    verifiedFrontendSymbol_origin_spellings_checked_kernel verifiedFrontendSymbol_coverage_checked_kernel
end Lanius.Extraction
