import Lanius.Extraction.VerifiedFrontendUnitDecimal
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_root verifiedFrontendDecimal_root_trace_present_kernel,
  verifiedFrontendDecimalRootTraceKernel, verifiedFrontendDecimal_root_trace_found_kernel,
  verifiedFrontendDecimal_root_trace_shape_kernel for verifiedFrontendDecimalArtifact
end Lanius.Extraction
