import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolReconstructionTrace
namespace Lanius.Extraction
def verifiedFrontendSymbolReconstructedKernel : SurfaceFile := verifiedFrontendSymbolReconstructedTraceKernel
theorem verifiedFrontendSymbol_reconstructed_found_kernel :
    reconstructArtifactSurfaceView verifiedFrontendSymbolArtifact verifiedFrontendSymbolView =
      some verifiedFrontendSymbolReconstructedKernel := verifiedFrontendSymbol_reconstructed_trace_kernel
end Lanius.Extraction
