import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsClaims
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsOriginsTrace
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsDecode
namespace Lanius.Extraction
set_option maxRecDepth 500000
def verifiedFrontendDigitsReconstructionKernel : ProvenanceSurfaceReconstruction := {
  reconstructed := verifiedFrontendDigitsReconstructedKernel
  claims := verifiedFrontendDigitsClaimsKernel
  origins := verifiedFrontendDigitsOrigins
}
theorem verifiedFrontendDigits_reconstruction_found_kernel :
    reconstructArtifactSurfaceWithProvenanceView verifiedFrontendDigitsArtifact verifiedFrontendDigitsView
      verifiedFrontendDigitsOrigins = some verifiedFrontendDigitsReconstructionKernel :=
  reconstructArtifactSurfaceWithProvenanceView_of_components verifiedFrontendDigitsView
    verifiedFrontendDigitsOrigins verifiedFrontendDigitsReconstructedKernel verifiedFrontendDigitsClaimsKernel
    verifiedFrontendDigits_reconstructed_found_kernel verifiedFrontendDigits_claims_found_kernel
def verifiedFrontendDigitsSurfaceKernel : CheckedSurfaceArtifact verifiedFrontendDigitsArtifact :=
  CheckedSurfaceArtifact.ofOriginsWithParse verifiedFrontendDigitsView verifiedFrontendDigitsOrigins
    verifiedFrontendDigitsParseValidTraceKernel verifiedFrontendDigitsReconstructionKernel
    verifiedFrontendDigits_reconstruction_found_kernel verifiedFrontendDigitsDecodedSurfaceKernel
    verifiedFrontendDigits_decoded_surface_found_kernel verifiedFrontendDigits_claims_equal_kernel
    verifiedFrontendDigits_origins_checked_kernel
theorem verifiedFrontendDigits_surface_checked_kernel : SurfaceArtifactValid verifiedFrontendDigitsArtifact :=
  CheckedSurfaceArtifact.valid verifiedFrontendDigitsSurfaceKernel
end Lanius.Extraction
