import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumberClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumberIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumberOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumberOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceNumberCoverage
namespace Lanius.Extraction
theorem verifiedFrontendNumber_origins_checked_kernel :
    verifiedFrontendNumberOrigins.valid verifiedFrontendNumberArtifact verifiedFrontendNumberView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendNumberView verifiedFrontendNumberOrigins
    verifiedFrontendNumber_ids_dense_kernel verifiedFrontendNumber_origin_nodes_checked_kernel
    verifiedFrontendNumber_origin_spellings_checked_kernel verifiedFrontendNumber_coverage_checked_kernel
end Lanius.Extraction
