import Lanius.Extraction.VerifiedFrontendUnitTokenCacheSemantic
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
theorem verifiedFrontendToken_semantic_tree_represents_kernel :
    verifiedFrontendTokenSemanticKindTree.Represents verifiedFrontendTokenArtifact.semantic_token_kinds := by
  with_unfolding_all rfl
end Lanius.Extraction
