import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceDigitsCoverage
namespace Lanius.Extraction
theorem verifiedFrontendDigits_origins_checked_kernel :
    (verifiedFrontendDigitsOrigins).valid verifiedFrontendDigitsArtifact verifiedFrontendDigitsView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendDigitsView verifiedFrontendDigitsOrigins
    verifiedFrontendDigits_ids_dense_kernel verifiedFrontendDigits_origin_nodes_checked_kernel
    verifiedFrontendDigits_origin_spellings_checked_kernel verifiedFrontendDigits_coverage_checked_kernel
end Lanius.Extraction
