import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanClaims
import Lanius.Extraction.VerifiedFrontendPackOrigins
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_origins verifiedFrontendTokenScan_origin_claims_equal_kernel,
  verifiedFrontendTokenScan_origin_ids_dense_kernel,
  verifiedFrontendTokenScan_node_origins_checked_kernel,
  verifiedFrontendTokenScan_spelling_origins_checked_kernel,
  verifiedFrontendTokenScan_origin_coverage_checked_kernel,
  verifiedFrontendTokenScan_origins_checked_kernel for
  verifiedFrontendTokenScanArtifact, verifiedFrontendTokenScanView,
  verifiedFrontendTokenScanOrigins, verifiedFrontendTokenScanClaimsKernel

end Lanius.Extraction
