import Lanius.Extraction.VerifiedFrontendUnitRawLexer
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_raw verifiedFrontendRawLexer_token_raw_trace_checked_kernel for verifiedFrontendRawLexerArtifact
end Lanius.Extraction
