import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanClaimsEqual
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanIdsDense
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanOriginNodes
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanOriginSpellings
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceTokenScanCoverage
namespace Lanius.Extraction
theorem verifiedFrontendTokenScan_origins_checked_kernel :
    (verifiedFrontendTokenScanOrigins).valid verifiedFrontendTokenScanArtifact verifiedFrontendTokenScanView = true :=
  SurfaceOrigins.valid_of_components verifiedFrontendTokenScanView verifiedFrontendTokenScanOrigins
    verifiedFrontendTokenScan_ids_dense_kernel verifiedFrontendTokenScan_origin_nodes_checked_kernel
    verifiedFrontendTokenScan_origin_spellings_checked_kernel verifiedFrontendTokenScan_coverage_checked_kernel
end Lanius.Extraction
