import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceSymbolParseView
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
kernel_parse_nodes_cached_chunk verifiedFrontendSymbol_nodes_2_trace_checked_kernel,
  verifiedFrontendSymbol_nodes_2_trace_length_kernel for
  verifiedFrontendSymbolArtifact, verifiedFrontendSymbolParseView, 3000, 1500
end Lanius.Extraction
