import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensParseChunkAssembly

namespace Lanius.Extraction
theorem verifiedFrontendCanonicalTokensParseValidTraceKernel :
    ParseArtifactValid verifiedFrontendCanonicalTokensArtifact :=
  verifiedFrontendCanonicalTokensParseValidChunkKernel
end Lanius.Extraction
