import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensSources
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensTokens
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensRawTokens
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensSemanticTokenKinds
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseNodes
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensParseRoot
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensSurface
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensResolutions
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensTypes
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensCoreProgram
import Lanius.Extraction.VerifiedFrontendUnitCanonicalTokensLowering

namespace Lanius.Extraction
def verifiedFrontendCanonicalTokensArtifact : Artifact := {
  schema_version := schemaVersion
  sources := verifiedFrontendCanonicalTokensSources
  tokens := verifiedFrontendCanonicalTokensTokens
  raw_tokens := verifiedFrontendCanonicalTokensRawTokens
  semantic_token_kinds := verifiedFrontendCanonicalTokensSemanticTokenKinds
  parse_nodes := verifiedFrontendCanonicalTokensParseNodes
  parse_root := verifiedFrontendCanonicalTokensParseRoot
  surface := verifiedFrontendCanonicalTokensSurface
  resolutions := verifiedFrontendCanonicalTokensResolutions
  types := verifiedFrontendCanonicalTokensTypes
  core_program := verifiedFrontendCanonicalTokensCoreProgram
  lowering := verifiedFrontendCanonicalTokensLowering
}
end Lanius.Extraction
