import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewParseWell
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewParseRep
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewTokenWell
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewTokenRep
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewSourceWell
import Lanius.Extraction.VerifiedFrontendPackKernelSurfaceCanonicalTokensViewSourceRep

namespace Lanius.Extraction
def verifiedFrontendCanonicalTokensView :
    ArtifactView verifiedFrontendCanonicalTokensArtifact := {
  cache := verifiedFrontendCanonicalTokensCache
  parseNodesWellFormed :=
    verifiedFrontendCanonicalTokens_parse_tree_well_formed_kernel
  parseNodesRepresent :=
    verifiedFrontendCanonicalTokens_parse_tree_represents_kernel
  tokensWellFormed :=
    verifiedFrontendCanonicalTokens_token_tree_well_formed_kernel
  tokensRepresent :=
    verifiedFrontendCanonicalTokens_token_tree_represents_kernel
  sourceBytesWellFormed :=
    verifiedFrontendCanonicalTokens_source_tree_well_formed_kernel
  sourceBytesRepresent :=
    verifiedFrontendCanonicalTokens_source_tree_represents_kernel
}
end Lanius.Extraction
