import Lanius.Extraction.VerifiedFrontend.Artifact.Digits.Artifact
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_raw verifiedFrontendDigits_token_raw_trace_checked_kernel for verifiedFrontendDigitsArtifact
end Lanius.Extraction
