import Lanius.Extraction.VerifiedFrontend.Artifact.Lexer.Artifact
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_header verifiedFrontendLexer_token_header_trace_checked_kernel for
  verifiedFrontendLexerArtifact
end Lanius.Extraction
