import Lanius.Extraction.VerifiedFrontendPackKernelEvidenceBase
import Std.Data.TreeSet.Raw.Lemmas

/-! Regenerates `VerifiedFrontendPackKernelEvidenceUnit4IndexesData.lean` from
the canonical embedded artifact after that artifact changes.  The generated
trees remain untrusted until the kernel equality certificates accept them. -/

open Std.DTreeMap.Internal
open Lanius.Extraction

def renderNatUnitTree : Impl Nat (fun _ => Unit) → String
  | .leaf => ".leaf"
  | .inner size key _ left right =>
      "(.inner " ++ toString size ++ " " ++ toString key ++ " () " ++
        renderNatUnitTree left ++ " " ++ renderNatUnitTree right ++ ")"

def rawTreeOfNodes (nodes : List Nat) : Impl Nat (fun _ => Unit) :=
  (Std.TreeSet.Raw.ofList nodes : Std.TreeSet.Raw Nat).inner.inner.inner

def renderDefinition (name : String) (nodes : List Nat) : String :=
  "def " ++ name ++ " : Std.TreeSet.Raw Nat :=\n  ⟨⟨⟨" ++
    renderNatUnitTree (rawTreeOfNodes nodes) ++ "⟩⟩⟩\n"

def main : IO Unit := do
  IO.println "import Lanius.Extraction.EvidenceStructureChecker\nimport Std.Data.TreeSet.Raw.Lemmas\n\n/-! Generated by `GenerateCanonicalEvidenceIndexes.lean`.  This is only cached\ndata; the adjacent certificate modules establish its canonical meaning. -/\n\nnamespace Lanius.Extraction\n"
  IO.println <| renderDefinition
    "verifiedFrontendCanonicalTokensTypeNodeIndexDataKernel"
    (verifiedFrontendCanonicalTokensArtifact.types.map (·.surface_node))
  IO.println <| renderDefinition
    "verifiedFrontendCanonicalTokensLoweringNodeIndexDataKernel"
    (verifiedFrontendCanonicalTokensArtifact.lowering.map (·.surface_node))
  IO.println "end Lanius.Extraction"
