use super::super::*;

/// Borrowed inputs used to build the resident module/path state.
///
/// The constructor groups parser HIR rows, name rows, type rows, call rows, and
/// optional scratch aliases here so module-path bind-group creation remains
/// explicit about every buffer identity it captures.
pub(in crate::type_checker) struct CreateInputs<'a> {
    pub(in crate::type_checker) params: &'a LaniusBuffer<TypeCheckParams>,
    pub(in crate::type_checker) source_len: u32,
    pub(in crate::type_checker) source_file_capacity: u32,
    pub(in crate::type_checker) token_capacity: u32,
    pub(in crate::type_checker) hir_node_capacity: u32,
    pub(in crate::type_checker) parser_hir_node_capacity: u32,
    pub(in crate::type_checker) token_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) token_count_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) token_file_id_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) source_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_status_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_kind_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_token_pos_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_token_end_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) status_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_active_count_buf: &'a wgpu::Buffer,
    pub(in crate::type_checker) hir_items: GpuTypeCheckHirItemBuffers<'a>,
    pub(in crate::type_checker) name_id_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) name_spans: &'a wgpu::Buffer,
    pub(in crate::type_checker) name_hash_lo: &'a wgpu::Buffer,
    pub(in crate::type_checker) name_hash_hi: &'a wgpu::Buffer,
    pub(in crate::type_checker) language_symbol_bytes: &'a wgpu::Buffer,
    pub(in crate::type_checker) language_name_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_name_token_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_id_by_name_token_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_kind_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_type_path_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_type_path_status: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_expr_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_open: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_path_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_call_leaf: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_associated_method_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_associated_receiver_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_const_head: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_const_end: &'a wgpu::Buffer,
    pub(in crate::type_checker) module_value_path_status: &'a wgpu::Buffer,
    pub(in crate::type_checker) predicate_syntax_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) visible_decl: &'a wgpu::Buffer,
    pub(in crate::type_checker) visible_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) enclosing_fn: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_fn_index: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_dependency_decl: &'a LaniusBuffer<u32>,
    pub(in crate::type_checker) call_return_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_return_type_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_slot_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_slot_ordinal: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_count_out: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_callee: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_slot: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_generic_claim_order: &'a wgpu::Buffer,
    pub(in crate::type_checker) method_call_name_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_count_out: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_node: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_fn_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_ordinal: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_type: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_param_row_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) aggregate_compare_scan_input: &'a wgpu::Buffer,
    pub(in crate::type_checker) aggregate_compare_expected_instance: &'a wgpu::Buffer,
    pub(in crate::type_checker) aggregate_compare_actual_instance: &'a wgpu::Buffer,
    pub(in crate::type_checker) aggregate_compare_error_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) aggregate_compare_error_detail: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_record: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_node: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_call_node: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_ordinal: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) call_arg_row_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_expr_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_expr_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_kind: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_decl_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_external_canonical: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_row_start: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_row_count_out: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_row_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_arg_row_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_semantic_row_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_semantic_scan_input: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_semantic_prefix: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_semantic_count_out: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_semantic_row_by_ordinal: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_elem_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_elem_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_len_kind: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_len_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_decl_generic_param_count: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_decl_generic_param_count_by_owner_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_generic_param_slot_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_decl_hir_node_by_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_count_out: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_owner_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_name_id: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_token: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_kind: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_key_order: &'a wgpu::Buffer,
    pub(in crate::type_checker) generic_param_slot_order: &'a wgpu::Buffer,
    pub(in crate::type_checker) type_instance_state: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_type_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) decl_type_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) fn_return_ref_tag: &'a wgpu::Buffer,
    pub(in crate::type_checker) fn_return_ref_payload: &'a wgpu::Buffer,
    pub(in crate::type_checker) record_family_bits_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) record_family_flag_scratch: &'a wgpu::Buffer,
    pub(in crate::type_checker) external_scratch: Option<GpuTypeCheckExternalScratchBuffers<'a>>,
    pub(in crate::type_checker) dependency_interfaces: Option<&'a GpuDependencyInterfaceState>,
}
