use super::{
    super::*,
    dependency_visibility::DependencyVisibilityState,
    path_sequences::PathPrefixRound,
    projection::TypeAliasProjection,
};

/// All bind groups recorded by the module/path pass family.
///
/// This carrier preserves creation-time ordering and keeps the resident state
/// independent from individual constructor helpers.
pub(in crate::type_checker) struct BindGroups {
    pub(in crate::type_checker) mark_records: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_paths: wgpu::BindGroup,
    pub(in crate::type_checker) count_path_segments: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_path_segments: wgpu::BindGroup,
    pub(in crate::type_checker) clear_path_state: wgpu::BindGroup,
    pub(in crate::type_checker) path_prefix_dispatch_args: wgpu::BindGroup,
    pub(in crate::type_checker) path_prefix_rounds: Vec<PathPrefixRound>,
    pub(in crate::type_checker) path_prefix_finalize: wgpu::BindGroup,
    pub(in crate::type_checker) extract_module_record_flag: wgpu::BindGroup,
    pub(in crate::type_checker) module_scan: U32ScanBindGroups,
    pub(in crate::type_checker) extract_import_record_flag: wgpu::BindGroup,
    pub(in crate::type_checker) import_scan: U32ScanBindGroups,
    pub(in crate::type_checker) extract_decl_record_flag: wgpu::BindGroup,
    pub(in crate::type_checker) decl_scan: U32ScanBindGroups,
    pub(in crate::type_checker) scatter_module_records: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_import_records: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_decl_core_records: wgpu::BindGroup,
    pub(in crate::type_checker) append_variant_decl_count: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_variant_decl_records: wgpu::BindGroup,
    pub(in crate::type_checker) clear_decl_lookup: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_decl_span_records: wgpu::BindGroup,
    pub(in crate::type_checker) build_module_keys: wgpu::BindGroup,
    pub(in crate::type_checker) module_key_radix_dispatch: wgpu::BindGroup,
    pub(in crate::type_checker) sort_module_keys_small: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_module_key_histogram: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_module_key_bucket_prefix: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_module_key_bucket_bases: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_module_key_scatter: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) validate_modules: wgpu::BindGroup,
    pub(in crate::type_checker) clear_dependency_module_lookup: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) build_dependency_module_lookup: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) resolve_dependency_imports: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) resolve_imports: wgpu::BindGroup,
    pub(in crate::type_checker) seed_import_edge_key_order: wgpu::BindGroup,
    pub(in crate::type_checker) import_edge_key_radix_dispatch: wgpu::BindGroup,
    pub(in crate::type_checker) sort_import_edges_small: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_edge_key_histogram: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_edge_key_bucket_prefix: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_edge_key_bucket_bases: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_edge_key_scatter: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) validate_import_cycles: wgpu::BindGroup,
    pub(in crate::type_checker) clear_file_module_map: wgpu::BindGroup,
    pub(in crate::type_checker) build_file_module_map: wgpu::BindGroup,
    pub(in crate::type_checker) attach_record_modules: wgpu::BindGroup,
    pub(in crate::type_checker) import_dispatch_args: wgpu::BindGroup,
    pub(in crate::type_checker) seed_decl_key_order: wgpu::BindGroup,
    pub(in crate::type_checker) decl_key_radix_dispatch: wgpu::BindGroup,
    pub(in crate::type_checker) sort_decl_keys_small: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_decl_key_histogram: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_decl_key_bucket_prefix: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_decl_key_bucket_bases: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_decl_key_scatter: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) validate_decls: wgpu::BindGroup,
    pub(in crate::type_checker) mark_decl_namespace_keys: wgpu::BindGroup,
    pub(in crate::type_checker) decl_type_key_scan: U32ScanBindGroups,
    pub(in crate::type_checker) decl_value_key_scan: U32ScanBindGroups,
    pub(in crate::type_checker) scatter_decl_namespace_keys: wgpu::BindGroup,
    pub(in crate::type_checker) mark_public_decl_keys: wgpu::BindGroup,
    pub(in crate::type_checker) decl_type_public_scan: U32ScanBindGroups,
    pub(in crate::type_checker) decl_value_public_scan: U32ScanBindGroups,
    pub(in crate::type_checker) clear_interface_public_decls: wgpu::BindGroup,
    pub(in crate::type_checker) map_interface_public_decls: wgpu::BindGroup,
    pub(in crate::type_checker) count_import_visibility: wgpu::BindGroup,
    pub(in crate::type_checker) import_visible_type_scan: U32ScanBindGroups,
    pub(in crate::type_checker) import_visible_value_scan: U32ScanBindGroups,
    pub(in crate::type_checker) scatter_import_visible_type: wgpu::BindGroup,
    pub(in crate::type_checker) scatter_import_visible_value: wgpu::BindGroup,
    pub(in crate::type_checker) import_visible_type_key_radix_dispatch: wgpu::BindGroup,
    pub(in crate::type_checker) sort_import_visible_type_keys_small: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_type_key_histogram: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_type_key_bucket_prefix: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_type_key_bucket_bases: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_type_key_scatter: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) import_visible_value_key_radix_dispatch: wgpu::BindGroup,
    pub(in crate::type_checker) sort_import_visible_value_keys_small: Option<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_value_key_histogram: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_value_key_bucket_prefix: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_value_key_bucket_bases: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) sort_import_visible_value_key_scatter: Vec<wgpu::BindGroup>,
    pub(in crate::type_checker) build_import_visible_type_key_table: wgpu::BindGroup,
    pub(in crate::type_checker) build_import_visible_value_key_table: wgpu::BindGroup,
    pub(in crate::type_checker) import_visible_validate_dispatch_args: wgpu::BindGroup,
    pub(in crate::type_checker) initialize_import_visible_keys: wgpu::BindGroup,
    pub(in crate::type_checker) validate_import_visible_keys: wgpu::BindGroup,
    pub(in crate::type_checker) path_dispatch_args: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_local_type_paths: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_local_value_paths: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_imported_type_paths: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_imported_value_paths: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_qualified_type_paths: wgpu::BindGroup,
    pub(in crate::type_checker) resolve_qualified_value_paths: wgpu::BindGroup,
    pub(in crate::type_checker) clear_type_path_types: wgpu::BindGroup,
    pub(in crate::type_checker) project_type_paths: wgpu::BindGroup,
    pub(in crate::type_checker) validate_type_paths: wgpu::BindGroup,
    pub(in crate::type_checker) type_aliases: Box<TypeAliasProjection>,
    pub(in crate::type_checker) project_type_instances: wgpu::BindGroup,
    pub(in crate::type_checker) mark_value_call_paths: wgpu::BindGroup,
    pub(in crate::type_checker) project_value_paths: wgpu::BindGroup,
    pub(in crate::type_checker) consume_value_calls: wgpu::BindGroup,
    pub(in crate::type_checker) mirror_value_call_leaf: wgpu::BindGroup,
    pub(in crate::type_checker) consume_value_consts: wgpu::BindGroup,
    pub(in crate::type_checker) consume_value_enum_units: wgpu::BindGroup,
    pub(in crate::type_checker) consume_value_enum_calls: wgpu::BindGroup,
    pub(in crate::type_checker) validate_value_enum_call_payloads: wgpu::BindGroup,
    pub(in crate::type_checker) finalize_value_enum_calls: wgpu::BindGroup,
    pub(in crate::type_checker) bind_match_patterns: wgpu::BindGroup,
    pub(in crate::type_checker) type_match_payloads: wgpu::BindGroup,
    pub(in crate::type_checker) type_match_exprs: wgpu::BindGroup,
}

/// Resident module/path relation state.
///
/// The state owns module/import/declaration/path tables, lookup scratch, radix
/// scratch, projection outputs, retained uniforms, and the bind groups that
/// keep those buffers alive across recorded checks.
#[allow(dead_code)]
pub(in crate::type_checker) struct State {
    pub(in crate::type_checker) n_blocks: u32,
    pub(in crate::type_checker) parser_hir_n_blocks: u32,
    pub(in crate::type_checker) record_n_blocks: u32,
    pub(in crate::type_checker) module_n_blocks: u32,
    pub(in crate::type_checker) token_capacity: u32,
    pub(in crate::type_checker) record_family_bits: LaniusBuffer<u32>,
    pub(in crate::type_checker) record_family_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_record_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_record_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_record_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_record_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_record_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_record_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) record_scan_local_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) record_scan_block_sum: LaniusBuffer<u32>,
    pub(in crate::type_checker) record_scan_prefix_a: LaniusBuffer<u32>,
    pub(in crate::type_checker) record_scan_prefix_b: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_table_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_file_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_path_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_owner_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_canonical_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_segment_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_segment_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_segment_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_to_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_order_tmp: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_radix_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_radix_block_histogram: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_radix_bucket_total: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_key_radix_bucket_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) module_id_by_file_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_module_file_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_path_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_kind: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_owner_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_target_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_target_dependency_module_id: Option<LaniusBuffer<u32>>,
    pub(in crate::type_checker) dependency_interfaces: Option<GpuDependencyInterfaceState>,
    pub(in crate::type_checker) dependency_visibility: Option<Box<DependencyVisibilityState>>,
    pub(in crate::type_checker) dependency_module_params:
        Option<LaniusBuffer<DependencyInterfaceModuleParams>>,
    pub(in crate::type_checker) import_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_edge_key_order: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_edge_key_order_tmp: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_edge_key_radix_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_module_file_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_name_token: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_id_by_name_token: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_kind: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_namespace: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_visibility: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_hir_node: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_parent_type_decl: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_token_start: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_token_end: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_to_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_order_tmp: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_radix_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_radix_block_histogram: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_radix_bucket_total: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_key_radix_bucket_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_duplicate_of: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_type_key_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_value_key_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_type_key_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_value_key_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_type_key_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_value_key_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_type_key_to_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) decl_value_key_to_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) interface_public_decl_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) interface_public_decl_local_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) interface_public_decl_index_by_local: LaniusBuffer<u32>,
    pub(in crate::type_checker) interface_public_decl_index_by_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_order: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_order_tmp: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_to_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_duplicate_of: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_type_key_radix_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_order: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_order_tmp: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_to_decl_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_duplicate_of: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_value_key_radix_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_validate_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_key_radix_block_histogram: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_key_radix_block_bucket_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_key_radix_bucket_total: LaniusBuffer<u32>,
    pub(in crate::type_checker) import_visible_key_radix_bucket_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) resolved_type_decl: LaniusBuffer<u32>,
    pub(in crate::type_checker) resolved_value_decl: LaniusBuffer<u32>,
    pub(in crate::type_checker) resolved_type_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) resolved_value_status: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_record_flag: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_record_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_scan_local_prefix: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_scan_block_sum: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_scan_prefix_a: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_scan_prefix_b: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_start: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_len: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_segment_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_segment_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_segment_name_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_segment_token: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_segment_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_max_segment_count: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_base: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_id_a: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_id_b: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_table_state: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_row_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_prefix_round_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_owner_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_call_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_owner_token: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_id_by_owner_hir: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_id_by_owner_token: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_owner_module_id: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_kind: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_count_out: LaniusBuffer<u32>,
    pub(in crate::type_checker) path_dispatch_args: LaniusBuffer<u32>,
    pub(in crate::type_checker) scan_steps: Vec<NameScanStep>,
    pub(in crate::type_checker) record_scan_steps: Vec<NameScanStep>,
    pub(in crate::type_checker) _extract_module_record_flag_params:
        LaniusBuffer<RecordFamilyFlagParams>,
    pub(in crate::type_checker) _extract_import_record_flag_params:
        LaniusBuffer<RecordFamilyFlagParams>,
    pub(in crate::type_checker) _extract_decl_record_flag_params:
        LaniusBuffer<RecordFamilyFlagParams>,
    pub(in crate::type_checker) _path_dispatch_params: LaniusBuffer<CountDispatchParams>,
    pub(in crate::type_checker) _path_prefix_dispatch_params:
        LaniusBuffer<PathPrefixDispatchParams>,
    pub(in crate::type_checker) _import_dispatch_params: LaniusBuffer<CountDispatchParams>,
    pub(in crate::type_checker) _import_visible_validate_dispatch_params:
        LaniusBuffer<CountPairMaxDispatchParams>,
    pub(in crate::type_checker) _module_key_radix_dispatch_params:
        LaniusBuffer<ModuleKeyRadixParams>,
    pub(in crate::type_checker) _decl_key_radix_dispatch_params: LaniusBuffer<ModuleKeyRadixParams>,
    pub(in crate::type_checker) _import_visible_type_key_radix_dispatch_params:
        LaniusBuffer<ModuleKeyRadixParams>,
    pub(in crate::type_checker) _import_visible_value_key_radix_dispatch_params:
        LaniusBuffer<ModuleKeyRadixParams>,
    pub(in crate::type_checker) _retained_key_params: Vec<ModuleKeyRadixStep>,
    pub(in crate::type_checker) bind_groups: BindGroups,
}
