import Lanius.Extraction.VerifiedFrontend.Artifact.Decimal.Artifact
import Lanius.Extraction.ParseChunks
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
kernel_parse_token_raw verifiedFrontendDecimal_token_raw_trace_checked_kernel for verifiedFrontendDecimalArtifact
end Lanius.Extraction
