use super::*;

impl GpuWasmCodeGenerator {
    pub(super) fn create_resident_buffers(
        &self,
        device: &wgpu::Device,
        input_fingerprint: u64,
        output_capacity: usize,
        token_capacity: u32,
        hir_node_capacity: u32,
        inputs: GpuWasmCodegenInputs<'_>,
    ) -> Result<ResidentWasmBuffers> {
        let active_hir_dispatch_args_buf = inputs.active_hir_dispatch_args;
        let working_buffers =
            create_wasm_working_buffers(device, output_capacity, token_capacity, hir_node_capacity);
        let WasmPreludeBindGroups {
            wasm_const_values_bind_group,
            agg_layout_clear_bind_group,
            agg_layout_bind_group,
        } = self.create_wasm_prelude_bind_groups(device, inputs, &working_buffers)?;
        let WasmFunctionBindGroups {
            hir_body_let_init_clear_bind_group,
            hir_body_let_init_bind_group,
            hir_functions_clear_bind_group,
            hir_functions_mark_bind_group,
            hir_functions_reach_bind_group,
            hir_functions_count_bind_group,
            hir_func_scan_local_bind_group,
            hir_func_scan_block_bind_groups,
            hir_agg_scan_local_bind_group,
            hir_agg_scan_block_bind_groups,
            hir_functions_scatter_bind_group,
        } = self.create_wasm_function_bind_groups(device, inputs, &working_buffers)?;
        let WasmBodyPlanBindGroups {
            hir_body_plan_collect_bind_group,
            hir_body_plan_validate_bind_group,
            hir_body_plan_validate_return_bind_group,
            hir_body_plan_validate_return_call_bind_group,
            hir_body_plan_validate_return_agg_call_bind_group,
            hir_body_plan_validate_return_nested_call_bind_group,
            hir_body_plan_validate_assign_bind_group,
            hir_body_plan_validate_control_bind_group,
            hir_body_plan_validate_agg_range_control_bind_group,
            hir_body_plan_validate_if_simple_bind_group,
            hir_body_plan_validate_print_simple_bind_group,
            hir_body_plan_validate_call_bind_group,
            hir_body_plan_validate_host_void_call_bind_group,
            hir_body_plan_validate_let_host_bind_group,
            hir_body_plan_validate_let_host_env_bind_group,
            hir_body_plan_validate_let_host_io_bind_group,
            hir_body_plan_validate_let_host_string_bind_group,
            hir_body_plan_validate_return_host_io_bind_group,
            hir_body_plan_validate_return_host_string_bind_group,
            hir_body_plan_validate_let_direct_call_bind_group,
            hir_body_plan_validate_let_call_bind_group,
            hir_body_plan_validate_let_call_status_bind_group,
            hir_body_plan_agg_direct_call_bind_group,
            hir_body_plan_agg_struct_bind_group,
            hir_body_plan_arrays_bind_group,
            hir_body_plan_functions_bind_group,
            hir_body_plan_finalize_bind_group,
        } = self.create_wasm_body_plan_bind_groups(device, inputs, &working_buffers)?;
        let WasmBodySizingBindGroups {
            hir_body_clear_bind_group,
            hir_body_counts_bind_group,
            hir_body_scan_local_bind_group,
            hir_body_scan_block_bind_groups,
            hir_body_agg_call_arg_counts_bind_group,
            hir_body_agg_call_arg_count_scan_local_bind_group,
            hir_body_agg_call_arg_count_scan_block_bind_groups,
            hir_body_agg_call_arg_records_bind_group,
            hir_body_direct_call_arg_records_bind_group,
            hir_body_agg_call_arg_byte_scan_local_bind_group,
            hir_body_agg_call_arg_byte_scan_block_bind_groups,
            hir_body_agg_call_finalize_bind_group,
            hir_body_direct_call_finalize_bind_group,
            hir_body_status_bind_group,
        } = self.create_wasm_body_sizing_bind_groups(device, inputs, &working_buffers)?;
        let WasmBodyScatterBindGroups {
            hir_body_scatter_bind_group,
            hir_body_scatter_frame_bind_group,
            hir_body_scatter_if_simple_bind_group,
            hir_body_scatter_return_scalar_bind_group,
            hir_body_scatter_return_expr_bind_group,
            hir_body_scatter_conversion_expr_bind_group,
            hir_body_scatter_let_const_bind_group,
            hir_body_scatter_expr_control_bind_group,
            hir_body_scatter_agg_range_control_bind_group,
            hir_body_scatter_let_direct_bind_group,
            hir_body_scatter_direct_nested_call_bind_group,
            hir_body_scatter_host_io_bind_group,
            hir_body_scatter_host_bind_group,
            hir_body_scatter_arrays_bind_group,
            hir_body_scatter_agg_copy_bind_group,
            hir_body_scatter_array_lean_bind_group,
            hir_body_scatter_return_member_bind_group,
            hir_body_scatter_agg_call_args_bind_group,
            hir_body_scatter_nested_call_args_bind_group,
            hir_body_scatter_agg_direct_call_bind_group,
            hir_body_scatter_return_agg_direct_call_bind_group,
            hir_body_scatter_member_expr_bind_group,
            hir_body_scatter_binary_direct_call_bind_group,
        } = self.create_wasm_body_scatter_bind_groups(device, inputs, &working_buffers)?;
        let WasmModuleBindGroups {
            hir_agg_body_bind_group,
            hir_assert_module_bind_group,
            hir_enum_match_records_bind_group,
            module_type_dispatch_args_bind_group,
            module_type_lengths_bind_group,
            module_type_bytes_bind_group,
            module_status_bind_group,
            bind_group,
            pack_bind_group,
        } = self.create_wasm_module_bind_groups(device, inputs, &working_buffers)?;
        let WasmWorkingBuffers {
            params_buf,
            body_scan_param_bufs,
            body_scan_blocks,
            arg_scan_param_bufs,
            arg_scan_blocks,
            func_scan_param_bufs,
            func_scan_blocks,
            body_dispatch_buf,
            module_type_dispatch_buf,
            body_buf,
            body_plan_buf,
            wasm_func_flag_buf,
            wasm_func_decl_flag_buf,
            wasm_func_slot_by_token_buf,
            wasm_func_token_by_slot_buf,
            wasm_func_param_ordinal_by_decl_token_buf,
            wasm_func_body_len_by_token_buf,
            wasm_func_local_max_by_token_buf,
            wasm_func_return_count_by_token_buf,
            wasm_func_invalid_count_by_token_buf,
            wasm_func_return_token_by_token_buf,
            wasm_func_detail_by_token_buf,
            wasm_func_scan_local_prefix_buf,
            wasm_func_scan_block_sum_buf,
            wasm_func_scan_prefix_a_buf,
            wasm_func_scan_prefix_b_buf,
            body_let_init_expr_by_decl_token_buf,
            body_fragment_len_buf,
            body_fragment_meta_buf,
            body_fragment_aux_buf,
            body_scan_local_prefix_buf,
            body_scan_block_sum_buf,
            body_scan_prefix_a_buf,
            body_scan_prefix_b_buf,
            wasm_agg_call_arg_count_by_fragment_buf,
            wasm_agg_call_arg_count_local_prefix_buf,
            wasm_agg_call_arg_count_block_sum_buf,
            wasm_agg_call_arg_count_prefix_a_buf,
            wasm_agg_call_arg_count_prefix_b_buf,
            wasm_agg_call_arg_len_buf,
            wasm_agg_call_arg_meta_buf,
            wasm_agg_call_arg_aux_buf,
            wasm_agg_call_arg_byte_local_prefix_buf,
            wasm_agg_call_arg_byte_block_sum_buf,
            wasm_agg_call_arg_byte_prefix_a_buf,
            wasm_agg_call_arg_byte_prefix_b_buf,
            body_status_buf,
            struct_field_count_by_decl_token_buf,
            struct_field_index_by_token_buf,
            struct_field_decl_by_token_buf,
            struct_field_name_id_buf,
            struct_field_ref_tag_buf,
            struct_field_ref_payload_buf,
            struct_field_scalar_offset_buf,
            struct_field_scalar_width_buf,
            struct_init_field_index_buf,
            member_result_field_index_buf,
            wasm_agg_local_width_by_token_buf,
            wasm_agg_local_base_by_token_buf,
            wasm_agg_scan_block_sum_buf,
            wasm_agg_scan_prefix_a_buf,
            wasm_agg_scan_prefix_b_buf,
            hir_enum_match_record_buf,
            wasm_const_value_record_buf,
            out_buf,
            packed_out_buf,
            status_buf,
            out_readback,
            status_readback,
            body_plan_readback,
            body_fragment_len_readback,
            body_fragment_meta_readback,
            body_fragment_aux_readback,
            wasm_func_invalid_count_readback,
            wasm_func_detail_readback,
        } = working_buffers;

        Ok(ResidentWasmBuffers {
            input_fingerprint,
            output_capacity,
            token_capacity,
            hir_node_capacity,
            active_hir_dispatch_args_buf: active_hir_dispatch_args_buf.clone(),
            params_buf,
            body_scan_param_bufs,
            body_scan_blocks,
            arg_scan_param_bufs,
            arg_scan_blocks,
            func_scan_param_bufs,
            func_scan_blocks,
            body_dispatch_buf,
            _module_type_dispatch_buf: module_type_dispatch_buf,
            _body_buf: body_buf,
            body_plan_buf,
            _wasm_func_flag_buf: wasm_func_flag_buf,
            _wasm_func_decl_flag_buf: wasm_func_decl_flag_buf,
            _wasm_func_slot_by_token_buf: wasm_func_slot_by_token_buf,
            _wasm_func_token_by_slot_buf: wasm_func_token_by_slot_buf,
            _wasm_func_param_ordinal_by_decl_token_buf: wasm_func_param_ordinal_by_decl_token_buf,
            _wasm_func_body_len_by_token_buf: wasm_func_body_len_by_token_buf,
            _wasm_func_local_max_by_token_buf: wasm_func_local_max_by_token_buf,
            _wasm_func_return_count_by_token_buf: wasm_func_return_count_by_token_buf,
            _wasm_func_invalid_count_by_token_buf: wasm_func_invalid_count_by_token_buf,
            _wasm_func_return_token_by_token_buf: wasm_func_return_token_by_token_buf,
            _wasm_func_detail_by_token_buf: wasm_func_detail_by_token_buf,
            _wasm_func_scan_local_prefix_buf: wasm_func_scan_local_prefix_buf,
            _wasm_func_scan_block_sum_buf: wasm_func_scan_block_sum_buf,
            _wasm_func_scan_prefix_a_buf: wasm_func_scan_prefix_a_buf,
            _wasm_func_scan_prefix_b_buf: wasm_func_scan_prefix_b_buf,
            _body_let_init_expr_by_decl_token_buf: body_let_init_expr_by_decl_token_buf,
            _body_fragment_len_buf: body_fragment_len_buf,
            _body_fragment_meta_buf: body_fragment_meta_buf,
            _body_fragment_aux_buf: body_fragment_aux_buf,
            _body_scan_local_prefix_buf: body_scan_local_prefix_buf,
            _body_scan_block_sum_buf: body_scan_block_sum_buf,
            _body_scan_prefix_a_buf: body_scan_prefix_a_buf,
            _body_scan_prefix_b_buf: body_scan_prefix_b_buf,
            _wasm_agg_call_arg_count_by_fragment_buf: wasm_agg_call_arg_count_by_fragment_buf,
            _wasm_agg_call_arg_count_local_prefix_buf: wasm_agg_call_arg_count_local_prefix_buf,
            _wasm_agg_call_arg_count_block_sum_buf: wasm_agg_call_arg_count_block_sum_buf,
            _wasm_agg_call_arg_count_prefix_a_buf: wasm_agg_call_arg_count_prefix_a_buf,
            _wasm_agg_call_arg_count_prefix_b_buf: wasm_agg_call_arg_count_prefix_b_buf,
            _wasm_agg_call_arg_len_buf: wasm_agg_call_arg_len_buf,
            _wasm_agg_call_arg_meta_buf: wasm_agg_call_arg_meta_buf,
            _wasm_agg_call_arg_aux_buf: wasm_agg_call_arg_aux_buf,
            _wasm_agg_call_arg_byte_local_prefix_buf: wasm_agg_call_arg_byte_local_prefix_buf,
            _wasm_agg_call_arg_byte_block_sum_buf: wasm_agg_call_arg_byte_block_sum_buf,
            _wasm_agg_call_arg_byte_prefix_a_buf: wasm_agg_call_arg_byte_prefix_a_buf,
            _wasm_agg_call_arg_byte_prefix_b_buf: wasm_agg_call_arg_byte_prefix_b_buf,
            body_status_buf,
            _struct_field_count_by_decl_token_buf: struct_field_count_by_decl_token_buf,
            _struct_field_index_by_token_buf: struct_field_index_by_token_buf,
            _struct_field_decl_by_token_buf: struct_field_decl_by_token_buf,
            _struct_field_name_id_buf: struct_field_name_id_buf,
            _struct_field_ref_tag_buf: struct_field_ref_tag_buf,
            _struct_field_ref_payload_buf: struct_field_ref_payload_buf,
            _struct_field_scalar_offset_buf: struct_field_scalar_offset_buf,
            _struct_field_scalar_width_buf: struct_field_scalar_width_buf,
            _struct_init_field_index_buf: struct_init_field_index_buf,
            _member_result_field_index_buf: member_result_field_index_buf,
            _wasm_agg_local_width_by_token_buf: wasm_agg_local_width_by_token_buf,
            _wasm_agg_local_base_by_token_buf: wasm_agg_local_base_by_token_buf,
            _wasm_agg_scan_block_sum_buf: wasm_agg_scan_block_sum_buf,
            _wasm_agg_scan_prefix_a_buf: wasm_agg_scan_prefix_a_buf,
            _wasm_agg_scan_prefix_b_buf: wasm_agg_scan_prefix_b_buf,
            _hir_enum_match_record_buf: hir_enum_match_record_buf,
            wasm_const_value_record_buf,
            out_buf,
            packed_out_buf,
            status_buf,
            out_readback,
            status_readback,
            body_plan_readback,
            body_fragment_len_readback,
            body_fragment_meta_readback,
            body_fragment_aux_readback,
            wasm_func_invalid_count_readback,
            wasm_func_detail_readback,
            agg_layout_clear_bind_group,
            agg_layout_bind_group,
            hir_body_let_init_clear_bind_group,
            hir_body_let_init_bind_group,
            hir_functions_clear_bind_group,
            hir_functions_mark_bind_group,
            hir_functions_reach_bind_group,
            hir_functions_count_bind_group,
            hir_func_scan_local_bind_group,
            hir_func_scan_block_bind_groups,
            hir_agg_scan_local_bind_group,
            hir_agg_scan_block_bind_groups,
            hir_functions_scatter_bind_group,
            hir_body_plan_collect_bind_group,
            hir_body_plan_validate_bind_group,
            hir_body_plan_validate_return_bind_group,
            hir_body_plan_validate_return_call_bind_group,
            hir_body_plan_validate_return_agg_call_bind_group,
            hir_body_plan_validate_return_nested_call_bind_group,
            hir_body_plan_validate_assign_bind_group,
            hir_body_plan_validate_control_bind_group,
            hir_body_plan_validate_agg_range_control_bind_group,
            hir_body_plan_validate_if_simple_bind_group,
            hir_body_plan_validate_print_simple_bind_group,
            hir_body_plan_validate_call_bind_group,
            hir_body_plan_validate_host_void_call_bind_group,
            hir_body_plan_validate_let_host_bind_group,
            hir_body_plan_validate_let_host_env_bind_group,
            hir_body_plan_validate_let_host_io_bind_group,
            hir_body_plan_validate_let_host_string_bind_group,
            hir_body_plan_validate_return_host_io_bind_group,
            hir_body_plan_validate_return_host_string_bind_group,
            hir_body_plan_validate_let_direct_call_bind_group,
            hir_body_plan_validate_let_call_bind_group,
            hir_body_plan_validate_let_call_status_bind_group,
            hir_body_plan_agg_direct_call_bind_group,
            hir_body_plan_agg_struct_bind_group,
            hir_body_plan_arrays_bind_group,
            hir_body_plan_functions_bind_group,
            hir_body_plan_finalize_bind_group,
            hir_body_clear_bind_group,
            hir_body_counts_bind_group,
            hir_body_scan_local_bind_group,
            hir_body_scan_block_bind_groups,
            hir_body_agg_call_arg_counts_bind_group,
            hir_body_agg_call_arg_count_scan_local_bind_group,
            hir_body_agg_call_arg_count_scan_block_bind_groups,
            hir_body_agg_call_arg_records_bind_group,
            hir_body_direct_call_arg_records_bind_group,
            hir_body_agg_call_arg_byte_scan_local_bind_group,
            hir_body_agg_call_arg_byte_scan_block_bind_groups,
            hir_body_agg_call_finalize_bind_group,
            hir_body_direct_call_finalize_bind_group,
            hir_body_status_bind_group,
            hir_body_scatter_bind_group,
            hir_body_scatter_frame_bind_group,
            hir_body_scatter_if_simple_bind_group,
            hir_body_scatter_return_scalar_bind_group,
            hir_body_scatter_return_expr_bind_group,
            hir_body_scatter_conversion_expr_bind_group,
            hir_body_scatter_let_const_bind_group,
            hir_body_scatter_expr_control_bind_group,
            hir_body_scatter_agg_range_control_bind_group,
            hir_body_scatter_let_direct_bind_group,
            hir_body_scatter_direct_nested_call_bind_group,
            hir_body_scatter_host_io_bind_group,
            hir_body_scatter_host_bind_group,
            hir_body_scatter_arrays_bind_group,
            hir_body_scatter_array_lean_bind_group,
            hir_body_scatter_agg_copy_bind_group,
            hir_body_scatter_agg_call_args_bind_group,
            hir_body_scatter_nested_call_args_bind_group,
            hir_body_scatter_agg_direct_call_bind_group,
            hir_body_scatter_return_agg_direct_call_bind_group,
            hir_body_scatter_return_member_bind_group,
            hir_body_scatter_member_expr_bind_group,
            hir_body_scatter_binary_direct_call_bind_group,
            hir_agg_body_bind_group,
            hir_assert_module_bind_group,
            hir_enum_match_records_bind_group,
            wasm_const_values_bind_group,
            module_type_lengths_bind_group,
            module_type_dispatch_args_bind_group,
            module_type_bytes_bind_group,
            module_status_bind_group,
            bind_group,
            pack_bind_group,
        })
    }
}
