import Lanius.Extraction.VerifiedFrontend.Surface.Number.Claims.Assembly
import Lanius.Extraction.VerifiedFrontend.Artifact.Number.Origins
import Lanius.Extraction.KernelSurfacePhases

namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option cbv.maxSteps 100000000
set_option cbv.warning false

kernel_surface_origins verifiedFrontendNumber_origin_claims_equal_kernel,
  verifiedFrontendNumber_origin_ids_dense_kernel,
  verifiedFrontendNumber_node_origins_checked_kernel,
  verifiedFrontendNumber_spelling_origins_checked_kernel,
  verifiedFrontendNumber_origin_coverage_checked_kernel,
  verifiedFrontendNumber_origins_checked_kernel for
  verifiedFrontendNumberArtifact, verifiedFrontendNumberView,
  verifiedFrontendNumberOrigins, verifiedFrontendNumberClaims

end Lanius.Extraction
