import Lanius.Extraction.VerifiedFrontend.Context.Allocations
import Lanius.Extraction.ArtifactPackContextPhaseChunks
namespace Lanius.Extraction
set_option maxRecDepth 100000
set_option maxHeartbeats 0
open ArtifactPackContextChecker
theorem verifiedFrontendCanonicalTokens_context_headers_present_kernel :
    (buildUnitHeaders verifiedFrontendCanonicalTokensAllocationKernel).isSome = true := by
  with_unfolding_all rfl
def verifiedFrontendCanonicalTokensContextHeadersKernel :=
  (buildUnitHeaders verifiedFrontendCanonicalTokensAllocationKernel).get
    verifiedFrontendCanonicalTokens_context_headers_present_kernel
theorem verifiedFrontendCanonicalTokens_context_headers_found_kernel :
    buildUnitHeaders verifiedFrontendCanonicalTokensAllocationKernel =
      some verifiedFrontendCanonicalTokensContextHeadersKernel :=
  parseOptionEqSomeGet verifiedFrontendCanonicalTokens_context_headers_present_kernel
end Lanius.Extraction
