{
    macro_rules! retain_x86_buffers {
        ($($buffer:expr),+ $(,)?) => {{
            let mut buffers = Vec::<RetainedX86Buffer>::new();
            $(buffers.push(RetainedX86Buffer::from($buffer));)+
            buffers
        }};
    }

    let mut retained_buffers = retain_x86_buffers![
        params_buf,
        active_hir_count_dispatch_args_buf,
        active_hir_plus_one_dispatch_args_buf,
        active_hir_scan_block_dispatch_args_buf,
        active_node_order_scan_dispatch_args_buf,
        active_node_order_scan_block_dispatch_args_buf,
        active_function_dispatch_args_buf,
        active_virtual_inst_dispatch_args_buf,
        active_virtual_next_call_dispatch_args_buf,
        active_virtual_regalloc_dispatch_args_buf,
        active_selected_inst_dispatch_args_buf,
        active_selected_scan_block_dispatch_args_buf,
        active_text_word_dispatch_args_buf,
        active_elf_header_word_dispatch_args_buf,
        func_meta_buf,
        func_meta_uniform_buf,
        node_tree_status_buf,
        expr_resolved_final_buf,
        node_func_buf,
        func_owner_scan_local_prefix_buf,
        func_owner_scan_block_sum_buf,
        func_owner_scan_prefix_a_buf,
        func_owner_scan_prefix_b_buf,
        enum_type_record_buf,
        enum_value_record_buf,
        enum_record_status_buf,
        match_record_buf,
        match_arm_owner_buf,
        match_return_node_buf,
        match_pattern_owner_buf,
        match_result_value_owner_buf,
        match_pattern_node_owner_buf,
        match_pattern_node_variant_buf,
        match_pattern_node_payload_decl_buf,
        match_pattern_first_use_node_buf,
        enclosing_return_node_a_buf,
        enclosing_return_node_b_buf,
        enclosing_let_node_a_buf,
        enclosing_let_node_b_buf,
        struct_type_record_buf,
        struct_access_record_buf,
        struct_store_record_buf,
        struct_record_status_buf,
        decl_layout_record_buf,
        decl_layout_status_buf,
        decl_node_by_token_buf,
        func_slot_by_index_buf,
        call_record_buf,
        call_type_record_buf,
        call_record_status_buf,
        const_value_record_buf,
        const_value_status_buf,
        const_value_status_uniform_buf,
        param_reg_record_buf,
        param_reg_status_buf,
        param_reg_status_uniform_buf,
        local_literal_record_buf,
        local_literal_status_buf,
        local_literal_status_uniform_buf,
        node_inst_order_record_buf,
        call_arg_lookup_record_buf,
        intrinsic_call_status_buf,
        call_abi_record_buf,
        call_abi_status_buf,
        call_abi_status_uniform_buf,
        node_inst_same_end_link_a_buf,
        node_inst_same_end_link_b_buf,
        node_inst_count_status_buf,
        node_inst_order_status_buf,
        node_inst_scan_local_prefix_buf,
        node_inst_range_start_buf,
        node_inst_range_info_buf,
        node_inst_range_status_buf,
        node_inst_subtree_bounds_status_buf,
        node_inst_location_status_buf,
        node_inst_gen_input_status_buf,
        virtual_inst_record_buf,
        virtual_inst_args_buf,
        virtual_inst_status_buf,
        virtual_func_first_row_status_buf,
        virtual_func_slot_buf,
        virtual_live_start_buf,
        virtual_live_end_buf,
        virtual_liveness_status_buf,
        virtual_next_call_a_buf,
        virtual_next_call_b_buf,
        virtual_next_call_status_buf,
        func_param_reg_mask_status_buf,
        virtual_value_def_flag_buf,
        virtual_value_def_row_buf,
        virtual_regalloc_param_rank_mask_buf,
        virtual_phys_reg_buf,
        virtual_call_live_reg_mask_buf,
        virtual_regalloc_status_buf,
        select_status_buf,
        size_status_buf,
        text_len_buf,
        text_status_buf,
        text_scan_block_sum_buf,
        text_scan_prefix_a_buf,
        text_scan_prefix_b_buf,
        encode_status_buf,
        elf_layout_buf,
        layout_status_buf,
        status_buf,
    ];
    if let Some(buffer) = match_pattern_first_variant_node_storage_buf {
        retained_buffers.push(RetainedX86Buffer::from(buffer));
    }
    if let Some(buffer) = match_pattern_first_payload_node_storage_buf {
        retained_buffers.push(RetainedX86Buffer::from(buffer));
    }
    if let Some(buffer) = empty_param_record_buf {
        retained_buffers.push(RetainedX86Buffer::from(buffer));
    }
    retained_buffers.push(RetainedX86Buffer::from(
        func_owner_scan_params_buf.into_buffer(),
    ));
    retained_buffers.push(RetainedX86Buffer::from(
        node_inst_scan_params_buf.into_buffer(),
    ));
    retained_buffers.push(RetainedX86Buffer::from(
        text_scan_params_buf.into_buffer(),
    ));
    retained_buffers.push(RetainedX86Buffer::from(
        virtual_next_call_params_buf.into_buffer(),
    ));
    retained_buffers.push(RetainedX86Buffer::from(
        virtual_regalloc_params_buf.into_buffer(),
    ));
    host_timer.stamp("retained_buffers_collected");

    let mut retained_bind_groups = vec![
        active_scan_dispatch_args_bind_group,
        node_inst_scan_input_clear_bind_group,
        node_order_dispatch_args_bind_group,
        virtual_dispatch_args_bind_group,
        output_dispatch_args_bind_group,
        node_tree_info_bind_group,
        func_bind_group,
        func_owner_scan_local_bind_group,
        func_assign_nodes_bind_group,
        expr_resolve_init_bind_group,
        enum_records_bind_group,
        match_records_bind_group,
        match_pattern_records_bind_group,
        enclosing_return_init_bind_group,
        enclosing_let_init_bind_group,
        enclosing_stmt_init_bind_group,
        return_match_records_bind_group,
        match_result_owner_init_bind_group,
        match_ownership_bind_group,
        match_pattern_owner_init_bind_group,
        match_pattern_finalize_bind_group,
        struct_records_bind_group,
        array_records_bind_group,
        expr_semantic_type_init_bind_group,
        decl_layout_bind_group,
        decl_widths_bind_group,
        const_values_bind_group,
        param_regs_bind_group,
        local_literals_bind_group,
        call_records_bind_group,
        call_callee_owner_init_bind_group,
        call_arg_values_bind_group,
        intrinsic_calls_bind_group,
        call_abi_bind_group,
        node_inst_same_end_rank_init_bind_group,
        node_inst_end_counts_bind_group,
        node_inst_counts_bind_group,
        enclosing_loop_init_bind_group,
        node_inst_scan_local_bind_group,
        node_inst_prefix_scan_bind_group,
        node_inst_order_bind_group,
        node_inst_subtree_bounds_bind_group,
        node_inst_locations_bind_group,
        node_inst_gen_inputs_bind_group,
        virtual_inst_clear_dispatch_args_bind_group,
        virtual_inst_clear_bind_group,
        node_inst_gen_bind_group,
        aggregate_literal_return_copy_bind_group,
        node_inst_gen_aggregate_copy_bind_group,
        virtual_func_rows_init_bind_group,
        virtual_func_first_row_bind_group,
        virtual_func_span_max_bind_group,
        virtual_regalloc_dispatch_args_bind_group,
        virtual_regalloc_bind_group,
        virtual_spans_fixed_barrier_bind_group,
        virtual_param_masks_bind_group,
        virtual_liveness_init_bind_group,
        virtual_liveness_bind_group,
        select_bind_group,
        inst_size_bind_group,
        text_scan_local_bind_group,
        text_offsets_bind_group,
        encode_bind_group,
        elf_layout_bind_group,
        elf_bind_group,
    ];
    retained_bind_groups.extend(func_owner_scan_block_bind_groups);
    retained_bind_groups.extend(func_assign_nodes_step_bind_groups);
    retained_bind_groups.extend(expr_resolve_step_bind_groups);
    retained_bind_groups.extend(enclosing_return_step_bind_groups);
    retained_bind_groups.extend(enclosing_let_step_bind_groups);
    retained_bind_groups.extend(match_result_owner_step_bind_groups);
    retained_bind_groups.extend(enclosing_stmt_step_bind_groups);
    retained_bind_groups.extend(call_callee_owner_step_bind_groups);
    retained_bind_groups.extend(match_pattern_owner_step_bind_groups);
    retained_bind_groups.extend(node_inst_same_end_rank_step_bind_groups);
    retained_bind_groups.extend(expr_semantic_type_step_bind_groups);
    retained_bind_groups.extend(enclosing_loop_step_bind_groups);
    retained_bind_groups.extend(node_inst_scan_block_bind_groups);
    retained_bind_groups.extend(virtual_next_call_bind_groups);
    retained_bind_groups.extend(text_scan_block_bind_groups);
    host_timer.stamp("retained_bind_groups_collected");

    let recorded = RecordedX86Codegen {
        output_capacity,
        output_status_offset,
        _retained_buffers: retained_buffers,
        _retained_bind_groups: retained_bind_groups,
        out_buf,
        output_readback,
        status_trace_readback,
    };
    host_timer.stamp("recorded_result_ready");
    recorded
}
