#!/usr/bin/env python3
"""Generate public language-slice reference tables from the TSV inventory."""

from __future__ import annotations

import argparse
import csv
import subprocess
import sys
from collections import Counter
from pathlib import Path


REQUIRED_COLUMNS = (
    "kind",
    "id",
    "status",
    "evidence_scope",
    "evidence_test",
    "evidence_contract",
    "notes",
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate language-slice reference tables from docs/language_slice_unstable_alpha.tsv."
    )
    parser.add_argument(
        "--input",
        default="docs/language_slice_unstable_alpha.tsv",
        help="language-slice TSV input path",
    )
    parser.add_argument("--output", help="write Markdown output to this path")
    parser.add_argument(
        "--check",
        help="compare generated Markdown with this path and exit nonzero if stale",
    )
    args = parser.parse_args()

    repo = repo_root()
    rows = read_slice_rows(repo / args.input)
    markdown = render_markdown(Path(args.input), rows)

    if args.check:
        target = Path(args.check)
        try:
            current = target.read_text(encoding="utf-8")
        except FileNotFoundError:
            sys.stderr.write(f"language_slice_summary: missing generated file {target}\n")
            return 1
        if current != markdown:
            sys.stderr.write(f"language_slice_summary: generated output is stale: {target}\n")
            return 1
        return 0

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown, encoding="utf-8")
    else:
        sys.stdout.write(markdown)
    return 0


def repo_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        return Path(result.stdout.strip())
    return Path.cwd()


def read_slice_rows(path: Path) -> list[dict[str, str]]:
    lines: list[str] = []
    try:
        raw_lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    except FileNotFoundError:
        raise SystemExit(f"language_slice_summary: missing input {path}")

    for line in raw_lines:
        if line.startswith("# kind"):
            lines.append(line[2:])
        elif line.startswith("#"):
            continue
        elif line.strip():
            lines.append(line)

    reader = csv.DictReader(lines, delimiter="\t")
    if reader.fieldnames is None:
        raise SystemExit(f"language_slice_summary: {path} has no TSV header")

    missing = [column for column in REQUIRED_COLUMNS if column not in reader.fieldnames]
    if missing:
        joined = ", ".join(missing)
        raise SystemExit(f"language_slice_summary: {path} missing columns: {joined}")

    rows = []
    for index, row in enumerate(reader, 1):
        normalized = {column: (row.get(column) or "").strip() for column in REQUIRED_COLUMNS}
        missing_values = [column for column, value in normalized.items() if not value]
        if missing_values:
            joined = ", ".join(missing_values)
            raise SystemExit(f"language_slice_summary: row {index} missing values: {joined}")
        rows.append(normalized)
    return rows


def render_markdown(input_path: Path, rows: list[dict[str, str]]) -> str:
    kind_order = ordered_unique(row["kind"] for row in rows)
    status_counts = Counter(row["status"] for row in rows)
    contract_counts = Counter(row["evidence_contract"] for row in rows)
    kind_counts = Counter(row["kind"] for row in rows)

    lines: list[str] = [
        "# Generated unstable-alpha Language Slice",
        "",
        f"Generated by `tools/language_slice_summary.py` from `{input_path.as_posix()}`.",
        "Regenerate this file instead of editing it by hand.",
        "",
        "```bash",
        "tools/language_slice_summary.py --output docs/language/generated/unstable-alpha-slice.md",
        "tools/language_slice_summary.py --check docs/language/generated/unstable-alpha-slice.md",
        "```",
        "",
        "## Inventory Summary",
        "",
    ]
    lines.extend(
        table(
            ("Item", "Count"),
            [
                ("Rows", str(len(rows))),
                *[(f"Status: {status}", str(count)) for status, count in sorted_counter(status_counts)],
                *[
                    (f"Evidence: {contract}", str(count))
                    for contract, count in sorted_counter(contract_counts)
                ],
            ],
        )
    )

    lines.extend(["", "## Rows By Kind", ""])
    lines.extend(
        table(
            ("Kind", "Rows"),
            [(kind, str(kind_counts[kind])) for kind in kind_order],
        )
    )

    planned = [row for row in rows if row["status"] != "bounded"]
    lines.extend(["", "## Non-Bounded Rows", ""])
    if planned:
        lines.extend(
            table(
                ("Kind", "ID", "Status", "Evidence", "Notes"),
                [
                    (
                        row["kind"],
                        row["id"],
                        row["status"],
                        row["evidence_contract"],
                        row["notes"],
                    )
                    for row in planned
                ],
            )
        )
    else:
        lines.append("All rows are currently `bounded`.")

    for kind in kind_order:
        kind_rows = [row for row in rows if row["kind"] == kind]
        lines.extend(["", f"## {kind_title(kind)}", ""])
        lines.extend(
            table(
                ("ID", "Status", "Evidence", "Scope", "Test", "Notes"),
                [
                    (
                        row["id"],
                        row["status"],
                        row["evidence_contract"],
                        row["evidence_scope"],
                        row["evidence_test"],
                        row["notes"],
                    )
                    for row in kind_rows
                ],
            )
        )

    lines.append("")
    return "\n".join(lines)


def ordered_unique(values) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out


def sorted_counter(counter: Counter[str]) -> list[tuple[str, int]]:
    return sorted(counter.items(), key=lambda item: (-item[1], item[0]))


def kind_title(kind: str) -> str:
    return kind.replace("-", " ").title()


def table(headers: tuple[str, ...], rows: list[tuple[str, ...]]) -> list[str]:
    lines = [
        "| " + " | ".join(escape_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    if not rows:
        lines.append("| " + " | ".join("none" for _ in headers) + " |")
        return lines
    for row in rows:
        lines.append("| " + " | ".join(escape_cell(cell) for cell in row) + " |")
    return lines


def escape_cell(value: str) -> str:
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


if __name__ == "__main__":
    raise SystemExit(main())
