import Lanius.Basic

namespace Lanius.Surface

abbrev Name := String

mutual
  inductive PathSegment where
    | mk (name : Name) (arguments : List TypeExpr)

  inductive TypeExpr where
    | path (segments : List PathSegment)
    | array (element : TypeExpr) (length : ArrayLength)
    | slice (element : TypeExpr)
    | reference (referent : TypeExpr)

  inductive ArrayLength where
    | literal (value : Nat)
    | parameter (name : Name)
end

structure Path where
  segments : List PathSegment

inductive Literal where
  | integer (text : String)
  | float (text : String)
  | string (value : String)
  | character (value : Char)
  | boolean (value : Bool)
deriving DecidableEq

inductive UnaryOp where
  | positive
  | negative
  | logicalNot

inductive BinaryOp where
  | logicalOr
  | logicalAnd
  | bitOr
  | bitXor
  | bitAnd
  | equal
  | notEqual
  | less
  | greater
  | lessEqual
  | greaterEqual
  | shiftLeft
  | shiftRight
  | add
  | subtract
  | multiply
  | divide
  | remainder

inductive AssignOp where
  | set
  | add
  | subtract
  | multiply
  | divide
  | remainder
  | bitXor
  | shiftLeft
  | shiftRight
  | bitAnd
  | bitOr

inductive RangeKind where
  | full
  | from
  | toExclusive
  | toInclusive
  | exclusive
  | inclusive

mutual
  inductive Pattern where
    | wildcard
    | path (path : Path) (payload : List Pattern)
    | integer (text : String)
    | boolean (value : Bool)

  inductive Expr where
    | literal (literal : Literal)
    | path (path : Path)
    | selfValue
    | array (elements : List Expr)
    | structValue (path : Path) (fields : List (Name × Expr))
    | unary (op : UnaryOp) (operand : Expr)
    | binary (op : BinaryOp) (left right : Expr)
    | assign (op : AssignOp) (place value : Expr)
    | call (callee : Expr) (arguments : List Expr)
    | index (base index : Expr)
    | member (base : Expr) (name : Name)
    | matchValue (scrutinee : Expr) (arms : List (Pattern × Expr))

  /-- The concrete range grammar admits either an integer token or a name with
      a postfix call/index/member chain. `RangeBoundPostfix` below records the
      latter shape independently of its eventual `i32` type. -/
  inductive RangeBound where
    | integer (text : String)
    | postfix (expression : Expr)

  inductive ForIterable where
    | path (path : Path)
    | range (kind : RangeKind) (start stop : Option RangeBound)

  inductive Stmt where
    | letLocal (name : Name) (type : Option TypeExpr) (initializer : Option Expr)
    | returnValue (value : Option Expr)
    | ifThenElse (condition : Expr) (thenBody elseBody : List Stmt)
    | whileLoop (condition : Expr) (body : List Stmt)
    | forLoop (name : Name) (iterable : ForIterable) (body : List Stmt)
    | breakLoop
    | continueLoop
    | block (body : List Stmt)
    | expression (expression : Expr)
end

/-- Syntactic subset generated by `range_bound_ident postfix_tail`. Arguments
    and index operands are ordinary expressions, but the callee/base chain
    begins with one unqualified name. -/
inductive RangeBoundPostfix : Expr → Prop where
  | name : RangeBoundPostfix (.path { segments := [.mk name []] })
  | call
      (base : RangeBoundPostfix callee) :
      RangeBoundPostfix (.call callee arguments)
  | index
      (base : RangeBoundPostfix expression) :
      RangeBoundPostfix (.index expression index)
  | member
      (base : RangeBoundPostfix expression) :
      RangeBoundPostfix (.member expression name)

structure TypeParameter where
  name : Name
  bounds : List TypeExpr := []

structure ConstParameter where
  name : Name
  type : TypeExpr

inductive GenericParameter where
  | type (parameter : TypeParameter)
  | const (parameter : ConstParameter)

structure WherePredicate where
  parameter : Name
  bounds : List TypeExpr

inductive Parameter where
  | named (name : Name) (type : TypeExpr)
  | selfValue (type : Option TypeExpr)
  | selfReference

structure Function where
  name : Name
  isPublic : Bool := false
  genericParameters : List GenericParameter := []
  parameters : List Parameter := []
  returnType : Option TypeExpr := none
  wherePredicates : List WherePredicate := []
  body : List Stmt

structure ExternFunction where
  name : Name
  isPublic : Bool := false
  abi : Option String := none
  genericParameters : List GenericParameter := []
  parameters : List Parameter := []
  returnType : Option TypeExpr := none
  wherePredicates : List WherePredicate := []

structure StructField where
  name : Name
  type : TypeExpr

structure StructDecl where
  name : Name
  isPublic : Bool := false
  genericParameters : List GenericParameter := []
  wherePredicates : List WherePredicate := []
  fields : List StructField := []

structure EnumVariant where
  name : Name
  payload : List TypeExpr := []

structure EnumDecl where
  name : Name
  isPublic : Bool := false
  genericParameters : List GenericParameter := []
  wherePredicates : List WherePredicate := []
  variants : List EnumVariant := []

structure TraitMethod where
  signature : ExternFunction

structure TraitDecl where
  name : Name
  isPublic : Bool := false
  genericParameters : List GenericParameter := []
  wherePredicates : List WherePredicate := []
  methods : List TraitMethod := []

structure ImplDecl where
  isPublic : Bool := false
  genericParameters : List GenericParameter := []
  traitType : Option TypeExpr := none
  receiverType : TypeExpr
  wherePredicates : List WherePredicate := []
  methods : List Function := []

inductive Item where
  | module (path : Path)
  | importPath (path : Path)
  | importString (path : String)
  | function (declaration : Function)
  | externFunction (declaration : ExternFunction)
  | constant (name : Name) (isPublic : Bool) (type : TypeExpr) (value : Expr)
  | typeAlias (name : Name) (isPublic : Bool) (parameters : List GenericParameter)
      (predicates : List WherePredicate) (target : TypeExpr)
  | structure (declaration : StructDecl)
  | enumeration (declaration : EnumDecl)
  | trait (declaration : TraitDecl)
  | implementation (declaration : ImplDecl)

structure File where
  items : List Item

end Lanius.Surface
