import Lanius.Extraction.VerifiedFrontend.Surface.CanonicalTokens.Parse.Trace
import Lanius.Extraction.SurfaceReconstruct
namespace Lanius.Extraction
set_option maxRecDepth 500000
set_option maxHeartbeats 0
theorem verifiedFrontendCanonicalTokens_proposed_present_kernel : verifiedFrontendCanonicalTokensArtifact.surface.isSome = true := by
  with_unfolding_all rfl
def verifiedFrontendCanonicalTokensProposedKernel : SurfaceFile :=
  verifiedFrontendCanonicalTokensArtifact.surface.get verifiedFrontendCanonicalTokens_proposed_present_kernel
theorem verifiedFrontendCanonicalTokens_proposed_found_kernel :
    verifiedFrontendCanonicalTokensArtifact.surface = some verifiedFrontendCanonicalTokensProposedKernel :=
  parseOptionEqSomeGet verifiedFrontendCanonicalTokens_proposed_present_kernel
end Lanius.Extraction
